export const booksList = [
  {
    nameEn: "Sahih Al-Bukhari",
    nameBn: "সহীহ আল-বুখারী",
    nameAr: "صحيح البخاري",
    nameHi: "सहीह आल-बुखारी",
    nameUr: "صحیح البخاری",
    nameTa: "சஹீஹ் அல்-புகாரி",
    nameDe: "Sahih Al-Bukhari",
    nameEs: "Sahih Al-Bujari",
    nameFr: "Sahih Al-Bukhari",
    namePt: "Sahih Al-Bukhari",
    nameTr: "Sahih Al-Buhari",
    nameIt: "Sahih Al-Bukhari",
    nameNl: "Sahih Al-Bukhari",
    nameRu: "Сахих Аль-Бухари",
    nameFil: "Sahih Al-Bukhari",
    nameTh: "ศอฮีฮ์ อัล-บุคอรี",
    nameId: "Shahih Al-Bukhari",
    nameJa: "サヒーフ・アル＝ブハーリー",
    nameKo: "사히 알 부카리",
    namePl: "Sahih Al-Bukhari",
    nameVi: "Sahih Al-Bukhari",
    nameZh: "圣训布哈里集",
    code: "(d. 256 AH) C",
    id: "bukhari",
  },
  {
    nameEn: "Sahih Muslim",
    nameBn: "সহীহ মুসলিম",
    nameAr: "صحيح مسلم",
    nameHi: "सहीह मुस्लिम",
    nameUr: "صحیح مسلم",
    nameTa: "சஹீஹ் முஸ்லிம்",
    nameDe: "Sahih Muslim",
    nameEs: "Sahih Muslim",
    nameFr: "Sahih Muslim",
    namePt: "Sahih Muslim",
    nameTr: "Sahih Müslim",
    nameIt: "Sahih Muslim",
    nameNl: "Sahih Muslim",
    nameRu: "Сахих Муслим",
    nameFil: "Sahih Muslim",
    nameTh: "ศอฮีฮ์ มุสลิม",
    nameId: "Shahih Muslim",
    nameJa: "サヒーフ・ムスリム",
    nameKo: "사히 무슬림",
    namePl: "Sahih Muslim",
    nameVi: "Sahih Muslim",
    nameZh: "圣训穆斯林集",
    code: "(d. 261 AH) C",
    id: "muslim",
  },
  {
    nameEn: "Sunan Ibn Mājah",
    nameBn: "সুনান ইবনে মাজাহ",
    nameAr: "سنن ابن ماجه",
    nameHi: "सुनन इब्न माजा",
    nameUr: "سنن ابن ماجہ",
    nameTa: "ஸுனன் இப்னு மாஜா",
    nameDe: "Sunan Ibn Majah",
    nameEs: "Sunan Ibn Majah",
    nameFr: "Sunan Ibn Majah",
    namePt: "Sunan Ibn Majah",
    nameTr: "Sünen İbn Mace",
    nameIt: "Sunan Ibn Majah",
    nameNl: "Sunan Ibn Majah",
    nameRu: "Сунан Ибн Маджа",
    nameFil: "Sunan Ibn Majah",
    nameTh: "ซุนัน อิบนุ มาญะห์",
    nameId: "Sunan Ibnu Majah",
    nameJa: "スナン・イブン・マージャ",
    nameKo: "수난 이븐 마자",
    namePl: "Sunan Ibn Majah",
    nameVi: "Sunan Ibn Majah",
    nameZh: "圣训伊本马哲集",
    code: "(d. 273 AH) C",
    id: "ibnmajah",
  },
  {
    nameEn: "Sunan Abi Dawud",
    nameBn: "সুনান আবু দাউদ",
    nameAr: "سنن أبي داود",
    nameHi: "सुनन अबू दाऊद",
    nameUr: "سنن ابوداؤد",
    nameTa: "ஸுனன் அபூ தாவுத்",
    nameDe: "Sunan Abi Dawud",
    nameEs: "Sunan Abi Dawud",
    nameFr: "Sunan Abi Dawud",
    namePt: "Sunan Abi Dawud",
    nameTr: "Sünen Ebu Davud",
    nameIt: "Sunan Abi Dawud",
    nameNl: "Sunan Abi Dawud",
    nameRu: "Сунан Абу Дауд",
    nameFil: "Sunan Abi Dawud",
    nameTh: "ซุนัน อบู ดาวูด",
    nameId: "Sunan Abu Dawud",
    nameJa: "スナン・アブー・ダーウード",
    nameKo: "수난 아부 다우드",
    namePl: "Sunan Abi Dawud",
    nameVi: "Sunan Abi Dawud",
    nameZh: "圣训艾卜达伍德集",
    code: "(d. 275 AH)",
    id: "abudawud",
  },
  {
    nameEn: "Sunan At-Tirmidhi",
    nameBn: "সুনান আত-তিরমিজি",
    nameAr: "سنن الترمذي",
    nameHi: "सुनन अत-तिर्मिज़ी",
    nameUr: "سنن الترمذی",
    nameTa: "ஸுனன் அத்-திர்மிதி",
    nameDe: "Sunan At-Tirmidhi",
    nameEs: "Sunan At-Tirmidhi",
    nameFr: "Sunan At-Tirmidhi",
    namePt: "Sunan At-Tirmidhi",
    nameTr: "Sünen Tirmizi",
    nameIt: "Sunan At-Tirmidhi",
    nameNl: "Sunan At-Tirmidhi",
    nameRu: "Сунан ат-Тирмизи",
    nameFil: "Sunan At-Tirmidhi",
    nameTh: "ซุนัน อัต-ติรมิซี",
    nameId: "Sunan At-Tirmidhi",
    nameJa: "スナン・アット・ティルミズィー",
    nameKo: "수난 앗티르미지",
    namePl: "Sunan At-Tirmidhi",
    nameVi: "Sunan At-Tirmidhi",
    nameZh: "圣训提尔密集",
    code: "(d. 279 AH)",
    id: "tirmidhi",
  },
  {
    nameEn: "Sunan An-Nasa'i",
    nameBn: "সুনান আন-নাসাঈ",
    nameAr: "سنن النسائي",
    nameHi: "सुनन अन-नसाई",
    nameUr: "سنن النسائی",
    nameTa: "ஸுனன் அன்நஸாயி",
    nameDe: "Sunan An-Nasa'i",
    nameEs: "Sunan An-Nasa'i",
    nameFr: "Sunan An-Nasa'i",
    namePt: "Sunan An-Nasa'i",
    nameTr: "Sünen Nesai",
    nameIt: "Sunan An-Nasa'i",
    nameNl: "Sunan An-Nasa'i",
    nameRu: "Сунан ан-Насаи",
    nameFil: "Sunan An-Nasa'i",
    nameTh: "ซุนัน อัน-นะสาอี",
    nameId: "Sunan An-Nasa'i",
    nameJa: "スナン・アン＝ナサーイー",
    nameKo: "수난 안 나사이",
    namePl: "Sunan An-Nasa'i",
    nameVi: "Sunan An-Nasa'i",
    nameZh: "圣训奈萨仪集",
    code: "(d. 303 AH)",
    id: "nasai",
  },
  {
    nameEn: "Muwatta Imam Malik",
    nameBn: "মুয়াত্তা ইমাম মালিক",
    nameAr: "الموطأ الإمام مالك",
    nameHi: "मुवत्ता इमाम मालिक",
    nameUr: "موطا امام مالک",
    nameTa: "முவத்தா இமாம் மாலிக்",
    nameDe: "Muwatta Imam Malik",
    nameEs: "Muwatta Imam Malik",
    nameFr: "Muwatta Imam Malik",
    namePt: "Muwatta Imam Malik",
    nameTr: "Muvatta İmam Malik",
    nameIt: "Muwatta Imam Malik",
    nameNl: "Muwatta Imam Malik",
    nameRu: "Аль-Муватта Имама Малика",
    nameFil: "Muwatta Imam Malik",
    nameTh: "มูวัตตาอิมามมาลิก",
    nameId: "Muwatta Imam Malik",
    nameJa: "ムワッター・イマーム・マーリク",
    nameKo: "무와따 이맘 말리크",
    namePl: "Muwatta Imam Malik",
    nameVi: "Muwatta Imam Malik",
    nameZh: "穆瓦塔伊玛目马立克",
    code: "(d. 179 AH)",
    id: "muwatta",
  },
  {
    nameEn: "Musnad Ahmad",
    nameBn: "মুসনাদ আহমদ",
    nameAr: "مسند أحمد",
    nameHi: "मुसनद अहमद",
    nameUr: "مسند احمد",
    nameTa: "முஸ்நாத் அகமத்",
    nameDe: "Musnad Ahmad",
    nameEs: "Musnad Ahmad",
    nameFr: "Musnad Ahmad",
    namePt: "Musnad Ahmad",
    nameTr: "Müsned Ahmed",
    nameIt: "Musnad Ahmad",
    nameNl: "Musnad Ahmad",
    nameRu: "Муснад Ахмада",
    nameFil: "Musnad Ahmad",
    nameTh: "มุสนัดอะห์หมัด",
    nameId: "Musnad Ahmad",
    nameJa: "ムスナド・アフマド",
    nameKo: "무스나드 아흐마드",
    namePl: "Musnad Ahmad",
    nameVi: "Musnad Ahmad",
    nameZh: "穆斯奈德艾哈迈德",
    code: "(d. 241 AH)",
    id: "musnad-ahmad",
  },
  {
    nameEn: "Sunan Ad-Darimi",
    nameBn: "সুনান আদ-দারিমি",
    nameAr: "سنن الدارمي",
    nameHi: "सुनन अद-दारीमी",
    nameUr: "سنن الدارمی",
    nameTa: "ஸுனன் அத்-தாரிமி",
    nameDe: "Sunan Ad-Darimi",
    nameEs: "Sunan Ad-Darimi",
    nameFr: "Sunan Ad-Darimi",
    namePt: "Sunan Ad-Darimi",
    nameTr: "Sünen Darimi",
    nameIt: "Sunan Ad-Darimi",
    nameNl: "Sunan Ad-Darimi",
    nameRu: "Сунан ад-Дарими",
    nameFil: "Sunan Ad-Darimi",
    nameTh: "ซุนัน อัด-ดารีมี",
    nameId: "Sunan Ad-Darimi",
    nameJa: "スナン・アッ＝ダーリミー",
    nameKo: "수난 아드다리미",
    namePl: "Sunan Ad-Darimi",
    nameVi: "Sunan Ad-Darimi",
    nameZh: "圣训达里米集",
    code: "(d. 255 AH)",
    id: "darimi",
  },
  {
    nameEn: "Al-Adab Al-Mufrad",
    nameBn: "আল-আদাবুল মুফরাদ",
    nameAr: "الأدب المفرد",
    nameHi: "अल-अदब अल-मुफ़रद",
    nameUr: "الادب المفرد",
    nameTa: "அல்-அதப் அல்-முஃப்ரத்",
    nameDe: "Al-Adab Al-Mufrad",
    nameEs: "Al-Adab Al-Mufrad",
    nameFr: "Al-Adab Al-Mufrad",
    namePt: "Al-Adab Al-Mufrad",
    nameTr: "El-Edebü'l-Müfred",
    nameIt: "Al-Adab Al-Mufrad",
    nameNl: "Al-Adab Al-Mufrad",
    nameRu: "Аль-Адаб Аль-Муфрад",
    nameFil: "Al-Adab Al-Mufrad",
    nameTh: "อัล-อะดับ อัล-มุฟรอด",
    nameId: "Al-Adab Al-Mufrad",
    nameJa: "アル＝アダブ・アル＝ムフラド",
    nameKo: "알아답 알무프라드",
    namePl: "Al-Adab Al-Mufrad",
    nameVi: "Al-Adab Al-Mufrad",
    nameZh: "独特礼仪",
    code: "(by Imam al-Bukhari)",
    id: "adab-mufrad",
  },
  {
    nameEn: "An-Nawawi’s Forty",
    nameBn: "আন-নাওয়ীর চল্লিশ হাদিস",
    nameAr: "أربعون حديثاً للنووي",
    nameHi: "अल-नववी की चालीस हदीस",
    nameUr: "اربعون حدیثاً للنووی",
    nameTa: "அல்-நவவியின் நாற்பது ஹதீஸ்கள்",
    nameDe: "An-Nawawi’s Forty",
    nameEs: "Las Cuarenta de An-Nawawi",
    nameFr: "Les Quarante de An-Nawawi",
    namePt: "As Quarenta de An-Nawawi",
    nameTr: "An-Nawawi’nin Kırk Hadisi",
    nameIt: "Le Quaranta di An-Nawawi",
    nameNl: "An-Nawawi’s Veertig",
    nameRu: "Сорок хадисов Ан-Навави",
    nameFil: "An-Nawawi’s Forty",
    nameTh: "ฮะดีษสี่สิบของอัล-นาวาวี",
    nameId: "An-Nawawi’s Forty",
    nameJa: "アン＝ナワウィの四十",
    nameKo: "안-나위의 사십",
    namePl: "An-Nawawi’s Forty",
    nameVi: "An-Nawawi’s Forty",
    nameZh: "纳瓦维四十条哈迪斯",
    code: "(by Imam An-Nawawi)",
    id: "nawawi-forty",
  },
  {
    nameEn: "Mishkat Al-Masabih",
    nameBn: "মিশকাত আল-মাসাবিহ",
    nameAr: "مشكات المصابيح",
    nameHi: "मिश्कत अल-मसाबिह",
    nameUr: "مشکات المصابیح",
    nameTa: "மிஷ்கத் அல்-மசாபிஹ்",
    nameDe: "Mishkat Al-Masabih",
    nameEs: "Mishkat Al-Masabih",
    nameFr: "Mishkat Al-Masabih",
    namePt: "Mishkat Al-Masabih",
    nameTr: "Mişkatü’l-Mesabih",
    nameIt: "Mishkat Al-Masabih",
    nameNl: "Mishkat Al-Masabih",
    nameRu: "Мишкат аль-Масабих",
    nameFil: "Mishkat Al-Masabih",
    nameTh: "มิสกัต อัล-มาซาบิห์",
    nameId: "Mishkat Al-Masabih",
    nameJa: "ミシュカット・アル＝マサービフ",
    nameKo: "미슈캇 알-마사비흐",
    namePl: "Mishkat Al-Masabih",
    nameVi: "Mishkat Al-Masabih",
    nameZh: "灯塔集",
    code: "(by Al-Baghawi)",
    id: "mishkat-al-masabih",
  },
  {
    nameEn: "Riyad As-Salihin",
    nameBn: "রিয়াদ আস-সালিহিন",
    nameAr: "رياض الصالحين",
    nameHi: "रियाद अस-सलिहीन",
    nameUr: "ریاض الصالحین",
    nameTa: "ரியாத் அஸ்-சாலிஹீன்",
    nameDe: "Riyad As-Salihin",
    nameEs: "Riyad As-Salihin",
    nameFr: "Riyad As-Salihin",
    namePt: "Riyad As-Salihin",
    nameTr: "Riyad-üs-Salihîn",
    nameIt: "Riyad As-Salihin",
    nameNl: "Riyad As-Salihin",
    nameRu: "Рияд ас-Салихин",
    nameFil: "Riyad As-Salihin",
    nameTh: "ริยาด อัล-ซาลิฮีน",
    nameId: "Riyad As-Salihin",
    nameJa: "リヤード・アス＝サリーヒーン",
    nameKo: "리야드 아스-살리힌",
    namePl: "Riyad As-Salihin",
    nameVi: "Riyad As-Salihin",
    nameZh: "善人之园",
    code: "(by Imam An-Nawawi)",
    id: "riyad-as-salihin",
  },
  {
    nameEn: "Bulūgh Al-Marām",
    nameBn: "বুলুগ আল-মারাম",
    nameAr: "بلوغ المرام",
    nameHi: "बुलूघ अल-मराम",
    nameUr: "بلوغ المرام",
    nameTa: "புலூக் அல்-மராம்",
    nameDe: "Bulūgh Al-Marām",
    nameEs: "Bulūgh Al-Marām",
    nameFr: "Bulūgh Al-Marām",
    namePt: "Bulūgh Al-Marām",
    nameTr: "Bulûğ el-Merâm",
    nameIt: "Bulūgh Al-Marām",
    nameNl: "Bulūgh Al-Marām",
    nameRu: "Булуг аль-Марам",
    nameFil: "Bulūgh Al-Marām",
    nameTh: "บูลูก อัล-มาราม",
    nameId: "Bulūgh Al-Marām",
    nameJa: "ブルーグ・アル＝マラム",
    nameKo: "불루그 알-마람",
    namePl: "Bulūgh Al-Marām",
    nameVi: "Bulūgh Al-Marām",
    nameZh: "通往目标",
    code: "(by Ibn Hajar al-Asqalani)",
    id: "bulugh-al-maram",
  },
  {
    nameEn: "Hisn Al-Muslim",
    nameBn: "হিসন আল-মুসলিম",
    nameAr: "حصن المسلم",
    nameHi: "हिस्न अल-मुस्लिम",
    nameUr: "حصن المسلم",
    nameTa: "ஹிஸ்ன் அல்-முஸ்லிம்",
    nameDe: "Hisn Al-Muslim",
    nameEs: "Hisn Al-Muslim",
    nameFr: "Hisn Al-Muslim",
    namePt: "Hisn Al-Muslim",
    nameTr: "Hisn-ül Muslim",
    nameIt: "Hisn Al-Muslim",
    nameNl: "Hisn Al-Muslim",
    nameRu: "Хисн аль-Муслим",
    nameFil: "Hisn Al-Muslim",
    nameTh: "หิสน อัล-มุสลิม",
    nameId: "Hisn Al-Muslim",
    nameJa: "ヒスン・アル＝ムスリム",
    nameKo: "히스눈 알-무슬림",
    namePl: "Hisn Al-Muslim",
    nameVi: "Hisn Al-Muslim",
    nameZh: "穆斯林堡垒",
    code: "(by Sa'id bin Ali al-Qahtani)",
    id: "hisn-al-muslim",
  },
  {
    nameEn: "Ash-Shama'il Al-Muhammadiyah",
    nameBn: "আশ-শামাইল আল-মুহাম্মাদিয়াহ",
    nameAr: "الشمايل المحمدية",
    nameHi: "अश-शमाइल अल-मुहम्मदीया",
    nameUr: "الشمايل المحمدية",
    nameTa: "அஷ்-ஷமாயில் அல்-முஹம்மதியாஹ",
    nameDe: "Ash-Shama'il Al-Muhammadiyah",
    nameEs: "Ash-Shama'il Al-Muhammadiyah",
    nameFr: "Ash-Shama'il Al-Muhammadiyah",
    namePt: "Ash-Shama'il Al-Muhammadiyah",
    nameTr: "Eş-Şamail el-Muhammediyye",
    nameIt: "Ash-Shama'il Al-Muhammadiyah",
    nameNl: "Ash-Shama'il Al-Muhammadiyah",
    nameRu: "Аш-Шамаиль аль-Мухаммадийя",
    nameFil: "Ash-Shama'il Al-Muhammadiyah",
    nameTh: "อัช-ชะไมล์ อัล-มูฮัมมาดียะห์",
    nameId: "Ash-Shama'il Al-Muhammadiyah",
    nameJa: "アシュ・シャマイル・アル＝ムハンマディーヤ",
    nameKo: "아쉬-샤마일 알-무함마디야",
    namePl: "Ash-Shama'il Al-Muhammadiyah",
    nameVi: "Ash-Shama'il Al-Muhammadiyah",
    nameZh: "穆罕默德的美德",
    code: "(by Imam At-Tirmidhi)",
    id: "ash-shama'il-al-muhammadiyah",
  },
  {
    nameEn: "Fazail E Amaal",
    nameBn: "ফযায়েল-ই-আমাল",
    nameAr: "فضائل الأعمال",
    nameHi: "फ़ज़ाइल-ए-आमल",
    nameUr: "فضائل الأعمال",
    nameTa: "பஜாயில்-இ-ஆமல்",
    nameDe: "Fazail E Amaal",
    nameEs: "Fazail E Amaal",
    nameFr: "Fazail E Amaal",
    namePt: "Fazail E Amaal",
    nameTr: "Fazail E Amaal",
    nameIt: "Fazail E Amaal",
    nameNl: "Fazail E Amaal",
    nameRu: "Фазайл Э Амал",
    nameFil: "Fazail E Amaal",
    nameTh: "ฟะซาอิล-อามาล",
    nameId: "Fazail E Amaal",
    nameJa: "ファザイル・エ・アマール",
    nameKo: "파자일-이-아말",
    namePl: "Fazail E Amaal",
    nameVi: "Fazail E Amaal",
    nameZh: "善行的优点",
    code: "(by Shaikh Zakariyya Kandhalwi)",
    id: "fazail-e-amal",
  },
  {
    nameEn: "Faza'il E Sadaqaat",
    nameBn: "ফযায়েল-ই-সদকাত",
    nameAr: "فضائل الصدقات",
    nameHi: "फ़ज़ाइल-ए-सदकात",
    nameUr: "فضائل الصدقات",
    nameTa: "பஜாயில்-இ-சதகாத்",
    nameDe: "Faza'il E Sadaqaat",
    nameEs: "Faza'il E Sadaqaat",
    nameFr: "Faza'il E Sadaqaat",
    namePt: "Faza'il E Sadaqaat",
    nameTr: "Faza'il E Sadaqaat",
    nameIt: "Faza'il E Sadaqaat",
    nameNl: "Faza'il E Sadaqaat",
    nameRu: "Фазайл Э Садакат",
    nameFil: "Faza'il E Sadaqaat",
    nameTh: "ฟะซาอิล-อี-ศาดากาต",
    nameId: "Faza'il E Sadaqaat",
    nameJa: "ファザイル・エ・サダカート",
    nameKo: "파자일-이-사다카트",
    namePl: "Faza'il E Sadaqaat",
    nameVi: "Faza'il E Sadaqaat",
    nameZh: "施舍的优点",
    code: "(by Shaikh Zakariyya Kandhalwi)",
    id: "fazail-e-sadaqaat",
  },
];

export const languagesList = [
  { name: "Arabic", code: "ar" },
  { name: "Bengali", code: "bn" },
  { name: "English", code: "en" },
  { name: "Urdu", code: "ur" },
  { name: "Hindi", code: "hi" },
  { name: "Tamil", code: "ta" },
  { name: "German", code: "de" },
  { name: "Spanish", code: "es" },
  { name: "French", code: "fr" },
  { name: "Portuguese", code: "pt" },
  { name: "Turkish", code: "tr" },
  { name: "Italian", code: "it" },
  { name: "Dutch", code: "nl" },
  { name: "Russian", code: "ru" },
  { name: "Filipino", code: "tl" },
  { name: "Thai", code: "th" },
  { name: "Indonesian", code: "id" },
  { name: "Japanese", code: "ja" },
  { name: "Korean", code: "ko" },
  { name: "Polish", code: "pl" },
  { name: "Vietnamese", code: "vi" },
  { name: "Mandarin Chinese", code: "zh" },
];
