const mongoose = require("mongoose");

// surahData model
const surahDataSchema = new mongoose.Schema({
  surahName: String,
  surahNumber: Number,
  juzNumber: [Number],
  totalAyah: {
    type: Number,
  },
});

const SurahData = mongoose.model("Surah-Data", surahDataSchema);

const surahData = [
  {
    surahName: {
      ar: "سورة الفاتحة",
      bn: "সুরা আল-ফাতিহা",
      en: "Surah Al-Fatiha",
      hi: "सुरा अल-फातिहा",
      pt: "Surah Al-Fatiha",
      de: "Surah Al-Fatiha",
      fr: "Sourate Al-Fatiha",
      es: "Sura Al-Fatiha",
      tr: "Sure Al-Fatiha",
      it: "Sura Al-Fatiha",
      nl: "Soera Al-Fatiha",
      ru: "Сура Аль-Фатиха",
      tl: "Surah Al-Fatiha",
      th: "ซูรอาห์ อัลฟาติหะ",
      id: "Surah Al-Fatiha",
      ja: "スーラ アルファティハ",
      ko: "수라 알파티하",
      pl: "Surah Al-Fatiha",
      vi: "Surah Al-Fatiha",
      ta: "சூரா அல்-படிஹா",
      ur: "سورۃ الفاتحہ",
      zh: "苏拉·法蒂哈",
    },
    surahNumber: 1,
    juzNumber: [1],
    totalAyah: 7,
  },
  {
    surahName: {
      ar: "سورة البقرة",
      bn: "সুরা আল-বাকারা",
      en: "Surah Al-Baqarah",
      hi: "सुरा अल-बक़रा",
      pt: "Surah Al-Baqarah",
      de: "Surah Al-Baqarah",
      fr: "Sourate Al-Baqarah",
      es: "Sura Al-Baqarah",
      tr: "Sure Al-Baqarah",
      it: "Sura Al-Baqarah",
      nl: "Soera Al-Baqarah",
      ru: "Сура Аль-Бакара",
      tl: "Surah Al-Baqarah",
      th: "ซูรอาห์ อัลบากะระ",
      id: "Surah Al-Baqarah",
      ja: "スーラ アルバカラ",
      ko: "수라 알바카라",
      pl: "Surah Al-Baqarah",
      vi: "Surah Al-Baqarah",
      ta: "சூரா அல்-பக்கரா",
      ur: "سورۃ البقرہ",
      zh: "苏拉·巴卡拉",
    },
    surahNumber: 2,
    juzNumber: [1, 2, 3],
    totalAyah: 286,
  },
  {
    surahName: {
      ar: "سورة آل عمران",
      bn: "সুরা আল-ইমরান",
      en: "Surah Al-Imran",
      hi: "सुरा आल-इमरान",
      pt: "Surah Al-Imran",
      de: "Surah Al-Imran",
      fr: "Sourate Al-Imran",
      es: "Sura Al-Imran",
      tr: "Sure Al-Imran",
      it: "Sura Al-Imran",
      nl: "Soera Al-Imran",
      ru: "Сура Аль-Имран",
      tl: "Surah Al-Imran",
      th: "ซูรอาห์ อัลอิมราน",
      id: "Surah Al-Imran",
      ja: "スーラ アール・イムラーン",
      ko: "수라 알임란",
      pl: "Surah Al-Imran",
      vi: "Surah Al-Imran",
      ta: "சூரா அல்-இம்ரான்",
      ur: "سورۃ آل عمران",
      zh: "苏拉·阿尔-伊姆兰",
    },
    surahNumber: 3,
    juzNumber: [3, 4],
    totalAyah: 200,
  },
  {
    surahName: {
      ar: "سورة النساء",
      bn: "সুরা আন-নিসা",
      en: "Surah An-Nisa",
      hi: "सुरा अन-निसा",
      pt: "Surah An-Nisa",
      de: "Surah An-Nisa",
      fr: "Sourate An-Nisa",
      es: "Sura An-Nisa",
      tr: "Sure An-Nisa",
      it: "Sura An-Nisa",
      nl: "Soera An-Nisa",
      ru: "Сура Ан-Ниса",
      tl: "Surah An-Nisa",
      th: "ซูรอาห์ อัลนิสา",
      id: "Surah An-Nisa",
      ja: "スーラ アンニサ",
      ko: "수라 안니사",
      pl: "Surah An-Nisa",
      vi: "Surah An-Nisa",
      ta: "சூரா அன்-நிசா",
      ur: "سورۃ النساء",
      zh: "苏拉·安-尼萨",
    },
    surahNumber: 4,
    juzNumber: [4, 5, 6],
    totalAyah: 176,
  },
  {
    surahName: {
      ar: "سورة المائدة",
      bn: "সুরা আল-মায়িদাহ",
      en: "Surah Al-Ma'idah",
      hi: "सुरा अल-माइदाह",
      pt: "Surah Al-Ma'idah",
      de: "Surah Al-Ma'idah",
      fr: "Sourate Al-Ma'idah",
      es: "Sura Al-Ma'idah",
      tr: "Sure Al-Ma'idah",
      it: "Sura Al-Ma'idah",
      nl: "Soera Al-Ma'idah",
      ru: "Сура Аль-Маида",
      tl: "Surah Al-Ma'idah",
      th: "ซูรอาห์ อัลมะอิดะห์",
      id: "Surah Al-Ma'idah",
      ja: "スーラ アルマイダ",
      ko: "수라 알마이다",
      pl: "Surah Al-Ma'idah",
      vi: "Surah Al-Ma'idah",
      ta: "சூரா அல்-மாயிதா",
      ur: "سورۃ المائدہ",
      zh: "苏拉·麦地哈",
    },
    surahNumber: 5,
    juzNumber: [6, 7],
    totalAyah: 120,
  },
  {
    surahName: {
      ar: "سورة الأنعام",
      bn: "সুরা আল-আন'আম",
      en: "Surah Al-An'am",
      hi: "सुरा अल-आन'आम",
      pt: "Surah Al-An'am",
      de: "Surah Al-An'am",
      fr: "Sourate Al-An'am",
      es: "Sura Al-An'am",
      tr: "Sure Al-An'am",
      it: "Sura Al-An'am",
      nl: "Soera Al-An'am",
      ru: "Сура Аль-Ан'ам",
      tl: "Surah Al-An'am",
      th: "ซูรอาห์ อัลอานอาม",
      id: "Surah Al-An'am",
      ja: "スーラ アルアナーム",
      ko: "수라 알안암",
      pl: "Surah Al-An'am",
      vi: "Surah Al-An'am",
      ta: "சூரா அல்-ஆனாம்",
      ur: "سورۃ الانعام",
      zh: "苏拉·阿尔-阿纳姆",
    },
    surahNumber: 6,
    juzNumber: [7, 8],
    totalAyah: 165,
  },
  {
    surahName: {
      ar: "سورة الأعراف",
      bn: "সুরা আল-আ'রাফ",
      en: "Surah Al-A'raf",
      hi: "सुरा अल-आ'राफ",
      pt: "Surah Al-A'raf",
      de: "Surah Al-A'raf",
      fr: "Sourate Al-A'raf",
      es: "Sura Al-A'raf",
      tr: "Sure Al-A'raf",
      it: "Sura Al-A'raf",
      nl: "Soera Al-A'raf",
      ru: "Сура Аль-А'раф",
      tl: "Surah Al-A'raf",
      th: "ซูรอาห์ อัลอาราฟ",
      id: "Surah Al-A'raf",
      ja: "スーラ アルアラフ",
      ko: "수라 알아랍",
      pl: "Surah Al-A'raf",
      vi: "Surah Al-A'raf",
      ta: "சூரா அல்-ஆர஫்",
      ur: "سورۃ الاعراف",
      zh: "苏拉·阿尔-阿拉夫",
    },
    surahNumber: 7,
    juzNumber: [8, 9],
    totalAyah: 206,
  },
  {
    surahName: {
      ar: "سورة الأنفال",
      bn: "সুরা আল-আনফাল",
      en: "Surah Al-Anfal",
      hi: "सुरा अल-अंफाल",
      pt: "Surah Al-Anfal",
      de: "Surah Al-Anfal",
      fr: "Sourate Al-Anfal",
      es: "Sura Al-Anfal",
      tr: "Sure Al-Anfal",
      it: "Sura Al-Anfal",
      nl: "Soera Al-Anfal",
      ru: "Сура Аль-Анфал",
      tl: "Surah Al-Anfal",
      th: "ซูรอาห์ อัลอันฟาล",
      id: "Surah Al-Anfal",
      ja: "スーラ アルアンファール",
      ko: "수라 알안팔",
      pl: "Surah Al-Anfal",
      vi: "Surah Al-Anfal",
      ta: "சூரா அல்-அன்ஃபால்",
      ur: "سورۃ الانفال",
      zh: "苏拉·阿尔-安法尔",
    },
    surahNumber: 8,
    juzNumber: [9, 10],
    totalAyah: 75,
  },
  {
    surahName: {
      ar: "سورة التوبة",
      bn: "সুরা আত-তাওবাহ",
      en: "Surah At-Tawbah",
      hi: "सुरा अत-तौबा",
      pt: "Surah At-Tawbah",
      de: "Surah At-Tawbah",
      fr: "Sourate At-Tawbah",
      es: "Sura At-Tawbah",
      tr: "Sure At-Tawbah",
      it: "Sura At-Tawbah",
      nl: "Soera At-Tawbah",
      ru: "Сура Ат-Тауба",
      tl: "Surah At-Tawbah",
      th: "ซูรอาห์ อัตเตาบะห์",
      id: "Surah At-Tawbah",
      ja: "スーラ アットタウバ",
      ko: "수라 앗타우바",
      pl: "Surah At-Tawbah",
      vi: "Surah At-Tawbah",
      ta: "சூரா அத்-தௌபா",
      ur: "سورۃ التوبة",
      zh: "苏拉·塔乌巴",
    },
    surahNumber: 9,
    juzNumber: [10, 11],
    totalAyah: 129,
  },
  {
    surahName: {
      ar: "سورة يونس",
      bn: "সুরা ইউনুস",
      en: "Surah Yunus",
      hi: "सुरा युनुस",
      pt: "Surah Yunus",
      de: "Surah Yunus",
      fr: "Sourate Yunus",
      es: "Sura Yunus",
      tr: "Sure Yunus",
      it: "Sura Yunus",
      nl: "Soera Yunus",
      ru: "Сура Юнус",
      tl: "Surah Yunus",
      th: "ซูรอาห์ ยูนุส",
      id: "Surah Yunus",
      ja: "スーラ ユヌス",
      ko: "수라 유누스",
      pl: "Surah Yunus",
      vi: "Surah Yunus",
      ta: "சூரா யூனுஸ்",
      ur: "سورۃ یونس",
      zh: "苏拉·尤努斯",
    },
    surahNumber: 10,
    juzNumber: [11],
    totalAyah: 109,
  },
  {
    surahName: {
      ar: "سورة هود",
      bn: "সুরা হুদ",
      en: "Surah Hud",
      hi: "सुरा हुद",
      pt: "Surah Hud",
      de: "Surah Hud",
      fr: "Sourate Hud",
      es: "Sura Hud",
      tr: "Sure Hud",
      it: "Sura Hud",
      nl: "Soera Hud",
      ru: "Сура Худ",
      tl: "Surah Hud",
      th: "ซูรอาห์ ฮุด",
      id: "Surah Hud",
      ja: "スーラ フッド",
      ko: "수라 후드",
      pl: "Surah Hud",
      vi: "Surah Hud",
      ta: "சூரா ஹூத்",
      ur: "سورۃ ہود",
      zh: "苏拉·胡德",
    },
    surahNumber: 11,
    juzNumber: [11, 12],
    totalAyah: 123,
  },
  {
    surahName: {
      ar: "سورة يوسف",
      bn: "সুরা ইউসুফ",
      en: "Surah Yusuf",
      hi: "सुरा यूसुफ",
      pt: "Surah Yusuf",
      de: "Surah Yusuf",
      fr: "Sourate Yusuf",
      es: "Sura Yusuf",
      tr: "Sure Yusuf",
      it: "Sura Yusuf",
      nl: "Soera Yusuf",
      ru: "Сура Юсуф",
      tl: "Surah Yusuf",
      th: "ซูรอาห์ ยูซุฟ",
      id: "Surah Yusuf",
      ja: "スーラ ユースフ",
      ko: "수라 유수프",
      pl: "Surah Yusuf",
      vi: "Surah Yusuf",
      ta: "சூரா யூசுப்",
      ur: "سورۃ یوسف",
      zh: "苏拉·尤素福",
    },
    surahNumber: 12,
    juzNumber: [12, 13],
    totalAyah: 111,
  },
  {
    surahName: {
      ar: "سورة الرعد",
      bn: "সুরা আর-রাদ",
      en: "Surah Ar-Rad",
      hi: "सुरा अर-रद",
      pt: "Surah Ar-Rad",
      de: "Surah Ar-Rad",
      fr: "Sourate Ar-Rad",
      es: "Sura Ar-Rad",
      tr: "Sure Ar-Rad",
      it: "Sura Ar-Rad",
      nl: "Soera Ar-Rad",
      ru: "Сура Ар-Рад",
      tl: "Surah Ar-Rad",
      th: "ซูรอาห์ อาร์รัด",
      id: "Surah Ar-Rad",
      ja: "スーラ アルラッド",
      ko: "수라 알라드",
      pl: "Surah Ar-Rad",
      vi: "Surah Ar-Rad",
      ta: "சூரா அர்-ரத்",
      ur: "سورۃ الرعد",
      zh: "苏拉·阿尔拉德",
    },
    surahNumber: 13,
    juzNumber: [13],
    totalAyah: 43,
  },
  {
    surahName: {
      ar: "سورة إبراهيم",
      bn: "সুরা ইব্রাহীম",
      en: "Surah Ibrahim",
      hi: "सुरा इब्राहीम",
      pt: "Surah Ibrahim",
      de: "Surah Ibrahim",
      fr: "Sourate Ibrahim",
      es: "Sura Ibrahim",
      tr: "Sure Ibrahim",
      it: "Sura Ibrahim",
      nl: "Soera Ibrahim",
      ru: "Сура Ибрахим",
      tl: "Surah Ibrahim",
      th: "ซูรอาห์ ইব্রাহীম",
      id: "Surah Ibrahim",
      ja: "スーラ イブラヒム",
      ko: "수라 이브라힘",
      pl: "Surah Ibrahim",
      vi: "Surah Ibrahim",
      ta: "சூரா இப்ராஹீம்",
      ur: "سورۃ ابراہیم",
      zh: "苏拉·易卜拉欣",
    },
    surahNumber: 14,
    juzNumber: [13],
    totalAyah: 52,
  },
  {
    surahName: {
      ar: "سورة الحجر",
      bn: "সুরা আল-হিজর",
      en: "Surah Al-Hijr",
      hi: "सुरा अल-हिज्र",
      pt: "Surah Al-Hijr",
      de: "Surah Al-Hijr",
      fr: "Sourate Al-Hijr",
      es: "Sura Al-Hijr",
      tr: "Sure Al-Hijr",
      it: "Sura Al-Hijr",
      nl: "Soera Al-Hijr",
      ru: "Сура Аль-Хиджр",
      tl: "Surah Al-Hijr",
      th: "ซูรอาห์ อัลฮิจร์",
      id: "Surah Al-Hijr",
      ja: "スーラ アルヒジュル",
      ko: "수라 알히르",
      pl: "Surah Al-Hijr",
      vi: "Surah Al-Hijr",
      ta: "சூரா அல்-ஹிஜ்ர்",
      ur: "سورۃ الحجر",
      zh: "苏拉·胡哲尔",
    },
    surahNumber: 15,
    juzNumber: [14],
    totalAyah: 99,
  },
  {
    surahName: {
      ar: "سورة النحل",
      bn: "সুরা আন-নাহল",
      en: "Surah An-Nahl",
      hi: "सुरा अन-नहल",
      pt: "Surah An-Nahl",
      de: "Surah An-Nahl",
      fr: "Sourate An-Nahl",
      es: "Sura An-Nahl",
      tr: "Sure An-Nahl",
      it: "Sura An-Nahl",
      nl: "Soera An-Nahl",
      ru: "Сура Ан-Нахль",
      tl: "Surah An-Nahl",
      th: "ซูรอาห์ อัลนาห์ล",
      id: "Surah An-Nahl",
      ja: "スーラ アンナール",
      ko: "수라 안날",
      pl: "Surah An-Nahl",
      vi: "Surah An-Nahl",
      ta: "சூரா அன்-நஹ்ல்",
      ur: "سورۃ النحل",
      zh: "苏拉·纳赫勒",
    },
    surahNumber: 16,
    juzNumber: [14],
    totalAyah: 128,
  },
  {
    surahName: {
      ar: "سورة الإسراء",
      bn: "সুরা আল-ইসরা",
      en: "Surah Al-Isra",
      hi: "सुरा अल-इसरा",
      pt: "Surah Al-Isra",
      de: "Surah Al-Isra",
      fr: "Sourate Al-Isra",
      es: "Sura Al-Isra",
      tr: "Sure Al-Isra",
      it: "Sura Al-Isra",
      nl: "Soera Al-Isra",
      ru: "Сура Аль-Исра",
      tl: "Surah Al-Isra",
      th: "ซูรอาห์ อัลอิสรา",
      id: "Surah Al-Isra",
      ja: "スーラ アルイスラ",
      ko: "수라 알이스라",
      pl: "Surah Al-Isra",
      vi: "Surah Al-Isra",
      ta: "சூரா அல-இஸ்ரா",
      ur: "سورۃ الإسراء",
      zh: "苏拉·以色列",
    },
    surahNumber: 17,
    juzNumber: [15],
    totalAyah: 111,
  },
  {
    surahName: {
      ar: "سورة الكهف",
      bn: "সুরা আল-কাহফ",
      en: "Surah Al-Kahf",
      hi: "सुरा अल-कहफ",
      pt: "Surah Al-Kahf",
      de: "Surah Al-Kahf",
      fr: "Sourate Al-Kahf",
      es: "Sura Al-Kahf",
      tr: "Sure Al-Kahf",
      it: "Sura Al-Kahf",
      nl: "Soera Al-Kahf",
      ru: "Сура Аль-Кахф",
      tl: "Surah Al-Kahf",
      th: "ซูรอาห์ อัลคัฟ",
      id: "Surah Al-Kahf",
      ja: "スーラ アルカフ",
      ko: "수라 알카프",
      pl: "Surah Al-Kahf",
      vi: "Surah Al-Kahf",
      ta: "சூரா அல்-காஃப்",
      ur: "سورۃ الکہف",
      zh: "苏拉·凯夫",
    },
    surahNumber: 18,
    juzNumber: [15, 16],
    totalAyah: 110,
  },
  {
    surahName: {
      ar: "سورة مريم",
      bn: "সুরা মারইয়াম",
      en: "Surah Maryam",
      hi: "सुरा मरियम",
      pt: "Surah Maryam",
      de: "Surah Maryam",
      fr: "Sourate Maryam",
      es: "Sura Maryam",
      tr: "Sure Maryam",
      it: "Sura Maryam",
      nl: "Soera Maryam",
      ru: "Сура Мариам",
      tl: "Surah Maryam",
      th: "ซูรอาห์ มารียัม",
      id: "Surah Maryam",
      ja: "スーラ マリアム",
      ko: "수라 마리암",
      pl: "Surah Maryam",
      vi: "Surah Maryam",
      ta: "சூரா மரியாம்",
      ur: "سورۃ مریم",
      zh: "苏拉·玛丽亚姆",
    },
    surahNumber: 19,
    juzNumber: [16],
    totalAyah: 98,
  },
  {
    surahName: {
      ar: "سورة طه",
      bn: "সুরা তা-হা",
      en: "Surah Ta-Ha",
      hi: "सुरा ता-हा",
      pt: "Surah Ta-Ha",
      de: "Surah Ta-Ha",
      fr: "Sourate Ta-Ha",
      es: "Sura Ta-Ha",
      tr: "Sure Ta-Ha",
      it: "Sura Ta-Ha",
      nl: "Soera Ta-Ha",
      ru: "Сура Та-Ха",
      tl: "Surah Ta-Ha",
      th: "ซูรอาห์ ทา-ฮา",
      id: "Surah Ta-Ha",
      ja: "スーラ ター・ハ",
      ko: "수라 타-하",
      pl: "Surah Ta-Ha",
      vi: "Surah Ta-Ha",
      ta: "சூரா தா-ஹா",
      ur: "سورۃ طہ",
      zh: "苏拉·塔哈",
    },
    surahNumber: 20,
    juzNumber: [16],
    totalAyah: 135,
  },
  {
    surahName: {
      ar: "سورة الأنبياء",
      bn: "সুরা আল-আম্বিয়া",
      en: "Surah Al-Anbiya",
      hi: "सुरा अल-अंबिया",
      pt: "Surah Al-Anbiya",
      de: "Surah Al-Anbiya",
      fr: "Sourate Al-Anbiya",
      es: "Sura Al-Anbiya",
      tr: "Sure Al-Anbiya",
      it: "Sura Al-Anbiya",
      nl: "Soera Al-Anbiya",
      ru: "Сура Аль-Анбия",
      tl: "Surah Al-Anbiya",
      th: "ซูรอาห์ อัลอัมบิยา",
      id: "Surah Al-Anbiya",
      ja: "スーラ アルアンビヤ",
      ko: "수라 알암비야",
      pl: "Surah Al-Anbiya",
      vi: "Surah Al-Anbiya",
      ta: "சூரா அல்-அம்பியா",
      ur: "سورۃ الانبیاء",
      zh: "苏拉·安比亚",
    },
    surahNumber: 21,
    juzNumber: [17],
    totalAyah: 112,
  },
  {
    surahName: {
      ar: "سورة الحج",
      bn: "সুরা আল-হজ্জ",
      en: "Surah Al-Hajj",
      hi: "सुरा अल-हज",
      pt: "Surah Al-Hajj",
      de: "Surah Al-Hajj",
      fr: "Sourate Al-Hajj",
      es: "Sura Al-Hajj",
      tr: "Sure Al-Hajj",
      it: "Sura Al-Hajj",
      nl: "Soera Al-Hajj",
      ru: "Сура Аль-Хадж",
      tl: "Surah Al-Hajj",
      th: "ซูรอาห์ อัลฮัจญ์",
      id: "Surah Al-Hajj",
      ja: "スーラ アルハッジ",
      ko: "수라 알하지",
      pl: "Surah Al-Hajj",
      vi: "Surah Al-Hajj",
      ta: "சூரா அல்-ஹஜ்",
      ur: "سورۃ الحج",
      zh: "苏拉·哈吉",
    },
    surahNumber: 22,
    juzNumber: [17],
    totalAyah: 78,
  },
  {
    surahName: {
      ar: "سورة المؤمنون",
      bn: "সুরা আল-মুমিনুন",
      en: "Surah Al-Mu'minun",
      hi: "सुरा अल-मुमिनून",
      pt: "Surah Al-Mu'minun",
      de: "Surah Al-Mu'minun",
      fr: "Sourate Al-Mu'minun",
      es: "Sura Al-Mu'minun",
      tr: "Sure Al-Mu'minun",
      it: "Sura Al-Mu'minun",
      nl: "Soera Al-Mu'minun",
      ru: "Сура Аль-Му'минун",
      tl: "Surah Al-Mu'minun",
      th: "ซูรอาห์ อัลมุอ์มินูน",
      id: "Surah Al-Mu'minun",
      ja: "スーラ アルムミヌン",
      ko: "수라 알무민운",
      pl: "Surah Al-Mu'minun",
      vi: "Surah Al-Mu'minun",
      ta: "சூரா அல்-மூமினூன்",
      ur: "سورۃ المؤمنون",
      zh: "苏拉·穆民",
    },
    surahNumber: 23,
    juzNumber: [18],
    totalAyah: 118,
  },
  {
    surahName: {
      ar: "سورة النور",
      bn: "সুরা আন-নূর",
      en: "Surah An-Noor",
      hi: "सुरा अन-नूर",
      pt: "Surah An-Noor",
      de: "Surah An-Noor",
      fr: "Sourate An-Noor",
      es: "Sura An-Noor",
      tr: "Sure An-Noor",
      it: "Sura An-Noor",
      nl: "Soera An-Noor",
      ru: "Сура Ан-Нур",
      tl: "Surah An-Noor",
      th: "ซูรอาห์ อัลนูร์",
      id: "Surah An-Noor",
      ja: "スーラ アンヌール",
      ko: "수라 안누르",
      pl: "Surah An-Noor",
      vi: "Surah An-Noor",
      ta: "சூரா அன்-நூர்",
      ur: "سورۃ النور",
      zh: "苏拉·努尔",
    },
    surahNumber: 24,
    juzNumber: [18],
    totalAyah: 64,
  },
  {
    surahName: {
      ar: "سورة الفرقان",
      bn: "সুরা আল-ফুরকান",
      en: "Surah Al-Furqan",
      hi: "सुरा अल-फुर्कान",
      pt: "Surah Al-Furqan",
      de: "Surah Al-Furqan",
      fr: "Sourate Al-Furqan",
      es: "Sura Al-Furqan",
      tr: "Sure Al-Furqan",
      it: "Sura Al-Furqan",
      nl: "Soera Al-Furqan",
      ru: "Сура Аль-Фуркан",
      tl: "Surah Al-Furqan",
      th: "ซูรอาห์ อัลฟุรกาน",
      id: "Surah Al-Furqan",
      ja: "スーラ アルフルカン",
      ko: "수라 알푸르칸",
      pl: "Surah Al-Furqan",
      vi: "Surah Al-Furqan",
      ta: "சூரா அல்-புர்கான்",
      ur: "سورۃ الفرقان",
      zh: "苏拉·福尔干",
    },
    surahNumber: 25,
    juzNumber: [18, 19],
    totalAyah: 77,
  },
  {
    surahName: {
      ar: "سورة الشعراء",
      bn: "সুরা আশ-শুআরা",
      en: "Surah Ash-Shu'ara",
      hi: "सुरा अश-शुआरा",
      pt: "Surah Ash-Shu'ara",
      de: "Surah Ash-Shu'ara",
      fr: "Sourate Ash-Shu'ara",
      es: "Sura Ash-Shu'ara",
      tr: "Sure Ash-Shu'ara",
      it: "Sura Ash-Shu'ara",
      nl: "Soera Ash-Shu'ara",
      ru: "Сура Аш-Шуара",
      tl: "Surah Ash-Shu'ara",
      th: "ซูรอาห์ อัลชัวรา",
      id: "Surah Ash-Shu'ara",
      ja: "スーラ アシュシュアラ",
      ko: "수라 아쉬슈아라",
      pl: "Surah Ash-Shu'ara",
      vi: "Surah Ash-Shu'ara",
      ta: "சூரா அஷ்-ஷூஅரா",
      ur: "سورۃ الشعراء",
      zh: "苏拉·诗人",
    },
    surahNumber: 26,
    juzNumber: [19],
    totalAyah: 227,
  },
  {
    surahName: {
      ar: "سورة النمل",
      bn: "সুরা আন-নামল",
      en: "Surah An-Naml",
      hi: "सुरा अन-नमल",
      pt: "Surah An-Naml",
      de: "Surah An-Naml",
      fr: "Sourate An-Naml",
      es: "Sura An-Naml",
      tr: "Sure An-Naml",
      it: "Sura An-Naml",
      nl: "Soera An-Naml",
      ru: "Сура Ан-Намл",
      tl: "Surah An-Naml",
      th: "ซูรอาห์ อัลนัมล",
      id: "Surah An-Naml",
      ja: "スーラ アンナムル",
      ko: "수라 안남르",
      pl: "Surah An-Naml",
      vi: "Surah An-Naml",
      ta: "சூரா அல்-நமல்",
      ur: "سورۃ النمل",
      zh: "苏拉·蚂蚁",
    },
    surahNumber: 27,
    juzNumber: [19, 20],
    totalAyah: 93,
  },
  {
    surahName: {
      ar: "سورة القصص",
      bn: "সুরা আল-কাসাস",
      en: "Surah Al-Qasas",
      hi: "सुरा अल-क़सस",
      pt: "Surah Al-Qasas",
      de: "Surah Al-Qasas",
      fr: "Sourate Al-Qasas",
      es: "Sura Al-Qasas",
      tr: "Sure Al-Qasas",
      it: "Sura Al-Qasas",
      nl: "Soera Al-Qasas",
      ru: "Сура Аль-Касас",
      tl: "Surah Al-Qasas",
      th: "ซูรอาห์ อัลกาซัส",
      id: "Surah Al-Qasas",
      ja: "スーラ アルカサス",
      ko: "수라 알카사스",
      pl: "Surah Al-Qasas",
      vi: "Surah Al-Qasas",
      ta: "சூரா அல்-கஸஸ்",
      ur: "سورۃ القصص",
      zh: "苏拉·故事",
    },
    surahNumber: 28,
    juzNumber: [20],
    totalAyah: 88,
  },
  {
    surahName: {
      ar: "سورة العنكبوت",
      bn: "সুরা আল-আনকাবুত",
      en: "Surah Al-'Ankabut",
      hi: "सुरा अल-आंन्काबूत",
      pt: "Surah Al-'Ankabut",
      de: "Surah Al-'Ankabut",
      fr: "Sourate Al-'Ankabut",
      es: "Sura Al-'Ankabut",
      tr: "Sure Al-'Ankabut",
      it: "Sura Al-'Ankabut",
      nl: "Soera Al-'Ankabut",
      ru: "Сура Аль-Анкабут",
      tl: "Surah Al-'Ankabut",
      th: "ซูรอาห์ อัลอังคาบุต",
      id: "Surah Al-'Ankabut",
      ja: "スーラ アルアンカブート",
      ko: "수라 알앙카부트",
      pl: "Surah Al-'Ankabut",
      vi: "Surah Al-'Ankabut",
      ta: "சூரா அல்-அங்காபூத்",
      ur: "سورۃ العنكبوت",
      zh: "苏拉·安卡布特",
    },
    surahNumber: 29,
    juzNumber: [20, 21],
    totalAyah: 69,
  },
  {
    surahName: {
      ar: "سورة الروم",
      bn: "সুরা আর-রূম",
      en: "Surah Ar-Rum",
      hi: "सुरा अर-रूम",
      pt: "Surah Ar-Rum",
      de: "Surah Ar-Rum",
      fr: "Sourate Ar-Rum",
      es: "Sura Ar-Rum",
      tr: "Sure Ar-Rum",
      it: "Sura Ar-Rum",
      nl: "Soera Ar-Rum",
      ru: "Сура Ар-Рум",
      tl: "Surah Ar-Rum",
      th: "ซูรอาห์ อาร์รูม",
      id: "Surah Ar-Rum",
      ja: "スーラ アルルーム",
      ko: "수라 알룸",
      pl: "Surah Ar-Rum",
      vi: "Surah Ar-Rum",
      ta: "சூரா அர்-ரூம்",
      ur: "سورۃ الروم",
      zh: "苏拉·罗马",
    },
    surahNumber: 30,
    juzNumber: [21],
    totalAyah: 60,
  },
  {
    surahName: "Surah Luqman",
    surahNumber: 31,
    juzNumber: [21],
    totalAyah: 34,
  },
  {
    surahName: "Surah As-Sajdah",
    surahNumber: 32,
    juzNumber: [21],
    totalAyah: 30,
  },
  {
    surahName: "Surah Al-Ahzab",
    surahNumber: 33,
    juzNumber: [21, 22],
    totalAyah: 73,
  },
  {
    surahName: "Surah Saba",
    surahNumber: 34,
    juzNumber: [22],
    totalAyah: 54,
  },
  {
    surahName: "Surah Fatir",
    surahNumber: 35,
    juzNumber: [22],
    totalAyah: 45,
  },
  {
    surahName: "Surah Ya-Seen",
    surahNumber: 36,
    juzNumber: [22, 23],
    totalAyah: 83,
  },
  {
    surahName: "Surah As-Saffat",
    surahNumber: 37,
    juzNumber: [23],
    totalAyah: 182,
  },
  {
    surahName: "Surah Sad",
    surahNumber: 38,
    juzNumber: [23],
    totalAyah: 88,
  },
  {
    surahName: "Surah Az-Zumar",
    surahNumber: 39,
    juzNumber: [23],
    totalAyah: 75,
  },
  {
    surahName: "Surah Ghafir",
    surahNumber: 40,
    juzNumber: [24],
    totalAyah: 85,
  },
  {
    surahName: "Surah Fussilat",
    surahNumber: 41,
    juzNumber: [24, 25],
    totalAyah: 54,
  },
  {
    surahName: "Surah Ash-Shuraa",
    surahNumber: 42,
    juzNumber: [25],
    totalAyah: 53,
  },
  {
    surahName: "Surah Az-Zukhruf",
    surahNumber: 43,
    juzNumber: [25],
    totalAyah: 89,
  },
  {
    surahName: "Surah Ad-Dukhan",
    surahNumber: 44,
    juzNumber: [25],
    totalAyah: 59,
  },
  {
    surahName: "Surah Al-Jathiyah",
    surahNumber: 45,
    juzNumber: [25],
    totalAyah: 37,
  },
  {
    surahName: "Surah Al-Ahqaf",
    surahNumber: 46,
    juzNumber: [26],
    totalAyah: 35,
  },
  {
    surahName: "Surah Muhammad",
    surahNumber: 47,
    juzNumber: [26],
    totalAyah: 38,
  },
  {
    surahName: "Surah Al-Fath",
    surahNumber: 48,
    juzNumber: [26],
    totalAyah: 29,
  },
  {
    surahName: "Surah Al-Hujurat",
    surahNumber: 49,
    juzNumber: [26],
    totalAyah: 18,
  },
  {
    surahName: "Surah Qaf",
    surahNumber: 50,
    juzNumber: [26],
    totalAyah: 45,
  },
  {
    surahName: "Surah Adh-Dhariyat",
    surahNumber: 51,
    juzNumber: [26],
    totalAyah: 60,
  },
  {
    surahName: "Surah At-Tur",
    surahNumber: 52,
    juzNumber: [27],
    totalAyah: 49,
  },
  {
    surahName: "Surah An-Najm",
    surahNumber: 53,
    juzNumber: [27],
    totalAyah: 62,
  },
  {
    surahName: "Surah Al-Qamar",
    surahNumber: 54,
    juzNumber: [27],
    totalAyah: 55,
  },
  {
    surahName: "Surah Ar-Rahman",
    surahNumber: 55,
    juzNumber: [27],
    totalAyah: 78,
  },
  {
    surahName: "Surah Al-Waqi'ah",
    surahNumber: 56,
    juzNumber: [27],
    totalAyah: 96,
  },
  {
    surahName: "Surah Al-Hadid",
    surahNumber: 57,
    juzNumber: [27],
    totalAyah: 29,
  },
  {
    surahName: "Surah Al-Mujadilah",
    surahNumber: 58,
    juzNumber: [28],
    totalAyah: 22,
  },
  {
    surahName: "Surah Al-Hashr",
    surahNumber: 59,
    juzNumber: [28],
    totalAyah: 24,
  },
  {
    surahName: "Surah Al-Mumtahanah",
    surahNumber: 60,
    juzNumber: [28],
    totalAyah: 13,
  },
  {
    surahName: "Surah As-Saf",
    surahNumber: 61,
    juzNumber: [28],
    totalAyah: 14,
  },
  {
    surahName: "Surah Al-Jumu'ah",
    surahNumber: 62,
    juzNumber: [28],
    totalAyah: 11,
  },
  {
    surahName: "Surah Al-Munafiqun",
    surahNumber: 63,
    juzNumber: [28],
    totalAyah: 11,
  },
  {
    surahName: "Surah At-Taghabun",
    surahNumber: 64,
    juzNumber: [28],
    totalAyah: 18,
  },
  {
    surahName: "Surah At-Talaq",
    surahNumber: 65,
    juzNumber: [28],
    totalAyah: 12,
  },
  {
    surahName: "Surah At-Tahrim",
    surahNumber: 66,
    juzNumber: [28],
    totalAyah: 12,
  },
  {
    surahName: "Surah Al-Mulk",
    surahNumber: 67,
    juzNumber: [29],
    totalAyah: 30,
  },
  {
    surahName: "Surah Al-Qalam",
    surahNumber: 68,
    juzNumber: [29],
    totalAyah: 52,
  },
  {
    surahName: "Surah Al-Haqqah",
    surahNumber: 69,
    juzNumber: [29],
    totalAyah: 52,
  },
  {
    surahName: "Surah Al-Ma'arij",
    surahNumber: 70,
    juzNumber: [29],
    totalAyah: 44,
  },
  {
    surahName: "Surah Nuh",
    surahNumber: 71,
    juzNumber: [29],
    totalAyah: 28,
  },
  {
    surahName: "Surah Al-Jinn",
    surahNumber: 72,
    juzNumber: [29],
    totalAyah: 28,
  },
  {
    surahName: "Surah Al-Muzzammil",
    surahNumber: 73,
    juzNumber: [29],
    totalAyah: 20,
  },
  {
    surahName: "Surah Al-Muddaththir",
    surahNumber: 74,
    juzNumber: [29],
    totalAyah: 56,
  },
  {
    surahName: "Surah Al-Qiyamah",
    surahNumber: 75,
    juzNumber: [29],
    totalAyah: 40,
  },
  {
    surahName: "Surah Al-Insan",
    surahNumber: 76,
    juzNumber: [29],
    totalAyah: 31,
  },
  {
    surahName: "Surah Al-Mursalat",
    surahNumber: 77,
    juzNumber: [29],
    totalAyah: 50,
  },
  {
    surahName: "Surah An-Naba",
    surahNumber: 78,
    juzNumber: [30],
    totalAyah: 40,
  },
  {
    surahName: "Surah An-Nazi'at",
    surahNumber: 79,
    juzNumber: [30],
    totalAyah: 45,
  },
  {
    surahName: "Surah 'Abasa",
    surahNumber: 80,
    juzNumber: [30],
    totalAyah: 42,
  },
  {
    surahName: "Surah At-Takwir",
    surahNumber: 81,
    juzNumber: [30],
    totalAyah: 29,
  },
  {
    surahName: "Surah Al-Infitar",
    surahNumber: 82,
    juzNumber: [30],
    totalAyah: 19,
  },
  {
    surahName: "Surah Al-Mutaffifin",
    surahNumber: 83,
    juzNumber: [30],
    totalAyah: 36,
  },
  {
    surahName: "Surah Al-Inshiqaq",
    surahNumber: 84,
    juzNumber: [30],
    totalAyah: 25,
  },
  {
    surahName: "Surah Al-Buruj",
    surahNumber: 85,
    juzNumber: [30],
    totalAyah: 22,
  },
  {
    surahName: "Surah At-Tariq",
    surahNumber: 86,
    juzNumber: [30],
    totalAyah: 17,
  },
  {
    surahName: "Surah Al-A'la",
    surahNumber: 87,
    juzNumber: [30],
    totalAyah: 19,
  },
  {
    surahName: "Surah Al-Ghashiyah",
    surahNumber: 88,
    juzNumber: [30],
    totalAyah: 26,
  },
  {
    surahName: "Surah Al-Fajr",
    surahNumber: 89,
    juzNumber: [30],
    totalAyah: 30,
  },
  {
    surahName: "Surah Al-Balad",
    surahNumber: 90,
    juzNumber: [30],
    totalAyah: 20,
  },
  {
    surahName: "Surah Ash-Shams",
    surahNumber: 91,
    juzNumber: [30],
    totalAyah: 15,
  },
  {
    surahName: "Surah Al-Layl",
    surahNumber: 92,
    juzNumber: [30],
    totalAyah: 21,
  },
  {
    surahName: "Surah Ad-Duhaa",
    surahNumber: 93,
    juzNumber: [30],
    totalAyah: 11,
  },
  {
    surahName: "Surah Al-Inshirah",
    surahNumber: 94,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: "Surah At-Tin",
    surahNumber: 95,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: "Surah Al-'Alaq",
    surahNumber: 96,
    juzNumber: [30],
    totalAyah: 19,
  },
  {
    surahName: "Surah Al-Qadr",
    surahNumber: 97,
    juzNumber: [30],
    totalAyah: 5,
  },
  {
    surahName: "Surah Al-Bayyinah",
    surahNumber: 98,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: "Surah Az-Zalzalah",
    surahNumber: 99,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: "Surah Al-'Adiyat",
    surahNumber: 100,
    juzNumber: [30],
    totalAyah: 11,
  },
  {
    surahName: "Surah Al-Qari'ah",
    surahNumber: 101,
    juzNumber: [30],
    totalAyah: 11,
  },
  {
    surahName: "Surah At-Takathur",
    surahNumber: 102,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: "Surah Al-'Asr",
    surahNumber: 103,
    juzNumber: [30],
    totalAyah: 3,
  },
  {
    surahName: "Surah Al-Humazah",
    surahNumber: 104,
    juzNumber: [30],
    totalAyah: 9,
  },
  {
    surahName: "Surah Al-Fil",
    surahNumber: 105,
    juzNumber: [30],
    totalAyah: 5,
  },
  {
    surahName: "Surah Quraish",
    surahNumber: 106,
    juzNumber: [30],
    totalAyah: 4,
  },
  {
    surahName: "Surah Al-Ma'un",
    surahNumber: 107,
    juzNumber: [30],
    totalAyah: 7,
  },
  {
    surahName: "Surah Al-Kauthar",
    surahNumber: 108,
    juzNumber: [30],
    totalAyah: 3,
  },
  {
    surahName: "Surah Al-Kafirun",
    surahNumber: 109,
    juzNumber: [30],
    totalAyah: 6,
  },
  {
    surahName: "Surah An-Nasr",
    surahNumber: 110,
    juzNumber: [30],
    totalAyah: 3,
  },
  {
    surahName: "Surah Al-Masad",
    surahNumber: 111,
    juzNumber: [30],
    totalAyah: 5,
  },
  {
    surahName: "Surah Al-Ikhlas",
    surahNumber: 112,
    juzNumber: [30],
    totalAyah: 4,
  },
  {
    surahName: "Surah Al-Falaq",
    surahNumber: 113,
    juzNumber: [30],
    totalAyah: 5,
  },
  {
    surahName: "Surah An-Nas",
    surahNumber: 114,
    juzNumber: [30],
    totalAyah: 6,
  },
];

// MongoDB connection string
// const mongoURI =
//   "mongodb+srv://mahbub:mahbub@theislamicdb.2g6v7.mongodb.net/theislamicdb?retryWrites=true&w=majority&appName=theislamicdb";

// Connect to MongoDB
// mongoose
//   .connect(mongoURI, {
//     useNewUrlParser: true,
//     useUnifiedTopology: true,
//   })
//   .then(() => {
//     console.log("MongoDB connected successfully!");
//     // Insert languages into database
//     insertLanguages();
//   })
//   .catch((err) => {
//     console.error("MongoDB connection error:", err);
//   });

// insert languages into database
const insertLanguages = async () => {
  try {
    for (const surah of surahData) {
      await SurahData.updateOne(
        { surahName: surah.surahName },
        { $setOnInsert: surah },
        { upsert: true }
      );
    }
    console.log("SurahData inserted/updated successfully!");
  } catch (error) {
    console.error("Error inserting surahs:", error);
  } finally {
    mongoose.connection.close();
  }
};

module.exports = SurahData;
