export const booksList = [
  {
    nameEn: "Sahih Al-Bukhari",
    nameBn: "সহীহ আল-বুখারী",
    nameAr: "صحيح البخاري",
    nameHi: "सहीह आल-बुखारी",
    nameUr: "صحیح البخاری",
    nameTa: "சஹீஹ் அல்-புகாரி",
    nameDe: "Sahih Al-Bukhari",
    nameEs: "Sahih Al-Bujari",
    nameFr: "Sahih Al-Bukhari",
    namePt: "Sahih Al-Bukhari",
    nameTr: "Sahih Al-Buhari",
    nameIt: "Sahih Al-Bukhari",
    nameNl: "Sahih Al-Bukhari",
    nameRu: "Сахих Аль-Бухари",
    nameFil: "Sahih Al-Bukhari",
    nameTh: "ศอฮีฮ์ อัล-บุคอรี",
    nameId: "Shahih Al-Bukhari",
    nameJa: "サヒーフ・アル＝ブハーリー",
    nameKo: "사히 알 부카리",
    namePl: "Sahih Al-Bukhari",
    nameVi: "Sahih Al-Bukhari",
    nameZh: "圣训布哈里集",
    code: "(d. 256 AH) C",
    id: "bukhari",
  },
  {
    nameEn: "Sahih Muslim",
    nameBn: "সহীহ মুসলিম",
    nameAr: "صحيح مسلم",
    nameHi: "सहीह मुस्लिम",
    nameUr: "صحیح مسلم",
    nameTa: "சஹீஹ் முஸ்லிம்",
    nameDe: "Sahih Muslim",
    nameEs: "Sahih Muslim",
    nameFr: "Sahih Muslim",
    namePt: "Sahih Muslim",
    nameTr: "Sahih Müslim",
    nameIt: "Sahih Muslim",
    nameNl: "Sahih Muslim",
    nameRu: "Сахих Муслим",
    nameFil: "Sahih Muslim",
    nameTh: "ศอฮีฮ์ มุสลิม",
    nameId: "Shahih Muslim",
    nameJa: "サヒーフ・ムスリム",
    nameKo: "사히 무슬림",
    namePl: "Sahih Muslim",
    nameVi: "Sahih Muslim",
    nameZh: "圣训穆斯林集",
    code: "(d. 261 AH) C",
    id: "muslim",
  },
  {
    nameEn: "Sunan Ibn Mājah",
    nameBn: "সুনান ইবনে মাজাহ",
    nameAr: "سنن ابن ماجه",
    nameHi: "सुनन इब्न माजा",
    nameUr: "سنن ابن ماجہ",
    nameTa: "ஸுனன் இப்னு மாஜா",
    nameDe: "Sunan Ibn Majah",
    nameEs: "Sunan Ibn Majah",
    nameFr: "Sunan Ibn Majah",
    namePt: "Sunan Ibn Majah",
    nameTr: "Sünen İbn Mace",
    nameIt: "Sunan Ibn Majah",
    nameNl: "Sunan Ibn Majah",
    nameRu: "Сунан Ибн Маджа",
    nameFil: "Sunan Ibn Majah",
    nameTh: "ซุนัน อิบนุ มาญะห์",
    nameId: "Sunan Ibnu Majah",
    nameJa: "スナン・イブン・マージャ",
    nameKo: "수난 이븐 마자",
    namePl: "Sunan Ibn Majah",
    nameVi: "Sunan Ibn Majah",
    nameZh: "圣训伊本马哲集",
    code: "(d. 273 AH) C",
    id: "ibnmajah",
  },
  {
    nameEn: "Sunan Abi Dawud",
    nameBn: "সুনান আবু দাউদ",
    nameAr: "سنن أبي داود",
    nameHi: "सुनन अबू दाऊद",
    nameUr: "سنن ابوداؤد",
    nameTa: "ஸுனன் அபூ தாவுத்",
    nameDe: "Sunan Abi Dawud",
    nameEs: "Sunan Abi Dawud",
    nameFr: "Sunan Abi Dawud",
    namePt: "Sunan Abi Dawud",
    nameTr: "Sünen Ebu Davud",
    nameIt: "Sunan Abi Dawud",
    nameNl: "Sunan Abi Dawud",
    nameRu: "Сунан Абу Дауд",
    nameFil: "Sunan Abi Dawud",
    nameTh: "ซุนัน อบู ดาวูด",
    nameId: "Sunan Abu Dawud",
    nameJa: "スナン・アブー・ダーウード",
    nameKo: "수난 아부 다우드",
    namePl: "Sunan Abi Dawud",
    nameVi: "Sunan Abi Dawud",
    nameZh: "圣训艾卜达伍德集",
    code: "(d. 275 AH)",
    id: "abudawud",
  },
  {
    nameEn: "Sunan At-Tirmidhi",
    nameBn: "সুনান আত-তিরমিজি",
    nameAr: "سنن الترمذي",
    nameHi: "सुनन अत-तिर्मिज़ी",
    nameUr: "سنن الترمذی",
    nameTa: "ஸுனன் அத்-திர்மிதி",
    nameDe: "Sunan At-Tirmidhi",
    nameEs: "Sunan At-Tirmidhi",
    nameFr: "Sunan At-Tirmidhi",
    namePt: "Sunan At-Tirmidhi",
    nameTr: "Sünen Tirmizi",
    nameIt: "Sunan At-Tirmidhi",
    nameNl: "Sunan At-Tirmidhi",
    nameRu: "Сунан ат-Тирмизи",
    nameFil: "Sunan At-Tirmidhi",
    nameTh: "ซุนัน อัต-ติรมิซี",
    nameId: "Sunan At-Tirmidhi",
    nameJa: "スナン・アット・ティルミズィー",
    nameKo: "수난 앗티르미지",
    namePl: "Sunan At-Tirmidhi",
    nameVi: "Sunan At-Tirmidhi",
    nameZh: "圣训提尔密集",
    code: "(d. 279 AH)",
    id: "tirmidhi",
  },
  {
    nameEn: "Sunan An-Nasa'i",
    nameBn: "সুনান আন-নাসাঈ",
    nameAr: "سنن النسائي",
    nameHi: "सुनन अन-नसाई",
    nameUr: "سنن النسائی",
    nameTa: "ஸுனன் அன்நஸாயி",
    nameDe: "Sunan An-Nasa'i",
    nameEs: "Sunan An-Nasa'i",
    nameFr: "Sunan An-Nasa'i",
    namePt: "Sunan An-Nasa'i",
    nameTr: "Sünen Nesai",
    nameIt: "Sunan An-Nasa'i",
    nameNl: "Sunan An-Nasa'i",
    nameRu: "Сунан ан-Насаи",
    nameFil: "Sunan An-Nasa'i",
    nameTh: "ซุนัน อัน-นะสาอี",
    nameId: "Sunan An-Nasa'i",
    nameJa: "スナン・アン＝ナサーイー",
    nameKo: "수난 안 나사이",
    namePl: "Sunan An-Nasa'i",
    nameVi: "Sunan An-Nasa'i",
    nameZh: "圣训奈萨仪集",
    code: "(d. 303 AH)",
    id: "nasai",
  },
  {
    nameEn: "Muwatta Imam Malik",
    nameBn: "মুয়াত্তা ইমাম মালিক",
    nameAr: "الموطأ الإمام مالك",
    nameHi: "मुवत्ता इमाम मालिक",
    nameUr: "موطا امام مالک",
    nameTa: "முவத்தா இமாம் மாலிக்",
    nameDe: "Muwatta Imam Malik",
    nameEs: "Muwatta Imam Malik",
    nameFr: "Muwatta Imam Malik",
    namePt: "Muwatta Imam Malik",
    nameTr: "Muvatta İmam Malik",
    nameIt: "Muwatta Imam Malik",
    nameNl: "Muwatta Imam Malik",
    nameRu: "Аль-Муватта Имама Малика",
    nameFil: "Muwatta Imam Malik",
    nameTh: "มูวัตตาอิมามมาลิก",
    nameId: "Muwatta Imam Malik",
    nameJa: "ムワッター・イマーム・マーリク",
    nameKo: "무와따 이맘 말리크",
    namePl: "Muwatta Imam Malik",
    nameVi: "Muwatta Imam Malik",
    nameZh: "穆瓦塔伊玛目马立克",
    code: "(d. 179 AH)",
    id: "muwatta",
  },
  {
    nameEn: "Musnad Ahmad",
    nameBn: "মুসনাদ আহমদ",
    nameAr: "مسند أحمد",
    nameHi: "मुसनद अहमद",
    nameUr: "مسند احمد",
    nameTa: "முஸ்நாத் அகமத்",
    nameDe: "Musnad Ahmad",
    nameEs: "Musnad Ahmad",
    nameFr: "Musnad Ahmad",
    namePt: "Musnad Ahmad",
    nameTr: "Müsned Ahmed",
    nameIt: "Musnad Ahmad",
    nameNl: "Musnad Ahmad",
    nameRu: "Муснад Ахмада",
    nameFil: "Musnad Ahmad",
    nameTh: "มุสนัดอะห์หมัด",
    nameId: "Musnad Ahmad",
    nameJa: "ムスナド・アフマド",
    nameKo: "무스나드 아흐마드",
    namePl: "Musnad Ahmad",
    nameVi: "Musnad Ahmad",
    nameZh: "穆斯奈德艾哈迈德",
    code: "(d. 241 AH)",
    id: "musnad-ahmad",
  },
  {
    nameEn: "Sunan Ad-Darimi",
    nameBn: "সুনান আদ-দারিমি",
    nameAr: "سنن الدارمي",
    nameHi: "सुनन अद-दारीमी",
    nameUr: "سنن الدارمی",
    nameTa: "ஸுனன் அத்-தாரிமி",
    nameDe: "Sunan Ad-Darimi",
    nameEs: "Sunan Ad-Darimi",
    nameFr: "Sunan Ad-Darimi",
    namePt: "Sunan Ad-Darimi",
    nameTr: "Sünen Darimi",
    nameIt: "Sunan Ad-Darimi",
    nameNl: "Sunan Ad-Darimi",
    nameRu: "Сунан ад-Дарими",
    nameFil: "Sunan Ad-Darimi",
    nameTh: "ซุนัน อัด-ดารีมี",
    nameId: "Sunan Ad-Darimi",
    nameJa: "スナン・アッ＝ダーリミー",
    nameKo: "수난 아드다리미",
    namePl: "Sunan Ad-Darimi",
    nameVi: "Sunan Ad-Darimi",
    nameZh: "圣训达里米集",
    code: "(d. 255 AH)",
    id: "darimi",
  },
  {
    nameEn: "Al-Adab Al-Mufrad",
    nameBn: "আল-আদাবুল মুফরাদ",
    nameAr: "الأدب المفرد",
    nameHi: "अल-अदब अल-मुफ़रद",
    nameUr: "الادب المفرد",
    nameTa: "அல்-அதப் அல்-முஃப்ரத்",
    nameDe: "Al-Adab Al-Mufrad",
    nameEs: "Al-Adab Al-Mufrad",
    nameFr: "Al-Adab Al-Mufrad",
    namePt: "Al-Adab Al-Mufrad",
    nameTr: "El-Edebü'l-Müfred",
    nameIt: "Al-Adab Al-Mufrad",
    nameNl: "Al-Adab Al-Mufrad",
    nameRu: "Аль-Адаб Аль-Муфрад",
    nameFil: "Al-Adab Al-Mufrad",
    nameTh: "อัล-อะดับ อัล-มุฟรอด",
    nameId: "Al-Adab Al-Mufrad",
    nameJa: "アル＝アダブ・アル＝ムフラド",
    nameKo: "알아답 알무프라드",
    namePl: "Al-Adab Al-Mufrad",
    nameVi: "Al-Adab Al-Mufrad",
    nameZh: "独特礼仪",
    code: "(by Imam al-Bukhari)",
    id: "adab-mufrad",
  },
  {
    nameEn: "An-Nawawi’s Forty",
    nameBn: "আন-নাওয়ীর চল্লিশ হাদিস",
    nameAr: "أربعون حديثاً للنووي",
    nameHi: "अल-नववी की चालीस हदीस",
    nameUr: "اربعون حدیثاً للنووی",
    nameTa: "அல்-நவவியின் நாற்பது ஹதீஸ்கள்",
    nameDe: "An-Nawawi’s Forty",
    nameEs: "Las Cuarenta de An-Nawawi",
    nameFr: "Les Quarante de An-Nawawi",
    namePt: "As Quarenta de An-Nawawi",
    nameTr: "An-Nawawi’nin Kırk Hadisi",
    nameIt: "Le Quaranta di An-Nawawi",
    nameNl: "An-Nawawi’s Veertig",
    nameRu: "Сорок хадисов Ан-Навави",
    nameFil: "An-Nawawi’s Forty",
    nameTh: "ฮะดีษสี่สิบของอัล-นาวาวี",
    nameId: "An-Nawawi’s Forty",
    nameJa: "アン＝ナワウィの四十",
    nameKo: "안-나위의 사십",
    namePl: "An-Nawawi’s Forty",
    nameVi: "An-Nawawi’s Forty",
    nameZh: "纳瓦维四十条哈迪斯",
    code: "(by Imam An-Nawawi)",
    id: "nawawi-forty",
  },
  {
    nameEn: "Mishkat Al-Masabih",
    nameBn: "মিশকাত আল-মাসাবিহ",
    nameAr: "مشكات المصابيح",
    nameHi: "मिश्कत अल-मसाबिह",
    nameUr: "مشکات المصابیح",
    nameTa: "மிஷ்கத் அல்-மசாபிஹ்",
    nameDe: "Mishkat Al-Masabih",
    nameEs: "Mishkat Al-Masabih",
    nameFr: "Mishkat Al-Masabih",
    namePt: "Mishkat Al-Masabih",
    nameTr: "Mişkatü’l-Mesabih",
    nameIt: "Mishkat Al-Masabih",
    nameNl: "Mishkat Al-Masabih",
    nameRu: "Мишкат аль-Масабих",
    nameFil: "Mishkat Al-Masabih",
    nameTh: "มิสกัต อัล-มาซาบิห์",
    nameId: "Mishkat Al-Masabih",
    nameJa: "ミシュカット・アル＝マサービフ",
    nameKo: "미슈캇 알-마사비흐",
    namePl: "Mishkat Al-Masabih",
    nameVi: "Mishkat Al-Masabih",
    nameZh: "灯塔集",
    code: "(by Al-Baghawi)",
    id: "mishkat-al-masabih",
  },
  {
    nameEn: "Riyad As-Salihin",
    nameBn: "রিয়াদ আস-সালিহিন",
    nameAr: "رياض الصالحين",
    nameHi: "रियाद अस-सलिहीन",
    nameUr: "ریاض الصالحین",
    nameTa: "ரியாத் அஸ்-சாலிஹீன்",
    nameDe: "Riyad As-Salihin",
    nameEs: "Riyad As-Salihin",
    nameFr: "Riyad As-Salihin",
    namePt: "Riyad As-Salihin",
    nameTr: "Riyad-üs-Salihîn",
    nameIt: "Riyad As-Salihin",
    nameNl: "Riyad As-Salihin",
    nameRu: "Рияд ас-Салихин",
    nameFil: "Riyad As-Salihin",
    nameTh: "ริยาด อัล-ซาลิฮีน",
    nameId: "Riyad As-Salihin",
    nameJa: "リヤード・アス＝サリーヒーン",
    nameKo: "리야드 아스-살리힌",
    namePl: "Riyad As-Salihin",
    nameVi: "Riyad As-Salihin",
    nameZh: "善人之园",
    code: "(by Imam An-Nawawi)",
    id: "riyad-as-salihin",
  },
  {
    nameEn: "Bulūgh Al-Marām",
    nameBn: "বুলুগ আল-মারাম",
    nameAr: "بلوغ المرام",
    nameHi: "बुलूघ अल-मराम",
    nameUr: "بلوغ المرام",
    nameTa: "புலூக் அல்-மராம்",
    nameDe: "Bulūgh Al-Marām",
    nameEs: "Bulūgh Al-Marām",
    nameFr: "Bulūgh Al-Marām",
    namePt: "Bulūgh Al-Marām",
    nameTr: "Bulûğ el-Merâm",
    nameIt: "Bulūgh Al-Marām",
    nameNl: "Bulūgh Al-Marām",
    nameRu: "Булуг аль-Марам",
    nameFil: "Bulūgh Al-Marām",
    nameTh: "บูลูก อัล-มาราม",
    nameId: "Bulūgh Al-Marām",
    nameJa: "ブルーグ・アル＝マラム",
    nameKo: "불루그 알-마람",
    namePl: "Bulūgh Al-Marām",
    nameVi: "Bulūgh Al-Marām",
    nameZh: "通往目标",
    code: "(by Ibn Hajar al-Asqalani)",
    id: "bulugh-al-maram",
  },
  {
    nameEn: "Hisn Al-Muslim",
    nameBn: "হিসন আল-মুসলিম",
    nameAr: "حصن المسلم",
    nameHi: "हिस्न अल-मुस्लिम",
    nameUr: "حصن المسلم",
    nameTa: "ஹிஸ்ன் அல்-முஸ்லிம்",
    nameDe: "Hisn Al-Muslim",
    nameEs: "Hisn Al-Muslim",
    nameFr: "Hisn Al-Muslim",
    namePt: "Hisn Al-Muslim",
    nameTr: "Hisn-ül Muslim",
    nameIt: "Hisn Al-Muslim",
    nameNl: "Hisn Al-Muslim",
    nameRu: "Хисн аль-Муслим",
    nameFil: "Hisn Al-Muslim",
    nameTh: "หิสน อัล-มุสลิม",
    nameId: "Hisn Al-Muslim",
    nameJa: "ヒスン・アル＝ムスリム",
    nameKo: "히스눈 알-무슬림",
    namePl: "Hisn Al-Muslim",
    nameVi: "Hisn Al-Muslim",
    nameZh: "穆斯林堡垒",
    code: "(by Sa'id bin Ali al-Qahtani)",
    id: "hisn-al-muslim",
  },
  {
    nameEn: "Ash-Shama'il Al-Muhammadiyah",
    nameBn: "আশ-শামাইল আল-মুহাম্মাদিয়াহ",
    nameAr: "الشمايل المحمدية",
    nameHi: "अश-शमाइल अल-मुहम्मदीया",
    nameUr: "الشمايل المحمدية",
    nameTa: "அஷ்-ஷமாயில் அல்-முஹம்மதியாஹ",
    nameDe: "Ash-Shama'il Al-Muhammadiyah",
    nameEs: "Ash-Shama'il Al-Muhammadiyah",
    nameFr: "Ash-Shama'il Al-Muhammadiyah",
    namePt: "Ash-Shama'il Al-Muhammadiyah",
    nameTr: "Eş-Şamail el-Muhammediyye",
    nameIt: "Ash-Shama'il Al-Muhammadiyah",
    nameNl: "Ash-Shama'il Al-Muhammadiyah",
    nameRu: "Аш-Шамаиль аль-Мухаммадийя",
    nameFil: "Ash-Shama'il Al-Muhammadiyah",
    nameTh: "อัช-ชะไมล์ อัล-มูฮัมมาดียะห์",
    nameId: "Ash-Shama'il Al-Muhammadiyah",
    nameJa: "アシュ・シャマイル・アル＝ムハンマディーヤ",
    nameKo: "아쉬-샤마일 알-무함마디야",
    namePl: "Ash-Shama'il Al-Muhammadiyah",
    nameVi: "Ash-Shama'il Al-Muhammadiyah",
    nameZh: "穆罕默德的美德",
    code: "(by Imam At-Tirmidhi)",
    id: "ash-shama'il-al-muhammadiyah",
  },
  {
    nameEn: "Fazail E Amaal",
    nameBn: "ফযায়েল-ই-আমাল",
    nameAr: "فضائل الأعمال",
    nameHi: "फ़ज़ाइल-ए-आमल",
    nameUr: "فضائل الأعمال",
    nameTa: "பஜாயில்-இ-ஆமல்",
    nameDe: "Fazail E Amaal",
    nameEs: "Fazail E Amaal",
    nameFr: "Fazail E Amaal",
    namePt: "Fazail E Amaal",
    nameTr: "Fazail E Amaal",
    nameIt: "Fazail E Amaal",
    nameNl: "Fazail E Amaal",
    nameRu: "Фазайл Э Амал",
    nameFil: "Fazail E Amaal",
    nameTh: "ฟะซาอิล-อามาล",
    nameId: "Fazail E Amaal",
    nameJa: "ファザイル・エ・アマール",
    nameKo: "파자일-이-아말",
    namePl: "Fazail E Amaal",
    nameVi: "Fazail E Amaal",
    nameZh: "善行的优点",
    code: "(by Shaikh Zakariyya Kandhalwi)",
    id: "fazail-e-amal",
  },
  {
    nameEn: "Faza'il E Sadaqaat",
    nameBn: "ফযায়েল-ই-সদকাত",
    nameAr: "فضائل الصدقات",
    nameHi: "फ़ज़ाइल-ए-सदकात",
    nameUr: "فضائل الصدقات",
    nameTa: "பஜாயில்-இ-சதகாத்",
    nameDe: "Faza'il E Sadaqaat",
    nameEs: "Faza'il E Sadaqaat",
    nameFr: "Faza'il E Sadaqaat",
    namePt: "Faza'il E Sadaqaat",
    nameTr: "Faza'il E Sadaqaat",
    nameIt: "Faza'il E Sadaqaat",
    nameNl: "Faza'il E Sadaqaat",
    nameRu: "Фазайл Э Садакат",
    nameFil: "Faza'il E Sadaqaat",
    nameTh: "ฟะซาอิล-อี-ศาดากาต",
    nameId: "Faza'il E Sadaqaat",
    nameJa: "ファザイル・エ・サダカート",
    nameKo: "파자일-이-사다카트",
    namePl: "Faza'il E Sadaqaat",
    nameVi: "Faza'il E Sadaqaat",
    nameZh: "施舍的优点",
    code: "(by Shaikh Zakariyya Kandhalwi)",
    id: "fazail-e-sadaqaat",
  },
];

export const languagesList = [
  // { name: "Arabic", code: "ar" },
  { name: "Bengali", code: "bn" },
  { name: "English", code: "en" },
  { name: "Urdu", code: "ur" },
  { name: "Hindi", code: "hi" },
  { name: "Tamil", code: "ta" },
  { name: "German", code: "de" },
  { name: "Spanish", code: "es" },
  { name: "French", code: "fr" },
  { name: "Portuguese", code: "pt" },
  { name: "Turkish", code: "tr" },
  { name: "Italian", code: "it" },
  { name: "Dutch", code: "nl" },
  { name: "Russian", code: "ru" },
  { name: "Filipino", code: "tl" },
  { name: "Thai", code: "th" },
  { name: "Indonesian", code: "id" },
  { name: "Japanese", code: "ja" },
  { name: "Korean", code: "ko" },
  { name: "Polish", code: "pl" },
  { name: "Vietnamese", code: "vi" },
  { name: "Mandarin Chinese", code: "zh" },
];

export const surahNameList = [
  {
    surahName: {
      ar: "سورة الفاتحة",
      bn: "সুরা আল-ফাতিহা",
      en: "Surah Al-Fatiha",
      hi: "सुरा अल-फातिहा",
      pt: "Surah Al-Fatiha",
      de: "Surah Al-Fatiha",
      fr: "Sourate Al-Fatiha",
      es: "Sura Al-Fatiha",
      tr: "Sure Al-Fatiha",
      it: "Sura Al-Fatiha",
      nl: "Soera Al-Fatiha",
      ru: "Сура Аль-Фатиха",
      tl: "Surah Al-Fatiha",
      th: "ซูรอาห์ อัลฟาติหะ",
      id: "Surah Al-Fatiha",
      ja: "スーラ アルファティハ",
      ko: "수라 알파티하",
      pl: "Surah Al-Fatiha",
      vi: "Surah Al-Fatiha",
      ta: "சூரா அல்-படிஹா",
      ur: "سورۃ الفاتحہ",
      zh: "苏拉·法蒂哈",
    },
    surahNumber: 1,
    juzNumber: [1],
    totalAyah: 7,
  },
  {
    surahName: {
      ar: "سورة البقرة",
      bn: "সুরা আল-বাকারা",
      en: "Surah Al-Baqarah",
      hi: "सुरा अल-बक़रा",
      pt: "Surah Al-Baqarah",
      de: "Surah Al-Baqarah",
      fr: "Sourate Al-Baqarah",
      es: "Sura Al-Baqarah",
      tr: "Sure Al-Baqarah",
      it: "Sura Al-Baqarah",
      nl: "Soera Al-Baqarah",
      ru: "Сура Аль-Бакара",
      tl: "Surah Al-Baqarah",
      th: "ซูรอาห์ อัลบากะระ",
      id: "Surah Al-Baqarah",
      ja: "スーラ アルバカラ",
      ko: "수라 알바카라",
      pl: "Surah Al-Baqarah",
      vi: "Surah Al-Baqarah",
      ta: "சூரா அல்-பக்கரா",
      ur: "سورۃ البقرہ",
      zh: "苏拉·巴卡拉",
    },
    surahNumber: 2,
    juzNumber: [1, 2, 3],
    totalAyah: 286,
  },
  {
    surahName: {
      ar: "سورة آل عمران",
      bn: "সুরা আল-ইমরান",
      en: "Surah Al-Imran",
      hi: "सुरा आल-इमरान",
      pt: "Surah Al-Imran",
      de: "Surah Al-Imran",
      fr: "Sourate Al-Imran",
      es: "Sura Al-Imran",
      tr: "Sure Al-Imran",
      it: "Sura Al-Imran",
      nl: "Soera Al-Imran",
      ru: "Сура Аль-Имран",
      tl: "Surah Al-Imran",
      th: "ซูรอาห์ อัลอิมราน",
      id: "Surah Al-Imran",
      ja: "スーラ アール・イムラーン",
      ko: "수라 알임란",
      pl: "Surah Al-Imran",
      vi: "Surah Al-Imran",
      ta: "சூரா அல்-இம்ரான்",
      ur: "سورۃ آل عمران",
      zh: "苏拉·阿尔-伊姆兰",
    },
    surahNumber: 3,
    juzNumber: [3, 4],
    totalAyah: 200,
  },
  {
    surahName: {
      ar: "سورة النساء",
      bn: "সুরা আন-নিসা",
      en: "Surah An-Nisa",
      hi: "सुरा अन-निसा",
      pt: "Surah An-Nisa",
      de: "Surah An-Nisa",
      fr: "Sourate An-Nisa",
      es: "Sura An-Nisa",
      tr: "Sure An-Nisa",
      it: "Sura An-Nisa",
      nl: "Soera An-Nisa",
      ru: "Сура Ан-Ниса",
      tl: "Surah An-Nisa",
      th: "ซูรอาห์ อัลนิสา",
      id: "Surah An-Nisa",
      ja: "スーラ アンニサ",
      ko: "수라 안니사",
      pl: "Surah An-Nisa",
      vi: "Surah An-Nisa",
      ta: "சூரா அன்-நிசா",
      ur: "سورۃ النساء",
      zh: "苏拉·安-尼萨",
    },
    surahNumber: 4,
    juzNumber: [4, 5, 6],
    totalAyah: 176,
  },
  {
    surahName: {
      ar: "سورة المائدة",
      bn: "সুরা আল-মায়িদাহ",
      en: "Surah Al-Ma'idah",
      hi: "सुरा अल-माइदाह",
      pt: "Surah Al-Ma'idah",
      de: "Surah Al-Ma'idah",
      fr: "Sourate Al-Ma'idah",
      es: "Sura Al-Ma'idah",
      tr: "Sure Al-Ma'idah",
      it: "Sura Al-Ma'idah",
      nl: "Soera Al-Ma'idah",
      ru: "Сура Аль-Маида",
      tl: "Surah Al-Ma'idah",
      th: "ซูรอาห์ อัลมะอิดะห์",
      id: "Surah Al-Ma'idah",
      ja: "スーラ アルマイダ",
      ko: "수라 알마이다",
      pl: "Surah Al-Ma'idah",
      vi: "Surah Al-Ma'idah",
      ta: "சூரா அல்-மாயிதா",
      ur: "سورۃ المائدہ",
      zh: "苏拉·麦地哈",
    },
    surahNumber: 5,
    juzNumber: [6, 7],
    totalAyah: 120,
  },
  {
    surahName: {
      ar: "سورة الأنعام",
      bn: "সুরা আল-আন'আম",
      en: "Surah Al-An'am",
      hi: "सुरा अल-आन'आम",
      pt: "Surah Al-An'am",
      de: "Surah Al-An'am",
      fr: "Sourate Al-An'am",
      es: "Sura Al-An'am",
      tr: "Sure Al-An'am",
      it: "Sura Al-An'am",
      nl: "Soera Al-An'am",
      ru: "Сура Аль-Ан'ам",
      tl: "Surah Al-An'am",
      th: "ซูรอาห์ อัลอานอาม",
      id: "Surah Al-An'am",
      ja: "スーラ アルアナーム",
      ko: "수라 알안암",
      pl: "Surah Al-An'am",
      vi: "Surah Al-An'am",
      ta: "சூரா அல்-ஆனாம்",
      ur: "سورۃ الانعام",
      zh: "苏拉·阿尔-阿纳姆",
    },
    surahNumber: 6,
    juzNumber: [7, 8],
    totalAyah: 165,
  },
  {
    surahName: {
      ar: "سورة الأعراف",
      bn: "সুরা আল-আ'রাফ",
      en: "Surah Al-A'raf",
      hi: "सुरा अल-आ'राफ",
      pt: "Surah Al-A'raf",
      de: "Surah Al-A'raf",
      fr: "Sourate Al-A'raf",
      es: "Sura Al-A'raf",
      tr: "Sure Al-A'raf",
      it: "Sura Al-A'raf",
      nl: "Soera Al-A'raf",
      ru: "Сура Аль-А'раф",
      tl: "Surah Al-A'raf",
      th: "ซูรอาห์ อัลอาราฟ",
      id: "Surah Al-A'raf",
      ja: "スーラ アルアラフ",
      ko: "수라 알아랍",
      pl: "Surah Al-A'raf",
      vi: "Surah Al-A'raf",
      ta: "சூரா அல்-ஆர஫்",
      ur: "سورۃ الاعراف",
      zh: "苏拉·阿尔-阿拉夫",
    },
    surahNumber: 7,
    juzNumber: [8, 9],
    totalAyah: 206,
  },
  {
    surahName: {
      ar: "سورة الأنفال",
      bn: "সুরা আল-আনফাল",
      en: "Surah Al-Anfal",
      hi: "सुरा अल-अंफाल",
      pt: "Surah Al-Anfal",
      de: "Surah Al-Anfal",
      fr: "Sourate Al-Anfal",
      es: "Sura Al-Anfal",
      tr: "Sure Al-Anfal",
      it: "Sura Al-Anfal",
      nl: "Soera Al-Anfal",
      ru: "Сура Аль-Анфал",
      tl: "Surah Al-Anfal",
      th: "ซูรอาห์ อัลอันฟาล",
      id: "Surah Al-Anfal",
      ja: "スーラ アルアンファール",
      ko: "수라 알안팔",
      pl: "Surah Al-Anfal",
      vi: "Surah Al-Anfal",
      ta: "சூரா அல்-அன்ஃபால்",
      ur: "سورۃ الانفال",
      zh: "苏拉·阿尔-安法尔",
    },
    surahNumber: 8,
    juzNumber: [9, 10],
    totalAyah: 75,
  },
  {
    surahName: {
      ar: "سورة التوبة",
      bn: "সুরা আত-তাওবাহ",
      en: "Surah At-Tawbah",
      hi: "सुरा अत-तौबा",
      pt: "Surah At-Tawbah",
      de: "Surah At-Tawbah",
      fr: "Sourate At-Tawbah",
      es: "Sura At-Tawbah",
      tr: "Sure At-Tawbah",
      it: "Sura At-Tawbah",
      nl: "Soera At-Tawbah",
      ru: "Сура Ат-Тауба",
      tl: "Surah At-Tawbah",
      th: "ซูรอาห์ อัตเตาบะห์",
      id: "Surah At-Tawbah",
      ja: "スーラ アットタウバ",
      ko: "수라 앗타우바",
      pl: "Surah At-Tawbah",
      vi: "Surah At-Tawbah",
      ta: "சூரா அத்-தௌபா",
      ur: "سورۃ التوبة",
      zh: "苏拉·塔乌巴",
    },
    surahNumber: 9,
    juzNumber: [10, 11],
    totalAyah: 129,
  },
  {
    surahName: {
      ar: "سورة يونس",
      bn: "সুরা ইউনুস",
      en: "Surah Yunus",
      hi: "सुरा युनुस",
      pt: "Surah Yunus",
      de: "Surah Yunus",
      fr: "Sourate Yunus",
      es: "Sura Yunus",
      tr: "Sure Yunus",
      it: "Sura Yunus",
      nl: "Soera Yunus",
      ru: "Сура Юнус",
      tl: "Surah Yunus",
      th: "ซูรอาห์ ยูนุส",
      id: "Surah Yunus",
      ja: "スーラ ユヌス",
      ko: "수라 유누스",
      pl: "Surah Yunus",
      vi: "Surah Yunus",
      ta: "சூரா யூனுஸ்",
      ur: "سورۃ یونس",
      zh: "苏拉·尤努斯",
    },
    surahNumber: 10,
    juzNumber: [11],
    totalAyah: 109,
  },
  {
    surahName: {
      ar: "سورة هود",
      bn: "সুরা হুদ",
      en: "Surah Hud",
      hi: "सुरा हुद",
      pt: "Surah Hud",
      de: "Surah Hud",
      fr: "Sourate Hud",
      es: "Sura Hud",
      tr: "Sure Hud",
      it: "Sura Hud",
      nl: "Soera Hud",
      ru: "Сура Худ",
      tl: "Surah Hud",
      th: "ซูรอาห์ ฮุด",
      id: "Surah Hud",
      ja: "スーラ フッド",
      ko: "수라 후드",
      pl: "Surah Hud",
      vi: "Surah Hud",
      ta: "சூரா ஹூத்",
      ur: "سورۃ ہود",
      zh: "苏拉·胡德",
    },
    surahNumber: 11,
    juzNumber: [11, 12],
    totalAyah: 123,
  },
  {
    surahName: {
      ar: "سورة يوسف",
      bn: "সুরা ইউসুফ",
      en: "Surah Yusuf",
      hi: "सुरा यूसुफ",
      pt: "Surah Yusuf",
      de: "Surah Yusuf",
      fr: "Sourate Yusuf",
      es: "Sura Yusuf",
      tr: "Sure Yusuf",
      it: "Sura Yusuf",
      nl: "Soera Yusuf",
      ru: "Сура Юсуф",
      tl: "Surah Yusuf",
      th: "ซูรอาห์ ยูซุฟ",
      id: "Surah Yusuf",
      ja: "スーラ ユースフ",
      ko: "수라 유수프",
      pl: "Surah Yusuf",
      vi: "Surah Yusuf",
      ta: "சூரா யூசுப்",
      ur: "سورۃ یوسف",
      zh: "苏拉·尤素福",
    },
    surahNumber: 12,
    juzNumber: [12, 13],
    totalAyah: 111,
  },
  {
    surahName: {
      ar: "سورة الرعد",
      bn: "সুরা আর-রাদ",
      en: "Surah Ar-Rad",
      hi: "सुरा अर-रद",
      pt: "Surah Ar-Rad",
      de: "Surah Ar-Rad",
      fr: "Sourate Ar-Rad",
      es: "Sura Ar-Rad",
      tr: "Sure Ar-Rad",
      it: "Sura Ar-Rad",
      nl: "Soera Ar-Rad",
      ru: "Сура Ар-Рад",
      tl: "Surah Ar-Rad",
      th: "ซูรอาห์ อาร์รัด",
      id: "Surah Ar-Rad",
      ja: "スーラ アルラッド",
      ko: "수라 알라드",
      pl: "Surah Ar-Rad",
      vi: "Surah Ar-Rad",
      ta: "சூரா அர்-ரத்",
      ur: "سورۃ الرعد",
      zh: "苏拉·阿尔拉德",
    },
    surahNumber: 13,
    juzNumber: [13],
    totalAyah: 43,
  },
  {
    surahName: {
      ar: "سورة إبراهيم",
      bn: "সুরা ইব্রাহীম",
      en: "Surah Ibrahim",
      hi: "सुरा इब्राहीम",
      pt: "Surah Ibrahim",
      de: "Surah Ibrahim",
      fr: "Sourate Ibrahim",
      es: "Sura Ibrahim",
      tr: "Sure Ibrahim",
      it: "Sura Ibrahim",
      nl: "Soera Ibrahim",
      ru: "Сура Ибрахим",
      tl: "Surah Ibrahim",
      th: "ซูรอาห์ ইব্রাহীম",
      id: "Surah Ibrahim",
      ja: "スーラ イブラヒム",
      ko: "수라 이브라힘",
      pl: "Surah Ibrahim",
      vi: "Surah Ibrahim",
      ta: "சூரா இப்ராஹீம்",
      ur: "سورۃ ابراہیم",
      zh: "苏拉·易卜拉欣",
    },
    surahNumber: 14,
    juzNumber: [13],
    totalAyah: 52,
  },
  {
    surahName: {
      ar: "سورة الحجر",
      bn: "সুরা আল-হিজর",
      en: "Surah Al-Hijr",
      hi: "सुरा अल-हिज्र",
      pt: "Surah Al-Hijr",
      de: "Surah Al-Hijr",
      fr: "Sourate Al-Hijr",
      es: "Sura Al-Hijr",
      tr: "Sure Al-Hijr",
      it: "Sura Al-Hijr",
      nl: "Soera Al-Hijr",
      ru: "Сура Аль-Хиджр",
      tl: "Surah Al-Hijr",
      th: "ซูรอาห์ อัลฮิจร์",
      id: "Surah Al-Hijr",
      ja: "スーラ アルヒジュル",
      ko: "수라 알히르",
      pl: "Surah Al-Hijr",
      vi: "Surah Al-Hijr",
      ta: "சூரா அல்-ஹிஜ்ர்",
      ur: "سورۃ الحجر",
      zh: "苏拉·胡哲尔",
    },
    surahNumber: 15,
    juzNumber: [14],
    totalAyah: 99,
  },
  {
    surahName: {
      ar: "سورة النحل",
      bn: "সুরা আন-নাহল",
      en: "Surah An-Nahl",
      hi: "सुरा अन-नहल",
      pt: "Surah An-Nahl",
      de: "Surah An-Nahl",
      fr: "Sourate An-Nahl",
      es: "Sura An-Nahl",
      tr: "Sure An-Nahl",
      it: "Sura An-Nahl",
      nl: "Soera An-Nahl",
      ru: "Сура Ан-Нахль",
      tl: "Surah An-Nahl",
      th: "ซูรอาห์ อัลนาห์ล",
      id: "Surah An-Nahl",
      ja: "スーラ アンナール",
      ko: "수라 안날",
      pl: "Surah An-Nahl",
      vi: "Surah An-Nahl",
      ta: "சூரா அன்-நஹ்ல்",
      ur: "سورۃ النحل",
      zh: "苏拉·纳赫勒",
    },
    surahNumber: 16,
    juzNumber: [14],
    totalAyah: 128,
  },
  {
    surahName: {
      ar: "سورة الإسراء",
      bn: "সুরা আল-ইসরা",
      en: "Surah Al-Isra",
      hi: "सुरा अल-इसरा",
      pt: "Surah Al-Isra",
      de: "Surah Al-Isra",
      fr: "Sourate Al-Isra",
      es: "Sura Al-Isra",
      tr: "Sure Al-Isra",
      it: "Sura Al-Isra",
      nl: "Soera Al-Isra",
      ru: "Сура Аль-Исра",
      tl: "Surah Al-Isra",
      th: "ซูรอาห์ อัลอิสรา",
      id: "Surah Al-Isra",
      ja: "スーラ アルイスラ",
      ko: "수라 알이스라",
      pl: "Surah Al-Isra",
      vi: "Surah Al-Isra",
      ta: "சூரா அல-இஸ்ரா",
      ur: "سورۃ الإسراء",
      zh: "苏拉·以色列",
    },
    surahNumber: 17,
    juzNumber: [15],
    totalAyah: 111,
  },
  {
    surahName: {
      ar: "سورة الكهف",
      bn: "সুরা আল-কাহফ",
      en: "Surah Al-Kahf",
      hi: "सुरा अल-कहफ",
      pt: "Surah Al-Kahf",
      de: "Surah Al-Kahf",
      fr: "Sourate Al-Kahf",
      es: "Sura Al-Kahf",
      tr: "Sure Al-Kahf",
      it: "Sura Al-Kahf",
      nl: "Soera Al-Kahf",
      ru: "Сура Аль-Кахф",
      tl: "Surah Al-Kahf",
      th: "ซูรอาห์ อัลคัฟ",
      id: "Surah Al-Kahf",
      ja: "スーラ アルカフ",
      ko: "수라 알카프",
      pl: "Surah Al-Kahf",
      vi: "Surah Al-Kahf",
      ta: "சூரா அல்-காஃப்",
      ur: "سورۃ الکہف",
      zh: "苏拉·凯夫",
    },
    surahNumber: 18,
    juzNumber: [15, 16],
    totalAyah: 110,
  },
  {
    surahName: {
      ar: "سورة مريم",
      bn: "সুরা মারইয়াম",
      en: "Surah Maryam",
      hi: "सुरा मरियम",
      pt: "Surah Maryam",
      de: "Surah Maryam",
      fr: "Sourate Maryam",
      es: "Sura Maryam",
      tr: "Sure Maryam",
      it: "Sura Maryam",
      nl: "Soera Maryam",
      ru: "Сура Мариам",
      tl: "Surah Maryam",
      th: "ซูรอาห์ มารียัม",
      id: "Surah Maryam",
      ja: "スーラ マリアム",
      ko: "수라 마리암",
      pl: "Surah Maryam",
      vi: "Surah Maryam",
      ta: "சூரா மரியாம்",
      ur: "سورۃ مریم",
      zh: "苏拉·玛丽亚姆",
    },
    surahNumber: 19,
    juzNumber: [16],
    totalAyah: 98,
  },
  {
    surahName: {
      ar: "سورة طه",
      bn: "সুরা তা-হা",
      en: "Surah Ta-Ha",
      hi: "सुरा ता-हा",
      pt: "Surah Ta-Ha",
      de: "Surah Ta-Ha",
      fr: "Sourate Ta-Ha",
      es: "Sura Ta-Ha",
      tr: "Sure Ta-Ha",
      it: "Sura Ta-Ha",
      nl: "Soera Ta-Ha",
      ru: "Сура Та-Ха",
      tl: "Surah Ta-Ha",
      th: "ซูรอาห์ ทา-ฮา",
      id: "Surah Ta-Ha",
      ja: "スーラ ター・ハ",
      ko: "수라 타-하",
      pl: "Surah Ta-Ha",
      vi: "Surah Ta-Ha",
      ta: "சூரா தா-ஹா",
      ur: "سورۃ طہ",
      zh: "苏拉·塔哈",
    },
    surahNumber: 20,
    juzNumber: [16],
    totalAyah: 135,
  },
  {
    surahName: {
      ar: "سورة الأنبياء",
      bn: "সুরা আল-আম্বিয়া",
      en: "Surah Al-Anbiya",
      hi: "सुरा अल-अंबिया",
      pt: "Surah Al-Anbiya",
      de: "Surah Al-Anbiya",
      fr: "Sourate Al-Anbiya",
      es: "Sura Al-Anbiya",
      tr: "Sure Al-Anbiya",
      it: "Sura Al-Anbiya",
      nl: "Soera Al-Anbiya",
      ru: "Сура Аль-Анбия",
      tl: "Surah Al-Anbiya",
      th: "ซูรอาห์ อัลอัมบิยา",
      id: "Surah Al-Anbiya",
      ja: "スーラ アルアンビヤ",
      ko: "수라 알암비야",
      pl: "Surah Al-Anbiya",
      vi: "Surah Al-Anbiya",
      ta: "சூரா அல்-அம்பியா",
      ur: "سورۃ الانبیاء",
      zh: "苏拉·安比亚",
    },
    surahNumber: 21,
    juzNumber: [17],
    totalAyah: 112,
  },
  {
    surahName: {
      ar: "سورة الحج",
      bn: "সুরা আল-হজ্জ",
      en: "Surah Al-Hajj",
      hi: "सुरा अल-हज",
      pt: "Surah Al-Hajj",
      de: "Surah Al-Hajj",
      fr: "Sourate Al-Hajj",
      es: "Sura Al-Hajj",
      tr: "Sure Al-Hajj",
      it: "Sura Al-Hajj",
      nl: "Soera Al-Hajj",
      ru: "Сура Аль-Хадж",
      tl: "Surah Al-Hajj",
      th: "ซูรอาห์ อัลฮัจญ์",
      id: "Surah Al-Hajj",
      ja: "スーラ アルハッジ",
      ko: "수라 알하지",
      pl: "Surah Al-Hajj",
      vi: "Surah Al-Hajj",
      ta: "சூரா அல்-ஹஜ்",
      ur: "سورۃ الحج",
      zh: "苏拉·哈吉",
    },
    surahNumber: 22,
    juzNumber: [17],
    totalAyah: 78,
  },
  {
    surahName: {
      ar: "سورة المؤمنون",
      bn: "সুরা আল-মুমিনুন",
      en: "Surah Al-Mu'minun",
      hi: "सुरा अल-मुमिनून",
      pt: "Surah Al-Mu'minun",
      de: "Surah Al-Mu'minun",
      fr: "Sourate Al-Mu'minun",
      es: "Sura Al-Mu'minun",
      tr: "Sure Al-Mu'minun",
      it: "Sura Al-Mu'minun",
      nl: "Soera Al-Mu'minun",
      ru: "Сура Аль-Му'минун",
      tl: "Surah Al-Mu'minun",
      th: "ซูรอาห์ อัลมุอ์มินูน",
      id: "Surah Al-Mu'minun",
      ja: "スーラ アルムミヌン",
      ko: "수라 알무민운",
      pl: "Surah Al-Mu'minun",
      vi: "Surah Al-Mu'minun",
      ta: "சூரா அல்-மூமினூன்",
      ur: "سورۃ المؤمنون",
      zh: "苏拉·穆民",
    },
    surahNumber: 23,
    juzNumber: [18],
    totalAyah: 118,
  },
  {
    surahName: {
      ar: "سورة النور",
      bn: "সুরা আন-নূর",
      en: "Surah An-Noor",
      hi: "सुरा अन-नूर",
      pt: "Surah An-Noor",
      de: "Surah An-Noor",
      fr: "Sourate An-Noor",
      es: "Sura An-Noor",
      tr: "Sure An-Noor",
      it: "Sura An-Noor",
      nl: "Soera An-Noor",
      ru: "Сура Ан-Нур",
      tl: "Surah An-Noor",
      th: "ซูรอาห์ อัลนูร์",
      id: "Surah An-Noor",
      ja: "スーラ アンヌール",
      ko: "수라 안누르",
      pl: "Surah An-Noor",
      vi: "Surah An-Noor",
      ta: "சூரா அன்-நூர்",
      ur: "سورۃ النور",
      zh: "苏拉·努尔",
    },
    surahNumber: 24,
    juzNumber: [18],
    totalAyah: 64,
  },
  {
    surahName: {
      ar: "سورة الفرقان",
      bn: "সুরা আল-ফুরকান",
      en: "Surah Al-Furqan",
      hi: "सुरा अल-फुर्कान",
      pt: "Surah Al-Furqan",
      de: "Surah Al-Furqan",
      fr: "Sourate Al-Furqan",
      es: "Sura Al-Furqan",
      tr: "Sure Al-Furqan",
      it: "Sura Al-Furqan",
      nl: "Soera Al-Furqan",
      ru: "Сура Аль-Фуркан",
      tl: "Surah Al-Furqan",
      th: "ซูรอาห์ อัลฟุรกาน",
      id: "Surah Al-Furqan",
      ja: "スーラ アルフルカン",
      ko: "수라 알푸르칸",
      pl: "Surah Al-Furqan",
      vi: "Surah Al-Furqan",
      ta: "சூரா அல்-புர்கான்",
      ur: "سورۃ الفرقان",
      zh: "苏拉·福尔干",
    },
    surahNumber: 25,
    juzNumber: [18, 19],
    totalAyah: 77,
  },
  {
    surahName: {
      ar: "سورة الشعراء",
      bn: "সুরা আশ-শুআরা",
      en: "Surah Ash-Shu'ara",
      hi: "सुरा अश-शुआरा",
      pt: "Surah Ash-Shu'ara",
      de: "Surah Ash-Shu'ara",
      fr: "Sourate Ash-Shu'ara",
      es: "Sura Ash-Shu'ara",
      tr: "Sure Ash-Shu'ara",
      it: "Sura Ash-Shu'ara",
      nl: "Soera Ash-Shu'ara",
      ru: "Сура Аш-Шуара",
      tl: "Surah Ash-Shu'ara",
      th: "ซูรอาห์ อัลชัวรา",
      id: "Surah Ash-Shu'ara",
      ja: "スーラ アシュシュアラ",
      ko: "수라 아쉬슈아라",
      pl: "Surah Ash-Shu'ara",
      vi: "Surah Ash-Shu'ara",
      ta: "சூரா அஷ்-ஷூஅரா",
      ur: "سورۃ الشعراء",
      zh: "苏拉·诗人",
    },
    surahNumber: 26,
    juzNumber: [19],
    totalAyah: 227,
  },
  {
    surahName: {
      ar: "سورة النمل",
      bn: "সুরা আন-নামল",
      en: "Surah An-Naml",
      hi: "सुरा अन-नमल",
      pt: "Surah An-Naml",
      de: "Surah An-Naml",
      fr: "Sourate An-Naml",
      es: "Sura An-Naml",
      tr: "Sure An-Naml",
      it: "Sura An-Naml",
      nl: "Soera An-Naml",
      ru: "Сура Ан-Намл",
      tl: "Surah An-Naml",
      th: "ซูรอาห์ อัลนัมล",
      id: "Surah An-Naml",
      ja: "スーラ アンナムル",
      ko: "수라 안남르",
      pl: "Surah An-Naml",
      vi: "Surah An-Naml",
      ta: "சூரா அல்-நமல்",
      ur: "سورۃ النمل",
      zh: "苏拉·蚂蚁",
    },
    surahNumber: 27,
    juzNumber: [19, 20],
    totalAyah: 93,
  },
  {
    surahName: {
      ar: "سورة القصص",
      bn: "সুরা আল-কাসাস",
      en: "Surah Al-Qasas",
      hi: "सुरा अल-क़सस",
      pt: "Surah Al-Qasas",
      de: "Surah Al-Qasas",
      fr: "Sourate Al-Qasas",
      es: "Sura Al-Qasas",
      tr: "Sure Al-Qasas",
      it: "Sura Al-Qasas",
      nl: "Soera Al-Qasas",
      ru: "Сура Аль-Касас",
      tl: "Surah Al-Qasas",
      th: "ซูรอาห์ อัลกาซัส",
      id: "Surah Al-Qasas",
      ja: "スーラ アルカサス",
      ko: "수라 알카사스",
      pl: "Surah Al-Qasas",
      vi: "Surah Al-Qasas",
      ta: "சூரா அல்-கஸஸ்",
      ur: "سورۃ القصص",
      zh: "苏拉·故事",
    },
    surahNumber: 28,
    juzNumber: [20],
    totalAyah: 88,
  },
  {
    surahName: {
      ar: "سورة العنكبوت",
      bn: "সুরা আল-আনকাবুত",
      en: "Surah Al-'Ankabut",
      hi: "सुरा अल-आंन्काबूत",
      pt: "Surah Al-'Ankabut",
      de: "Surah Al-'Ankabut",
      fr: "Sourate Al-'Ankabut",
      es: "Sura Al-'Ankabut",
      tr: "Sure Al-'Ankabut",
      it: "Sura Al-'Ankabut",
      nl: "Soera Al-'Ankabut",
      ru: "Сура Аль-Анкабут",
      tl: "Surah Al-'Ankabut",
      th: "ซูรอาห์ อัลอังคาบุต",
      id: "Surah Al-'Ankabut",
      ja: "スーラ アルアンカブート",
      ko: "수라 알앙카부트",
      pl: "Surah Al-'Ankabut",
      vi: "Surah Al-'Ankabut",
      ta: "சூரா அல்-அங்காபூத்",
      ur: "سورۃ العنكبوت",
      zh: "苏拉·安卡布特",
    },
    surahNumber: 29,
    juzNumber: [20, 21],
    totalAyah: 69,
  },
  {
    surahName: {
      ar: "سورة الروم",
      bn: "সুরা আর-রূম",
      en: "Surah Ar-Rum",
      hi: "सुरा अर-रूम",
      pt: "Surah Ar-Rum",
      de: "Surah Ar-Rum",
      fr: "Sourate Ar-Rum",
      es: "Sura Ar-Rum",
      tr: "Sure Ar-Rum",
      it: "Sura Ar-Rum",
      nl: "Soera Ar-Rum",
      ru: "Сура Ар-Рум",
      tl: "Surah Ar-Rum",
      th: "ซูรอาห์ อาร์รูม",
      id: "Surah Ar-Rum",
      ja: "スーラ アルルーム",
      ko: "수라 알룸",
      pl: "Surah Ar-Rum",
      vi: "Surah Ar-Rum",
      ta: "சூரா அர்-ரூம்",
      ur: "سورۃ الروم",
      zh: "苏拉·罗马",
    },
    surahNumber: 30,
    juzNumber: [21],
    totalAyah: 60,
  },
  {
    surahName: {
      ar: "سورة لقمان",
      bn: "সুরা লুকমান",
      en: "Surah Luqman",
      hi: "सूरा लुक़मान",
      pt: "Surah Luqman",
      de: "Surah Luqman",
      fr: "Sourate Luqman",
      es: "Sura Luqman",
      tr: "Sure Lokman",
      it: "Sura Luqman",
      nl: "Soera Loekman",
      ru: "Сура Лукман",
      tl: "Surah Luqman",
      th: "ซูรอาห์ ลูกมาน",
      id: "Surah Luqman",
      ja: "スーラ ルクマン",
      ko: "수라 루크만",
      pl: "Surah Luqman",
      vi: "Surah Luqman",
      ta: "சூரா லுக்மான்",
      ur: "سورۃ لقمان",
      zh: "苏拉·鲁格曼",
    },
    surahNumber: 31,
    juzNumber: [21],
    totalAyah: 34,
  },
  {
    surahName: {
      ar: "سورة السجدة",
      bn: "সুরা আস-সাজদাহ",
      en: "Surah As-Sajdah",
      hi: "सूरा अस-सज्दाह",
      pt: "Surah As-Sajdah",
      de: "Surah As-Sajdah",
      fr: "Sourate As-Sajdah",
      es: "Sura As-Sajdah",
      tr: "Sure Secde",
      it: "Sura As-Sajdah",
      nl: "Soera As-Sajdah",
      ru: "Сура Ас-Саджда",
      tl: "Surah As-Sajdah",
      th: "ซูรอาห์ อัสซัจดะห์",
      id: "Surah As-Sajdah",
      ja: "スーラ アッサジダ",
      ko: "수라 알사지다",
      pl: "Surah As-Sajdah",
      vi: "Surah As-Sajdah",
      ta: "சூரா அல்-சஜ்தா",
      ur: "سورۃ السجدة",
      zh: "苏拉·萨吉达",
    },
    surahNumber: 32,
    juzNumber: [21],
    totalAyah: 30,
  },
  {
    surahName: {
      ar: "سورة الأحزاب",
      bn: "সুরা আল-আহযাব",
      en: "Surah Al-Ahzab",
      hi: "सूरा अल-अहज़ाब",
      pt: "Surah Al-Ahzab",
      de: "Surah Al-Ahzab",
      fr: "Sourate Al-Ahzab",
      es: "Sura Al-Ahzab",
      tr: "Sure Ahzab",
      it: "Sura Al-Ahzab",
      nl: "Soera Al-Ahzab",
      ru: "Сура Аль-Ахзаб",
      tl: "Surah Al-Ahzab",
      th: "ซูรอาห์ อัลอะห์ซาบ",
      id: "Surah Al-Ahzab",
      ja: "スーラ アルアハザーブ",
      ko: "수라 알아흐자브",
      pl: "Surah Al-Ahzab",
      vi: "Surah Al-Ahzab",
      ta: "சூரா அல்-அஹ்சாப்",
      ur: "سورۃ الأحزاب",
      zh: "苏拉·艾哈扎布",
    },
    surahNumber: 33,
    juzNumber: [21, 22],
    totalAyah: 73,
  },
  {
    surahName: {
      ar: "سورة سبأ",
      bn: "সুরা সাবা",
      en: "Surah Saba",
      hi: "सूरा सबा",
      pt: "Surah Saba",
      de: "Surah Saba",
      fr: "Sourate Saba",
      es: "Sura Saba",
      tr: "Sure Sebe",
      it: "Sura Saba",
      nl: "Soera Saba",
      ru: "Сура Саба",
      tl: "Surah Saba",
      th: "ซูรอาห์ ซะบะอ์",
      id: "Surah Saba",
      ja: "スーラ サバ",
      ko: "수라 사바",
      pl: "Surah Saba",
      vi: "Surah Saba",
      ta: "சூரா சபா",
      ur: "سورۃ سبأ",
      zh: "苏拉·萨巴",
    },
    surahNumber: 34,
    juzNumber: [22],
    totalAyah: 54,
  },
  {
    surahName: {
      ar: "سورة فاطر",
      bn: "সুরা ফাতির",
      en: "Surah Fatir",
      hi: "सूरा फातिर",
      pt: "Surah Fatir",
      de: "Surah Fatir",
      fr: "Sourate Fatir",
      es: "Sura Fatir",
      tr: "Sure Fatır",
      it: "Sura Fatir",
      nl: "Soera Fatir",
      ru: "Сура Фатир",
      tl: "Surah Fatir",
      th: "ซูรอาห์ ฟาติร",
      id: "Surah Fatir",
      ja: "スーラ ファティル",
      ko: "수라 파티르",
      pl: "Surah Fatir",
      vi: "Surah Fatir",
      ta: "சூரா பாதிர்",
      ur: "سورۃ فاطر",
      zh: "苏拉·法蒂尔",
    },
    surahNumber: 35,
    juzNumber: [22],
    totalAyah: 45,
  },
  {
    surahName: {
      ar: "سورة يس",
      bn: "সুরা ইয়াসীন",
      en: "Surah Ya-Seen",
      hi: "सूरा या-सीन",
      pt: "Surah Ya-Seen",
      de: "Surah Ya-Seen",
      fr: "Sourate Ya-Sin",
      es: "Sura Ya-Sin",
      tr: "Sure Yasin",
      it: "Sura Ya-Sin",
      nl: "Soera Ya-Sin",
      ru: "Сура Я-Син",
      tl: "Surah Ya-Seen",
      th: "ซูรอาห์ ยาซีน",
      id: "Surah Ya-Seen",
      ja: "スーラ ヤーシーン",
      ko: "수라 야신",
      pl: "Surah Ya-Seen",
      vi: "Surah Ya-Seen",
      ta: "சூரா யாசீன்",
      ur: "سورۃ يس",
      zh: "苏拉·亚辛",
    },
    surahNumber: 36,
    juzNumber: [22, 23],
    totalAyah: 83,
  },
  {
    surahName: {
      ar: "سورة الصافات",
      bn: "সুরা আস-সাফফাত",
      en: "Surah As-Saffat",
      hi: "सूरा अस-साफ्फात",
      pt: "Surah As-Saffat",
      de: "Surah As-Saffat",
      fr: "Sourate As-Saffat",
      es: "Sura As-Saffat",
      tr: "Sure Saffat",
      it: "Sura As-Saffat",
      nl: "Soera As-Saffat",
      ru: "Сура Ас-Саффат",
      tl: "Surah As-Saffat",
      th: "ซูรอาห์ อัซซัฟฟาต",
      id: "Surah As-Saffat",
      ja: "スーラ アッサッファート",
      ko: "수라 아스사파트",
      pl: "Surah As-Saffat",
      vi: "Surah As-Saffat",
      ta: "சூரா அஸ்-சஃபாத்",
      ur: "سورۃ الصافات",
      zh: "苏拉·萨法特",
    },
    surahNumber: 37,
    juzNumber: [23],
    totalAyah: 182,
  },
  {
    surahName: {
      ar: "سورة ص",
      bn: "সুরা ছাদ",
      en: "Surah Sad",
      hi: "सूरा साद",
      pt: "Surah Sad",
      de: "Surah Sad",
      fr: "Sourate Sad",
      es: "Sura Sad",
      tr: "Sure Sad",
      it: "Sura Sad",
      nl: "Soera Sad",
      ru: "Сура Сад",
      tl: "Surah Sad",
      th: "ซูรอาห์ ซอด",
      id: "Surah Sad",
      ja: "スーラ サード",
      ko: "수라 사드",
      pl: "Surah Sad",
      vi: "Surah Sad",
      ta: "சூரா சாத்",
      ur: "سورۃ ص",
      zh: "苏拉·萨德",
    },
    surahNumber: 38,
    juzNumber: [23],
    totalAyah: 88,
  },
  {
    surahName: {
      ar: "سورة الزمر",
      bn: "সুরা আজ-জুমার",
      en: "Surah Az-Zumar",
      hi: "सूरा अज़-जुमर",
      pt: "Surah Az-Zumar",
      de: "Surah Az-Zumar",
      fr: "Sourate Az-Zumar",
      es: "Sura Az-Zumar",
      tr: "Sure Zümer",
      it: "Sura Az-Zumar",
      nl: "Soera Az-Zumar",
      ru: "Сура Аз-Зумар",
      tl: "Surah Az-Zumar",
      th: "ซูรอาห์ อัซซุมาร",
      id: "Surah Az-Zumar",
      ja: "スーラ アズ-ズマル",
      ko: "수라 아즈-주마르",
      pl: "Surah Az-Zumar",
      vi: "Surah Az-Zumar",
      ta: "சூரா அல்-ஜுமர்",
      ur: "سورۃ الزمر",
      zh: "苏拉·祖马尔",
    },
    surahNumber: 39,
    juzNumber: [23],
    totalAyah: 75,
  },
  {
    surahName: {
      ar: "سورة غافر",
      bn: "সুরা গাফির",
      en: "Surah Ghafir",
      hi: "सूरा ग़ाफ़िर",
      pt: "Surah Ghafir",
      de: "Surah Ghafir",
      fr: "Sourate Ghafir",
      es: "Sura Ghafir",
      tr: "Sure Gafir",
      it: "Sura Ghafir",
      nl: "Soera Ghafir",
      ru: "Сура Гафир",
      tl: "Surah Ghafir",
      th: "ซูรอาห์ ฆอฟิร",
      id: "Surah Ghafir",
      ja: "スーラ ガーフィル",
      ko: "수라 가피르",
      pl: "Surah Ghafir",
      vi: "Surah Ghafir",
      ta: "சூரா காஃபிர்",
      ur: "سورۃ غافر",
      zh: "苏拉·加菲尔",
    },
    surahNumber: 40,
    juzNumber: [24],
    totalAyah: 85,
  },
  {
    surahName: {
      ar: "سورة فصلت",
      bn: "সুরা ফুসসিলাত",
      en: "Surah Fussilat",
      hi: "सूरा फुस्सिलात",
      pt: "Surah Fussilat",
      de: "Surah Fussilat",
      fr: "Sourate Fussilat",
      es: "Sura Fussilat",
      tr: "Sure Fussilet",
      it: "Sura Fussilat",
      nl: "Soera Fussilat",
      ru: "Сура Фуссилят",
      tl: "Surah Fussilat",
      th: "ซูเราะห์ ฟุซศิลัต",
      id: "Surah Fussilat",
      ja: "スーラ フッシラト",
      ko: "수라 푸실라트",
      pl: "Surah Fussilat",
      vi: "Surah Fussilat",
      ta: "சூரா புஸ்ஸிலாத்",
      ur: "سورۃ فصلت",
      zh: "苏拉·福斯西拉特",
    },
    surahNumber: 41,
    juzNumber: [24, 25],
    totalAyah: 54,
  },
  {
    surahName: {
      ar: "سورة الشورى",
      bn: "সুরা আশ-শূরা",
      en: "Surah Ash-Shuraa",
      hi: "सूरा अश-शूरा",
      pt: "Surah Ash-Shuraa",
      de: "Surah Ash-Shuraa",
      fr: "Sourate Ash-Shuraa",
      es: "Sura Ash-Shuraa",
      tr: "Sure Ash-Şura",
      it: "Sura Ash-Shuraa",
      nl: "Soera Ash-Shuraa",
      ru: "Сура Аш-Шура",
      tl: "Surah Ash-Shuraa",
      th: "ซูรอาห์ อัช-ชูรอ",
      id: "Surah Ash-Shuraa",
      ja: "スーラ アッシューラー",
      ko: "수라 아슈-슈라",
      pl: "Surah Ash-Shuraa",
      vi: "Surah Ash-Shuraa",
      ta: "சூரா அஷ்-சூரா",
      ur: "سورۃ الشورى",
      zh: "苏拉·阿什-舒拉",
    },
    surahNumber: 42,
    juzNumber: [25],
    totalAyah: 53,
  },
  {
    surahName: {
      ar: "سورة الزخرف",
      bn: "সুরা আজ-জুখরুফ",
      en: "Surah Az-Zukhruf",
      hi: "सूरा अज़-जुख़रुफ़",
      pt: "Surah Az-Zukhruf",
      de: "Surah Az-Zukhruf",
      fr: "Sourate Az-Zukhruf",
      es: "Sura Az-Zukhruf",
      tr: "Sure Az-Zuhruf",
      it: "Sura Az-Zukhruf",
      nl: "Soera Az-Zoekhroef",
      ru: "Сура Аз-Зухруф",
      tl: "Surah Az-Zukhruf",
      th: "ซูเราะห์ อัซ-ซุครุฟ",
      id: "Surah Az-Zukhruf",
      ja: "スーラ アズ-ズフルフ",
      ko: "수라 아즈-주흐루프",
      pl: "Surah Az-Zukhruf",
      vi: "Surah Az-Zukhruf",
      ta: "சூரா அஸ்-சுக்ரூப்",
      ur: "سورۃ الزخرف",
      zh: "苏拉·阿兹-祖赫鲁夫",
    },
    surahNumber: 43,
    juzNumber: [25],
    totalAyah: 89,
  },
  {
    surahName: {
      ar: "سورة الدخان",
      bn: "সুরা আদ-দুখান",
      en: "Surah Ad-Dukhan",
      hi: "सूरा अद-दुख़ान",
      pt: "Surah Ad-Dukhan",
      de: "Surah Ad-Dukhan",
      fr: "Sourate Ad-Dukhan",
      es: "Sura Ad-Dukhan",
      tr: "Sure Ad-Duhan",
      it: "Sura Ad-Dukhan",
      nl: "Soera Ad-Doekhan",
      ru: "Сура Ад-Духан",
      tl: "Surah Ad-Dukhan",
      th: "ซูเราะห์อัดดุคาน",
      id: "Surah Ad-Dukhan",
      ja: "スーラ アド-ドゥハーン",
      ko: "수라 아드-두칸",
      pl: "Surah Ad-Dukhan",
      vi: "Surah Ad-Dukhan",
      ta: "சூரா அத்-துகான்",
      ur: "سورۃ الدخان",
      zh: "苏拉·阿德-杜汉",
    },
    surahNumber: 44,
    juzNumber: [25],
    totalAyah: 59,
  },
  {
    surahName: {
      ar: "سورة الجاثية",
      bn: "সুরা আল-জাসিয়া",
      en: "Surah Al-Jathiyah",
      hi: "सूरा अल-जासिया",
      pt: "Surah Al-Jathiyah",
      de: "Surah Al-Jathiyah",
      fr: "Sourate Al-Jathiyah",
      es: "Sura Al-Jathiyah",
      tr: "Sure Al-Câsiye",
      it: "Sura Al-Jathiyah",
      nl: "Soera Al-Djathiyah",
      ru: "Сура Аль-Джасийя",
      tl: "Surah Al-Jathiyah",
      th: "ซูรอาห์ อัล-จาธียะห์",
      id: "Surah Al-Jathiyah",
      ja: "スーラ アル-ジャシーヤ",
      ko: "수라 알-자시야",
      pl: "Surah Al-Jathiyah",
      vi: "Surah Al-Jathiyah",
      ta: "சூரா அல்-ஜாதியா",
      ur: "سورۃ الجاثية",
      zh: "苏拉·阿尔-贾西耶",
    },
    surahNumber: 45,
    juzNumber: [25],
    totalAyah: 37,
  },
  {
    surahName: {
      ar: "سورة الأحقاف",
      bn: "সুরা আল-আহকাফ",
      en: "Surah Al-Ahqaf",
      hi: "सूरा अल-अहक़ाफ़",
      pt: "Surah Al-Ahqaf",
      de: "Surah Al-Ahqaf",
      fr: "Sourate Al-Ahqaf",
      es: "Sura Al-Ahqaf",
      tr: "Sure Al-Ahkaf",
      it: "Sura Al-Ahqaf",
      nl: "Soera Al-Ahqaf",
      ru: "Сура Аль-Ахкаф",
      tl: "Surah Al-Ahqaf",
      th: "ซูเราะห์อัลอะห์กอฟ",
      id: "Surah Al-Ahqaf",
      ja: "スーラ アル-アフカーフ",
      ko: "수라 알-아흐카프",
      pl: "Surah Al-Ahqaf",
      vi: "Surah Al-Ahqaf",
      ta: "சூரா அல-அஹ்காஃப்",
      ur: "سورۃ الأحقاف",
      zh: "苏拉·阿尔-艾哈卡夫",
    },

    surahNumber: 46,
    juzNumber: [26],
    totalAyah: 35,
  },
  {
    surahName: {
      ar: "سورة محمد",
      bn: "সুরা মুহাম্মাদ",
      en: "Surah Muhammad",
      hi: "सूरा मुहम्मद",
      pt: "Surah Muhammad",
      de: "Surah Muhammad",
      fr: "Sourate Muhammad",
      es: "Sura Muhammad",
      tr: "Sure Muhammed",
      it: "Sura Muhammad",
      nl: "Soera Mohammed",
      ru: "Сура Мухаммад",
      tl: "Surah Muhammad",
      th: "ซูรอาห์ มูฮัมหมัด",
      id: "Surah Muhammad",
      ja: "スーラ ムハンマド",
      ko: "수라 무함마드",
      pl: "Surah Muhammad",
      vi: "Surah Muhammad",
      ta: "சூரா முஹம்மது",
      ur: "سورۃ محمد",
      zh: "苏拉·穆罕默德",
    },
    surahNumber: 47,
    juzNumber: [26],
    totalAyah: 38,
  },
  {
    surahName: {
      ar: "سورة الفتح",
      bn: "সুরা আল-ফাতহ",
      en: "Surah Al-Fath",
      hi: "सूरा अल-फ़तह",
      pt: "Surah Al-Fath",
      de: "Surah Al-Fath",
      fr: "Sourate Al-Fath",
      es: "Sura Al-Fath",
      tr: "Sure Al-Fetih",
      it: "Sura Al-Fath",
      nl: "Soera Al-Fath",
      ru: "Сура Аль-Фатх",
      tl: "Surah Al-Fath",
      th: "ซูเราะห์อัลฟาตาห์",
      id: "Surah Al-Fath",
      ja: "スーラ アル-ファトフ",
      ko: "수라 알-파트흐",
      pl: "Surah Al-Fath",
      vi: "Surah Al-Fath",
      ta: "சூரா அல-பத்",
      ur: "سورۃ الفتح",
      zh: "苏拉·阿尔-法特赫",
    },
    surahNumber: 48,
    juzNumber: [26],
    totalAyah: 29,
  },
  {
    surahName: {
      ar: "سورة الحجرات",
      bn: "সুরা আল-হুজরাত",
      en: "Surah Al-Hujurat",
      hi: "सूरा अल-हुजुरात",
      pt: "Surah Al-Hujurat",
      de: "Surah Al-Hujurat",
      fr: "Sourate Al-Hujurat",
      es: "Sura Al-Hujurat",
      tr: "Sure Al-Hucurat",
      it: "Sura Al-Hujurat",
      nl: "Soera Al-Hoedjoerat",
      ru: "Сура Аль-Худжурат",
      tl: "Surah Al-Hujurat",
      th: "ซูรอาห์ อัล-ฮุจรอต",
      id: "Surah Al-Hujurat",
      ja: "スーラ アル-フジュラート",
      ko: "수라 알-후주라트",
      pl: "Surah Al-Hujurat",
      vi: "Surah Al-Hujurat",
      ta: "சூரா அல-ஹுஜுராத்",
      ur: "سورۃ الحجرات",
      zh: "苏拉·阿尔-胡朱拉特",
    },
    surahNumber: 49,
    juzNumber: [26],
    totalAyah: 18,
  },
  {
    surahName: {
      ar: "سورة ق",
      bn: "সুরা ক্বাফ",
      en: "Surah Qaf",
      hi: "सूरा क़ाफ़",
      pt: "Surah Qaf",
      de: "Surah Qaf",
      fr: "Sourate Qaf",
      es: "Sura Qaf",
      tr: "Sure Kaf",
      it: "Sura Qaf",
      nl: "Soera Qaf",
      ru: "Сура Каф",
      tl: "Surah Qaf",
      th: "ซูเราะห์กอฟ",
      id: "Surah Qaf",
      ja: "スーラ カーフ",
      ko: "수라 카프",
      pl: "Surah Qaf",
      vi: "Surah Qaf",
      ta: "சூரா காஃப்",
      ur: "سورۃ ق",
      zh: "苏拉·卡夫",
    },
    surahNumber: 50,
    juzNumber: [26],
    totalAyah: 45,
  },
  {
    surahName: {
      ar: "سورة الذاريات",
      bn: "সুরা আধ-ধারিয়াত",
      en: "Surah Adh-Dhariyat",
      hi: "सूरा अध-धारियात",
      pt: "Surah Adh-Dhariyat",
      de: "Surah Adh-Dhariyat",
      fr: "Sourate Adh-Dhariyat",
      es: "Sura Adh-Dhariyat",
      tr: "Sure Zariyat",
      it: "Sura Adh-Dhariyat",
      nl: "Soera Adh-Dhariyat",
      ru: "Сура Ад-Зарият",
      tl: "Surah Adh-Dhariyat",
      th: "ซูรอาห์ อัซซาริยาต",
      id: "Surah Adh-Dhariyat",
      ja: "スーラ アド-ザリヤート",
      ko: "수라 아드-자리얏",
      pl: "Surah Adh-Dhariyat",
      vi: "Surah Adh-Dhariyat",
      ta: "சூரா அத்-தாரியாத்",
      ur: "سورۃ الذاریات",
      zh: "苏拉·扎里亚特",
    },
    surahNumber: 51,
    juzNumber: [26],
    totalAyah: 60,
  },
  {
    surahName: {
      ar: "سورة الطور",
      bn: "সুরা আত-তূর",
      en: "Surah At-Tur",
      hi: "सूरा अत-तूर",
      pt: "Surah At-Tur",
      de: "Surah At-Tur",
      fr: "Sourate At-Tur",
      es: "Sura At-Tur",
      tr: "Sure Tur",
      it: "Sura At-Tur",
      nl: "Soera At-Tur",
      ru: "Сура Ат-Тур",
      tl: "Surah At-Tur",
      th: "ซูเราะห์อัตตุร",
      id: "Surah At-Tur",
      ja: "スーラ アット-トゥル",
      ko: "수라 앗-투르",
      pl: "Surah At-Tur",
      vi: "Surah At-Tur",
      ta: "சூரா அத்-தூர்",
      ur: "سورۃ الطور",
      zh: "苏拉·图尔",
    },
    surahNumber: 52,
    juzNumber: [27],
    totalAyah: 49,
  },
  {
    surahName: {
      ar: "سورة النجم",
      bn: "সুরা আন-নাজম",
      en: "Surah An-Najm",
      hi: "सूरा अन-नज्म",
      pt: "Surah An-Najm",
      de: "Surah An-Najm",
      fr: "Sourate An-Najm",
      es: "Sura An-Najm",
      tr: "Sure Necm",
      it: "Sura An-Najm",
      nl: "Soera An-Najm",
      ru: "Сура Ан-Наджм",
      tl: "Surah An-Najm",
      th: "ซูเราะห์อันนัซม์",
      id: "Surah An-Najm",
      ja: "スーラ アン-ナジュム",
      ko: "수라 안-나즘",
      pl: "Surah An-Najm",
      vi: "Surah An-Najm",
      ta: "சூரா அல்-நஜ்ம்",
      ur: "سورۃ النجم",
      zh: "苏拉·纳吉姆",
    },
    surahNumber: 53,
    juzNumber: [27],
    totalAyah: 62,
  },
  {
    surahName: {
      ar: "سورة القمر",
      bn: "সুরা আল-কামার",
      en: "Surah Al-Qamar",
      hi: "सूरा अल-क़मर",
      pt: "Surah Al-Qamar",
      de: "Surah Al-Qamar",
      fr: "Sourate Al-Qamar",
      es: "Sura Al-Qamar",
      tr: "Sure Kamer",
      it: "Sura Al-Qamar",
      nl: "Soera Al-Qamar",
      ru: "Сура Аль-Камар",
      tl: "Surah Al-Qamar",
      th: "ซูรอาห์ อัลกอมาร",
      id: "Surah Al-Qamar",
      ja: "スーラ アル-カマル",
      ko: "수라 알-카마르",
      pl: "Surah Al-Qamar",
      vi: "Surah Al-Qamar",
      ta: "சூரா அல்-கமர்",
      ur: "سورۃ القمر",
      zh: "苏拉·卡马尔",
    },
    surahNumber: 54,
    juzNumber: [27],
    totalAyah: 55,
  },
  {
    surahName: {
      ar: "سورة الرحمن",
      bn: "সুরা আর-রহমান",
      en: "Surah Ar-Rahman",
      hi: "सूरा अर-रहमान",
      pt: "Surah Ar-Rahman",
      de: "Surah Ar-Rahman",
      fr: "Sourate Ar-Rahman",
      es: "Sura Ar-Rahman",
      tr: "Sure Rahman",
      it: "Sura Ar-Rahman",
      nl: "Soera Ar-Rahman",
      ru: "Сура Ар-Рахман",
      tl: "Surah Ar-Rahman",
      th: "ซูรอาห์ อัรรஹ்மான்",
      id: "Surah Ar-Rahman",
      ja: "スーラ アル-ラフマーン",
      ko: "수라 알-라흐만",
      pl: "Surah Ar-Rahman",
      vi: "Surah Ar-Rahman",
      ta: "சூரா அர்ரஹ்மான்",
      ur: "سورۃ الرحمن",
      zh: "苏拉·拉赫曼",
    },
    surahNumber: 55,
    juzNumber: [27],
    totalAyah: 78,
  },
  {
    surahName: {
      ar: "سورة الواقعة",
      bn: "সুরা আল-ওয়াকিয়া",
      en: "Surah Al-Waqi'ah",
      hi: "सूरा अल-वाक़िआ",
      pt: "Surah Al-Waqi'ah",
      de: "Surah Al-Waqi'ah",
      fr: "Sourate Al-Waqi'ah",
      es: "Sura Al-Waqi'ah",
      tr: "Sure Al-Vakıa",
      it: "Sura Al-Waqi'ah",
      nl: "Soera Al-Waqi'ah",
      ru: "Сура Аль-Вакиа",
      tl: "Surah Al-Waqi'ah",
      th: "ซูเราะห์อันนัซม์",
      id: "Surah Al-Waqi'ah",
      ja: "スーラ アル-ワーキア",
      ko: "수라 알-와키아",
      pl: "Surah Al-Waqi'ah",
      vi: "Surah Al-Waqi'ah",
      ta: "சூரா அல-வாக்கியா",
      ur: "سورۃ الواقعہ",
      zh: "苏拉·阿尔-瓦基亚",
    },
    surahNumber: 56,
    juzNumber: [27],
    totalAyah: 96,
  },
  {
    surahName: {
      ar: "سورة الحديد",
      bn: "সুরা আল-হাদীদ",
      en: "Surah Al-Hadid",
      hi: "सूरा अल-हदीद",
      pt: "Surah Al-Hadid",
      de: "Surah Al-Hadid",
      fr: "Sourate Al-Hadid",
      es: "Sura Al-Hadid",
      tr: "Sure Al-Hadid",
      it: "Sura Al-Hadid",
      nl: "Soera Al-Hadid",
      ru: "Сура Аль-Хадид",
      tl: "Surah Al-Hadid",
      th: "ซูเราะห์อัลหะดีด",
      id: "Surah Al-Hadid",
      ja: "スーラ アル-ハディード",
      ko: "수라 알-하디드",
      pl: "Surah Al-Hadid",
      vi: "Surah Al-Hadid",
      ta: "சூரா அல-ஹதீத்",
      ur: "سورۃ الحديد",
      zh: "苏拉·阿尔-哈迪德",
    },
    surahNumber: 57,
    juzNumber: [27],
    totalAyah: 29,
  },
  {
    surahName: {
      ar: "سورة المجادلة",
      bn: "সুরা আল-মুজাদালা",
      en: "Surah Al-Mujadilah",
      hi: "सूरा अल-मुजादिला",
      pt: "Surah Al-Mujadilah",
      de: "Surah Al-Mujadilah",
      fr: "Sourate Al-Mujadilah",
      es: "Sura Al-Mujadilah",
      tr: "Sure Al-Mücadele",
      it: "Sura Al-Mujadilah",
      nl: "Soera Al-Moudjalilah",
      ru: "Сура Аль-Муджадила",
      tl: "Surah Al-Mujadilah",
      th: "ซูเราะห์ อัล-มุซาดาละฮ์",
      id: "Surah Al-Mujadilah",
      ja: "スーラ アル-ムジャーディラ",
      ko: "수라 알-무자딜라",
      pl: "Surah Al-Mujadilah",
      vi: "Surah Al-Mujadilah",
      ta: "சூரா அல-முஜாதிலா",
      ur: "سورۃ المجادلة",
      zh: "苏拉·阿尔-穆贾迪拉",
    },
    surahNumber: 58,
    juzNumber: [28],
    totalAyah: 22,
  },
  {
    surahName: {
      ar: "سورة الحشر",
      bn: "সুরা আল-হাশর",
      en: "Surah Al-Hashr",
      hi: "सूरा अल-हशर",
      pt: "Surah Al-Hashr",
      de: "Surah Al-Hashr",
      fr: "Sourate Al-Hashr",
      es: "Sura Al-Hashr",
      tr: "Sure Al-Haşr",
      it: "Sura Al-Hashr",
      nl: "Soera Al-Hasjr",
      ru: "Сура Аль-Хашр",
      tl: "Surah Al-Hashr",
      th: "ซูเราะห์ อัล-ฮะชร",
      id: "Surah Al-Hashr",
      ja: "スーラ アル-ハシュル",
      ko: "수라 알-하시르",
      pl: "Surah Al-Hashr",
      vi: "Surah Al-Hashr",
      ta: "சூரா அல-ஹஷ்ர்",
      ur: "سورۃ الحشر",
      zh: "苏拉·阿尔-哈什尔",
    },
    surahNumber: 59,
    juzNumber: [28],
    totalAyah: 24,
  },
  {
    surahName: {
      ar: "سورة الممتحنة",
      bn: "সুরা আল-মুমতাহিনা",
      en: "Surah Al-Mumtahanah",
      hi: "सूरा अल-मुम्तहना",
      pt: "Surah Al-Mumtahanah",
      de: "Surah Al-Mumtahanah",
      fr: "Sourate Al-Mumtahanah",
      es: "Sura Al-Mumtahanah",
      tr: "Sure Al-Mümtehine",
      it: "Sura Al-Mumtahanah",
      nl: "Soera Al-Mumtahanah",
      ru: "Сура Аль-Мумтахана",
      tl: "Surah Al-Mumtahanah",
      th: "ซูเราะห์อัลมุมตะฮินะ",
      id: "Surah Al-Mumtahanah",
      ja: "スーラ アル-ムムタハナ",
      ko: "수라 알-뭄타하나",
      pl: "Surah Al-Mumtahanah",
      vi: "Surah Al-Mumtahanah",
      ta: "சூரா அல-மும்தஹானா",
      ur: "سورۃ الممتحنة",
      zh: "苏拉·阿尔-穆姆塔哈纳",
    },
    surahNumber: 60,
    juzNumber: [28],
    totalAyah: 13,
  },
  {
    surahName: {
      ar: "سورة الصف",
      bn: "সুরা আস-সাফ",
      en: "Surah As-Saf",
      hi: "सूरा अस-सफ",
      pt: "Surah As-Saf",
      de: "Surah As-Saf",
      fr: "Sourate As-Saf",
      es: "Sura As-Saf",
      tr: "Sure Saf",
      it: "Sura As-Saf",
      nl: "Soera As-Saf",
      ru: "Сура Ас-Сафф",
      tl: "Surah As-Saf",
      th: "ซูรอาห์ อัศศ็อฟ",
      id: "Surah As-Saf",
      ja: "スーラ アッ-サフ",
      ko: "수라 앗-사프",
      pl: "Surah As-Saf",
      vi: "Surah As-Saf",
      ta: "சூரா அச்-சஃப்",
      ur: "سورۃ الصف",
      zh: "苏拉·萨夫",
    },
    surahNumber: 61,
    juzNumber: [28],
    totalAyah: 14,
  },
  {
    surahName: {
      ar: "سورة الجمعة",
      bn: "সুরা আল-জুমু'আহ",
      en: "Surah Al-Jumu'ah",
      hi: "सूरा अल-जुमुआह",
      pt: "Surah Al-Jumu'ah",
      de: "Surah Al-Jumu'ah",
      fr: "Sourate Al-Jumu'ah",
      es: "Sura Al-Jumu'ah",
      tr: "Sure Cuma",
      it: "Sura Al-Jumu'ah",
      nl: "Soera Al-Jumu'ah",
      ru: "Сура Аль-Джума",
      tl: "Surah Al-Jumu'ah",
      th: "ซูเราะห์อัลญุมอะห์",
      id: "Surah Al-Jumu'ah",
      ja: "スーラ アル-ジュムア",
      ko: "수라 알-주무아",
      pl: "Surah Al-Jumu'ah",
      vi: "Surah Al-Jumu'ah",
      ta: "சூரா அல்-ஜுமுஆ",
      ur: "سورۃ الجمعۃ",
      zh: "苏拉·聚礼",
    },
    surahNumber: 62,
    juzNumber: [28],
    totalAyah: 11,
  },
  {
    surahName: {
      ar: "سورة المنافقون",
      bn: "সুরা আল-মুনাফিকুন",
      en: "Surah Al-Munafiqun",
      hi: "सूरा अल-मुनाफिकून",
      pt: "Surah Al-Munafiqun",
      de: "Surah Al-Munafiqun",
      fr: "Sourate Al-Munafiqun",
      es: "Sura Al-Munafiqun",
      tr: "Sure Münafikun",
      it: "Sura Al-Munafiqun",
      nl: "Soera Al-Munafiqun",
      ru: "Сура Аль-Мунафикун",
      tl: "Surah Al-Munafiqun",
      th: "ซูรอาห์ อัลมุนาฟิกูน",
      id: "Surah Al-Munafiqun",
      ja: "スーラ アル-ムナーフィクーン",
      ko: "수라 알-무나피쿤",
      pl: "Surah Al-Munafiqun",
      vi: "Surah Al-Munafiqun",
      ta: "சூரா அல்-முனாபிகூன்",
      ur: "سورۃ المنافقون",
      zh: "苏拉·穆纳菲昆",
    },
    surahNumber: 63,
    juzNumber: [28],
    totalAyah: 11,
  },
  {
    surahName: {
      ar: "سورة التغابن",
      bn: "সুরা আত-তাগাবুন",
      en: "Surah At-Taghabun",
      hi: "सूरा अत-तगाबुन",
      pt: "Surah At-Taghabun",
      de: "Surah At-Taghabun",
      fr: "Sourate At-Taghabun",
      es: "Sura At-Taghabun",
      tr: "Sure Tegabun",
      it: "Sura At-Taghabun",
      nl: "Soera At-Taghabun",
      ru: "Сура Ат-Тагабун",
      tl: "Surah At-Taghabun",
      th: "ซูรอาห์ อัตตะฆอบุน",
      id: "Surah At-Taghabun",
      ja: "スーラ アット-タグハーブン",
      ko: "수라 앗-타가분",
      pl: "Surah At-Taghabun",
      vi: "Surah At-Taghabun",
      ta: "சூரா அத்-தகாபுன்",
      ur: "سورۃ التغابن",
      zh: "苏拉·塔加布恩",
    },
    surahNumber: 64,
    juzNumber: [28],
    totalAyah: 18,
  },
  {
    surahName: {
      ar: "سورة الطلاق",
      bn: "সুরা আত-তালাক",
      en: "Surah At-Talaq",
      hi: "सूरा अत-तलाक",
      pt: "Surah At-Talaq",
      de: "Surah At-Talaq",
      fr: "Sourate At-Talaq",
      es: "Sura At-Talaq",
      tr: "Sure Talak",
      it: "Sura At-Talaq",
      nl: "Soera At-Talaq",
      ru: "Сура Ат-Талак",
      tl: "Surah At-Talaq",
      th: "ซูเราะห์อัต-เฏาะลาก",
      id: "Surah At-Talaq",
      ja: "スーラ アット-タラク",
      ko: "수라 앗-탈라크",
      pl: "Surah At-Talaq",
      vi: "Surah At-Talaq",
      ta: "சூரா அல்-தலாக்",
      ur: "سورۃ الطلاق",
      zh: "苏拉·塔拉克",
    },
    surahNumber: 65,
    juzNumber: [28],
    totalAyah: 12,
  },
  {
    surahName: {
      ar: "سورة التحريم",
      bn: "সুরা আত-তাহরীম",
      en: "Surah At-Tahrim",
      hi: "सूरा अत-तहरीम",
      pt: "Surah At-Tahrim",
      de: "Surah At-Tahrim",
      fr: "Sourate At-Tahrim",
      es: "Sura At-Tahrim",
      tr: "Sure At-Tahrim",
      it: "Sura At-Tahrim",
      nl: "Soera At-Tahrim",
      ru: "Сура Ат-Тахрим",
      tl: "Surah At-Tahrim",
      th: "ซูเราะห์อัตตะห์รีม",
      id: "Surah At-Tahrim",
      ja: "スーラ アット-タフリーム",
      ko: "수라 앗-타흐림",
      pl: "Surah At-Tahrim",
      vi: "Surah At-Tahrim",
      ta: "சூரா அத்-தஹ்ரீம்",
      ur: "سورۃ التحريم",
      zh: "苏拉·阿特-塔赫里姆",
    },

    surahNumber: 66,
    juzNumber: [28],
    totalAyah: 12,
  },
  {
    surahName: {
      ar: "سورة الملك",
      bn: "সুরা আল-মুলক",
      en: "Surah Al-Mulk",
      hi: "सूरा अल-मुल्क",
      pt: "Surah Al-Mulk",
      de: "Surah Al-Mulk",
      fr: "Sourate Al-Mulk",
      es: "Sura Al-Mulk",
      tr: "Sure Al-Mülk",
      it: "Sura Al-Mulk",
      nl: "Soera Al-Mulk",
      ru: "Сура Аль-Мульк",
      tl: "Surah Al-Mulk",
      th: "ซูเราะห์ อัล-มุลก์",
      id: "Surah Al-Mulk",
      ja: "スーラ アル-ムルク",
      ko: "수라 알-물크",
      pl: "Surah Al-Mulk",
      vi: "Surah Al-Mulk",
      ta: "சூரா அல-முல்க்",
      ur: "سورۃ الملك",
      zh: "苏拉·阿尔-穆勒克",
    },
    surahNumber: 67,
    juzNumber: [29],
    totalAyah: 30,
  },
  {
    surahName: {
      ar: "سورة القلم",
      bn: "সুরা আল-কলম",
      en: "Surah Al-Qalam",
      hi: "सूरा अल-क़लम",
      pt: "Surah Al-Qalam",
      de: "Surah Al-Qalam",
      fr: "Sourate Al-Qalam",
      es: "Sura Al-Qalam",
      tr: "Sure Al-Kalem",
      it: "Sura Al-Qalam",
      nl: "Soera Al-Qalam",
      ru: "Сура Аль-Калям",
      tl: "Surah Al-Qalam",
      th: "ซูเราะห์อัลกะลาม",
      id: "Surah Al-Qalam",
      ja: "スーラ アル-カラム",
      ko: "수라 알-칼람",
      pl: "Surah Al-Qalam",
      vi: "Surah Al-Qalam",
      ta: "சூரா அல-கலம்",
      ur: "سورۃ القلم",
      zh: "苏拉·阿尔-卡拉姆",
    },
    surahNumber: 68,
    juzNumber: [29],
    totalAyah: 52,
  },
  {
    surahName: {
      ar: "سورة الحاقة",
      bn: "সুরা আল-হাক্কাহ",
      en: "Surah Al-Haqqah",
      hi: "सूरा अल-हक्का",
      pt: "Surah Al-Haqqah",
      de: "Surah Al-Haqqah",
      fr: "Sourate Al-Haqqah",
      es: "Sura Al-Haqqah",
      tr: "Sure Al-Hakka",
      it: "Sura Al-Haqqah",
      nl: "Soera Al-Haqqah",
      ru: "Сура Аль-Хакка",
      tl: "Surah Al-Haqqah",
      th: "ซูเราะห์ อัล-ฮักเกาะฮ์",
      id: "Surah Al-Haqqah",
      ja: "スーラ アル-ハッカ",
      ko: "수라 알-하카",
      pl: "Surah Al-Haqqah",
      vi: "Surah Al-Haqqah",
      ta: "சூரா அல-ஹாக்கா",
      ur: "سورۃ الحاقة",
      zh: "苏拉·阿尔-哈卡",
    },
    surahNumber: 69,
    juzNumber: [29],
    totalAyah: 52,
  },
  {
    surahName: {
      ar: "سورة المعارج",
      bn: "সুরা আল-মা'আরিজ",
      en: "Surah Al-Ma'arij",
      hi: "सूरा अल-मआरिज",
      pt: "Surah Al-Ma'arij",
      de: "Surah Al-Ma'arij",
      fr: "Sourate Al-Ma'arij",
      es: "Sura Al-Ma'arij",
      tr: "Sure Al-Mearic",
      it: "Sura Al-Ma'arij",
      nl: "Soera Al-Ma'arij",
      ru: "Сура Аль-Мааридж",
      tl: "Surah Al-Ma'arij",
      th: "ซูเราะห์อัลมาอาริจญ์",
      id: "Surah Al-Ma'arij",
      ja: "スーラ アル-マアーリジュ",
      ko: "수라 알-마아리즈",
      pl: "Surah Al-Ma'arij",
      vi: "Surah Al-Ma'arij",
      ta: "சூரா அல-மஆரிஜ்",
      ur: "سورۃ المعارج",
      zh: "苏拉·阿尔-玛阿里吉",
    },
    surahNumber: 70,
    juzNumber: [29],
    totalAyah: 44,
  },
  {
    surahName: {
      ar: "سورة نوح",
      bn: "সুরা নূহ",
      en: "Surah Nuh",
      hi: "सूरा नूह",
      pt: "Surah Nuh",
      de: "Surah Nuh",
      fr: "Sourate Nuh",
      es: "Sura Nuh",
      tr: "Sure Nuh",
      it: "Sura Nuh",
      nl: "Soera Nuh",
      ru: "Сура Нух",
      tl: "Surah Nuh",
      th: "ซูรอาห์ นุห์",
      id: "Surah Nuh",
      ja: "スーラ ヌーフ",
      ko: "수라 누흐",
      pl: "Surah Nuh",
      vi: "Surah Nuh",
      ta: "சூரா நூஹ்",
      ur: "سورۃ نوح",
      zh: "苏拉·努哈",
    },
    surahNumber: 71,
    juzNumber: [29],
    totalAyah: 28,
  },
  {
    surahName: {
      ar: "سورة الجن",
      bn: "সুরা আল-জিন",
      en: "Surah Al-Jinn",
      hi: "सूरा अल-जिन्न",
      pt: "Surah Al-Jinn",
      de: "Surah Al-Jinn",
      fr: "Sourate Al-Jinn",
      es: "Sura Al-Jinn",
      tr: "Sure Cin",
      it: "Sura Al-Jinn",
      nl: "Soera Al-Jinn",
      ru: "Сура Аль-Джинн",
      tl: "Surah Al-Jinn",
      th: "ซูรอาห์ อัลญิน",
      id: "Surah Al-Jinn",
      ja: "スーラ アル・ジン",
      ko: "수라 알-진",
      pl: "Surah Al-Jinn",
      vi: "Surah Al-Jinn",
      ta: "சூரா அல்-ஜின்",
      ur: "سورۃ الجن",
      zh: "苏拉·精灵",
    },
    surahNumber: 72,
    juzNumber: [29],
    totalAyah: 28,
  },
  {
    surahName: {
      ar: "سورة المزمل",
      bn: "সুরা আল-মুযযাম্মিল",
      en: "Surah Al-Muzzammil",
      hi: "सूरा अल-मुज़्जम्मिल",
      pt: "Surah Al-Muzzammil",
      de: "Surah Al-Muzzammil",
      fr: "Sourate Al-Muzzammil",
      es: "Sura Al-Muzzammil",
      tr: "Sure Müzzemmil",
      it: "Sura Al-Muzzammil",
      nl: "Soera Al-Muzzammil",
      ru: "Сура Аль-Муззаммиль",
      tl: "Surah Al-Muzzammil",
      th: "ซูรอาห์ อัลมุซซัมมิล",
      id: "Surah Al-Muzzammil",
      ja: "スーラ アル・ムッザンミル",
      ko: "수라 알-무잠밀",
      pl: "Surah Al-Muzzammil",
      vi: "Surah Al-Muzzammil",
      ta: "சூரா அல்-முஸம்மில்",
      ur: "سورۃ المزمل",
      zh: "苏拉·穆扎米勒",
    },
    surahNumber: 73,
    juzNumber: [29],
    totalAyah: 20,
  },
  {
    surahName: {
      ar: "سورة المدثر",
      bn: "সুরা আল-মুদ্দাসসির",
      en: "Surah Al-Muddaththir",
      hi: "सूरा अल-मुद्दस्सिर",
      pt: "Surah Al-Muddaththir",
      de: "Surah Al-Muddaththir",
      fr: "Sourate Al-Muddaththir",
      es: "Sura Al-Muddaththir",
      tr: "Sure Müddessir",
      it: "Sura Al-Muddaththir",
      nl: "Soera Al-Muddaththir",
      ru: "Сура Аль-Муддассир",
      tl: "Surah Al-Muddaththir",
      th: "ซูรอาห์ อัลมุดดัษษิร",
      id: "Surah Al-Muddaththir",
      ja: "スーラ アル・ムッダッスィル",
      ko: "수라 알-무닷디르",
      pl: "Surah Al-Muddaththir",
      vi: "Surah Al-Muddaththir",
      ta: "சூரா அல்-முத்தத்திர்",
      ur: "سورۃ المدثر",
      zh: "苏拉·穆达斯西尔",
    },
    surahNumber: 74,
    juzNumber: [29],
    totalAyah: 56,
  },
  {
    surahName: {
      ar: "سورة القيامة",
      bn: "সুরা আল-কিয়ামাহ",
      en: "Surah Al-Qiyamah",
      hi: "सूरा अल-क़ियामा",
      pt: "Surah Al-Qiyamah",
      de: "Surah Al-Qiyamah",
      fr: "Sourate Al-Qiyamah",
      es: "Sura Al-Qiyamah",
      tr: "Sure Kıyamet",
      it: "Sura Al-Qiyamah",
      nl: "Soera Al-Qiyamah",
      ru: "Сура Аль-Кийама",
      tl: "Surah Al-Qiyamah",
      th: "ซูรอาห์ อัลกิยามะห์",
      id: "Surah Al-Qiyamah",
      ja: "スーラ アル・キヤーマ",
      ko: "수라 알-키야마",
      pl: "Surah Al-Qiyamah",
      vi: "Surah Al-Qiyamah",
      ta: "சூரா அல்-கியாமா",
      ur: "سورۃ القیامۃ",
      zh: "苏拉·复活",
    },
    surahNumber: 75,
    juzNumber: [29],
    totalAyah: 40,
  },
  {
    surahName: {
      ar: "سورة الإنسان",
      bn: "সুরা আল-ইনসান",
      en: "Surah Al-Insan",
      hi: "सूरा अल-इंसान",
      pt: "Surah Al-Insan",
      de: "Surah Al-Insan",
      fr: "Sourate Al-Insan",
      es: "Sura Al-Insan",
      tr: "Sure Al-İnsan",
      it: "Sura Al-Insan",
      nl: "Soera Al-Insan",
      ru: "Сура Аль-Инсан",
      tl: "Surah Al-Insan",
      th: "ซูรอาห์ อัล-อินসาน",
      id: "Surah Al-Insan",
      ja: "スーラ アル-インサーン",
      ko: "수라 알-인산",
      pl: "Surah Al-Insan",
      vi: "Surah Al-Insan",
      ta: "சூரா அல-இன்சான்",
      ur: "سورۃ الإنسان",
      zh: "苏拉·阿尔-因桑",
    },
    surahNumber: 76,
    juzNumber: [29],
    totalAyah: 31,
  },
  {
    surahName: {
      ar: "سورة المرسلات",
      bn: "সুরা আল-মুরসালাত",
      en: "Surah Al-Mursalat",
      hi: "सूरा अल-मुरसलात",
      pt: "Surah Al-Mursalat",
      de: "Surah Al-Mursalat",
      fr: "Sourate Al-Mursalat",
      es: "Sura Al-Mursalat",
      tr: "Sure Al-Murselat",
      it: "Sura Al-Mursalat",
      nl: "Soera Al-Mursalat",
      ru: "Сура Аль-Мурсалят",
      tl: "Surah Al-Mursalat",
      th: "ซูเราะห์ อัล-มุรศอลาต",
      id: "Surah Al-Mursalat",
      ja: "スーラ アル-ムルサラート",
      ko: "수라 알-무르살라트",
      pl: "Surah Al-Mursalat",
      vi: "Surah Al-Mursalat",
      ta: "சூரா அல-முர்சலாத்",
      ur: "سورۃ المرسلات",
      zh: "苏拉·阿尔-穆尔萨拉特",
    },
    surahNumber: 77,
    juzNumber: [29],
    totalAyah: 50,
  },
  {
    surahName: {
      ar: "سورة النبأ",
      bn: "সুরা আন-নাবা",
      en: "Surah An-Naba",
      hi: "सूरा अन-नबा",
      pt: "Surah An-Naba",
      de: "Surah An-Naba",
      fr: "Sourate An-Naba",
      es: "Sura An-Naba",
      tr: "Sure An-Nebe",
      it: "Sura An-Naba",
      nl: "Soera An-Naba",
      ru: "Сура Ан-Наба",
      tl: "Surah An-Naba",
      th: "ซูเราะห์อันนะบะฮฺ",
      id: "Surah An-Naba",
      ja: "スーラ アン-ナバー",
      ko: "수라 안-나바",
      pl: "Surah An-Naba",
      vi: "Surah An-Naba",
      ta: "சூரா அன்-நபா",
      ur: "سورۃ النبأ",
      zh: "苏拉·安-纳巴",
    },

    surahNumber: 78,
    juzNumber: [30],
    totalAyah: 40,
  },
  {
    surahName: {
      ar: "سورة النازعات",
      bn: "সুরা আন-নাজিআ'ত",
      en: "Surah An-Nazi'at",
      hi: "सूरा अन-नाज़िआत",
      pt: "Surah An-Nazi'at",
      de: "Surah An-Nazi'at",
      fr: "Sourate An-Nazi'at",
      es: "Sura An-Nazi'at",
      tr: "Sure An-Nazi'at",
      it: "Sura An-Nazi'at",
      nl: "Soera An-Nazi'at",
      ru: "Сура Ан-Нази'ат",
      tl: "Surah An-Nazi'at",
      th: "ซูเราะห์อัน-นาซีอาต",
      id: "Surah An-Nazi'at",
      ja: "スーラ アン-ナージィアート",
      ko: "수라 안-나지앗",
      pl: "Surah An-Nazi'at",
      vi: "Surah An-Nazi'at",
      ta: "சூரா அன்-நாஸிஆத்",
      ur: "سورۃ النازعات",
      zh: "苏拉·安-纳齐亚特",
    },
    surahNumber: 79,
    juzNumber: [30],
    totalAyah: 45,
  },
  {
    surahName: {
      ar: "سورة عبس",
      bn: "সুরা আবাসা",
      en: "Surah 'Abasa",
      hi: "सूरा अबसा",
      pt: "Surah 'Abasa",
      de: "Surah 'Abasa",
      fr: "Sourate 'Abasa",
      es: "Sura 'Abasa",
      tr: "Sure Abese",
      it: "Sura 'Abasa",
      nl: "Soera 'Abasa",
      ru: "Сура Абаса",
      tl: "Surah 'Abasa",
      th: "ซูเราะห์อะบาสะ",
      id: "Surah 'Abasa",
      ja: "スーラ アバサ",
      ko: "수라 아바사",
      pl: "Surah 'Abasa",
      vi: "Surah 'Abasa",
      ta: "சூரா அபஸா",
      ur: "سورۃ عبس",
      zh: "苏拉·阿巴萨",
    },
    surahNumber: 80,
    juzNumber: [30],
    totalAyah: 42,
  },
  {
    surahName: {
      ar: "سورة التكوير",
      bn: "সুরা আত-তাকভীর",
      en: "Surah At-Takwir",
      hi: "सूरा अत-तकवीर",
      pt: "Surah At-Takwir",
      de: "Surah At-Takwir",
      fr: "Sourate At-Takwir",
      es: "Sura At-Takwir",
      tr: "Sure Tekvir",
      it: "Sura At-Takwir",
      nl: "Soera At-Takwir",
      ru: "Сура Ат-Таквир",
      tl: "Surah At-Takwir",
      th: "ซูรอาห์ อัตตักวีร์",
      id: "Surah At-Takwir",
      ja: "スーラ アッタクウィール",
      ko: "수라 앗-타크위르",
      pl: "Surah At-Takwir",
      vi: "Surah At-Takwir",
      ta: "சூரா அத்-தகவீர்",
      ur: "سورۃ التکویر",
      zh: "苏拉·包裹",
    },
    surahNumber: 81,
    juzNumber: [30],
    totalAyah: 29,
  },
  {
    surahName: {
      ar: "سورة الإنفطار",
      bn: "সুরা আল-ইনফিতার",
      en: "Surah Al-Infitar",
      hi: "सूरा अल-इंफितार",
      pt: "Surah Al-Infitar",
      de: "Surah Al-Infitar",
      fr: "Sourate Al-Infitar",
      es: "Sura Al-Infitar",
      tr: "Sure İnfitâr",
      it: "Sura Al-Infitar",
      nl: "Soera Al-Infitar",
      ru: "Сура Аль-Инфитар",
      tl: "Surah Al-Infitar",
      th: "ซูรอาห์ อัลอินฟิทาร",
      id: "Surah Al-Infitar",
      ja: "スーラ アル・インフィター",
      ko: "수라 알-인피타르",
      pl: "Surah Al-Infitar",
      vi: "Surah Al-Infitar",
      ta: "சூரா அல்-இன்ஃபிதார்",
      ur: "سورۃ الإنفطار",
      zh: "苏拉·破裂",
    },
    surahNumber: 82,
    juzNumber: [30],
    totalAyah: 19,
  },
  {
    surahName: {
      ar: "سورة المطففين",
      bn: "সুরা আল-মুতাফফিফিন",
      en: "Surah Al-Mutaffifin",
      hi: "सूरा अल-मुतफ़्फ़िफ़ीन",
      pt: "Surah Al-Mutaffifin",
      de: "Surah Al-Mutaffifin",
      fr: "Sourate Al-Mutaffifin",
      es: "Sura Al-Mutaffifin",
      tr: "Sure Mutaffifin",
      it: "Sura Al-Mutaffifin",
      nl: "Soera Al-Mutaffifin",
      ru: "Сура Аль-Мутаффифин",
      tl: "Surah Al-Mutaffifin",
      th: "ซูรอาห์ อัลมุตตัฟฟิฟีน",
      id: "Surah Al-Mutaffifin",
      ja: "スーラ アル・ムタッフィフィン",
      ko: "수라 알-무타피핀",
      pl: "Surah Al-Mutaffifin",
      vi: "Surah Al-Mutaffifin",
      ta: "சூரா அல்-முதஃப்பிபீன்",
      ur: "سورۃ المطففین",
      zh: "苏拉·欺诈者",
    },
    surahNumber: 83,
    juzNumber: [30],
    totalAyah: 36,
  },
  {
    surahName: {
      ar: "سورة الإنشقاق",
      bn: "সুরা আল-ইনশিকাক",
      en: "Surah Al-Inshiqaq",
      hi: "सूरा अल-इंशिक़ाक़",
      pt: "Surah Al-Inshiqaq",
      de: "Surah Al-Inshiqaq",
      fr: "Sourate Al-Inshiqaq",
      es: "Sura Al-Inshiqaq",
      tr: "Sure İnşikak",
      it: "Sura Al-Inshiqaq",
      nl: "Soera Al-Inshiqaq",
      ru: "Сура Аль-Иншикак",
      tl: "Surah Al-Inshiqaq",
      th: "ซูรอาห์ อัลอินชิก๊อก",
      id: "Surah Al-Inshiqaq",
      ja: "スーラ アル・インシカーク",
      ko: "수라 알-인쉬카크",
      pl: "Surah Al-Inshiqaq",
      vi: "Surah Al-Inshiqaq",
      ta: "சூரா அல்-இன்ஷிகாக்",
      ur: "سورۃ الإنشقاق",
      zh: "苏拉·裂开",
    },
    surahNumber: 84,
    juzNumber: [30],
    totalAyah: 25,
  },
  {
    surahName: {
      ar: "سورة البروج",
      bn: "সুরা আল-বুরুজ",
      en: "Surah Al-Buruj",
      hi: "सूरा अल-बुरूज",
      pt: "Surah Al-Buruj",
      de: "Surah Al-Buruj",
      fr: "Sourate Al-Buruj",
      es: "Sura Al-Buruj",
      tr: "Sure Bürûc",
      it: "Sura Al-Buruj",
      nl: "Soera Al-Buruj",
      ru: "Сура Аль-Бурудж",
      tl: "Surah Al-Buruj",
      th: "ซูเราะห์อัลบุรุจ",
      id: "Surah Al-Buruj",
      ja: "スーラ アル・ブルージ",
      ko: "수라 알-부루즈",
      pl: "Surah Al-Buruj",
      vi: "Surah Al-Buruj",
      ta: "சூரா அல்-புரூஜ்",
      ur: "سورۃ البروج",
      zh: "苏拉·星座",
    },
    surahNumber: 85,
    juzNumber: [30],
    totalAyah: 22,
  },
  {
    surahName: {
      ar: "سورة الطارق",
      bn: "সুরা আত-তারিক",
      en: "Surah At-Tariq",
      hi: "सूरा अत-तारिक",
      pt: "Surah At-Tariq",
      de: "Surah At-Tariq",
      fr: "Sourate At-Tariq",
      es: "Sura At-Tariq",
      tr: "Sure At-Tarik",
      it: "Sura At-Tariq",
      nl: "Soera At-Tariq",
      ru: "Сура Ат-Тарик",
      tl: "Surah At-Tariq",
      th: "ซูเราะห์อัตตาริก",
      id: "Surah At-Tariq",
      ja: "スーラ アット-ターリク",
      ko: "수라 앗-타리크",
      pl: "Surah At-Tariq",
      vi: "Surah At-Tariq",
      ta: "சூரா அத்-தாரிக்",
      ur: "سورۃ الطارق",
      zh: "苏拉·阿特-塔里克",
    },
    surahNumber: 86,
    juzNumber: [30],
    totalAyah: 17,
  },
  {
    surahName: {
      ar: "سورة الأعلى",
      bn: "সুরা আল-আ'লা",
      en: "Surah Al-A'la",
      hi: "सूरा अल-आला",
      pt: "Surah Al-A'la",
      de: "Surah Al-A'la",
      fr: "Sourate Al-A'la",
      es: "Sura Al-A'la",
      tr: "Sure Al-A'la",
      it: "Sura Al-A'la",
      nl: "Soera Al-A'la",
      ru: "Сура Аль-А'ля",
      tl: "Surah Al-A'la",
      th: "ซูเราะห์อัลอะลา",
      id: "Surah Al-A'la",
      ja: "スーラ アル-アアラー",
      ko: "수라 알-알라",
      pl: "Surah Al-A'la",
      vi: "Surah Al-A'la",
      ta: "சூரா அல-அஅ்லா",
      ur: "سورۃ الأعلى",
      zh: "苏拉·阿尔-阿拉",
    },
    surahNumber: 87,
    juzNumber: [30],
    totalAyah: 19,
  },
  {
    surahName: {
      ar: "سورة الغاشية",
      bn: "সুরা আল-গাশিয়াহ",
      en: "Surah Al-Ghashiyah",
      hi: "सूरा अल-गाशियाह",
      pt: "Surah Al-Ghashiyah",
      de: "Surah Al-Ghashiyah",
      fr: "Sourate Al-Ghashiyah",
      es: "Sura Al-Ghashiyah",
      tr: "Sure Al-Gaşiye",
      it: "Sura Al-Ghashiyah",
      nl: "Soera Al-Ghashiyah",
      ru: "Сура Аль-Гашийа",
      tl: "Surah Al-Ghashiyah",
      th: "ซูเราะห์ อัล-กาชียะฮ์",
      id: "Surah Al-Ghashiyah",
      ja: "スーラ アル-ガーシヤ",
      ko: "수라 알-가시야",
      pl: "Surah Al-Ghashiyah",
      vi: "Surah Al-Ghashiyah",
      ta: "சூரா அல-காஷியா",
      ur: "سورۃ الغاشية",
      zh: "苏拉·阿尔-盖舍耶",
    },
    surahNumber: 88,
    juzNumber: [30],
    totalAyah: 26,
  },
  {
    surahName: {
      ar: "سورة الفجر",
      bn: "সুরা আল-ফাজর",
      en: "Surah Al-Fajr",
      hi: "सूरा अल-फज्र",
      pt: "Surah Al-Fajr",
      de: "Surah Al-Fajr",
      fr: "Sourate Al-Fajr",
      es: "Sura Al-Fajr",
      tr: "Sure Al-Fecr",
      it: "Sura Al-Fajr",
      nl: "Soera Al-Fajr",
      ru: "Сура Аль-Фаджр",
      tl: "Surah Al-Fajr",
      th: "ซูเราะห์อัลฟัจริ",
      id: "Surah Al-Fajr",
      ja: "スーラ アル-ファジュル",
      ko: "수라 알-파즈르",
      pl: "Surah Al-Fajr",
      vi: "Surah Al-Fajr",
      ta: "சூரா அல-ஃபஜ்ர்",
      ur: "سورۃ الفجر",
      zh: "苏拉·阿尔-法吉尔",
    },

    surahNumber: 89,
    juzNumber: [30],
    totalAyah: 30,
  },
  {
    surahName: {
      ar: "سورة البلد",
      bn: "সুরা আল-বালাদ",
      en: "Surah Al-Balad",
      hi: "सूरा अल-बलद",
      pt: "Surah Al-Balad",
      de: "Surah Al-Balad",
      fr: "Sourate Al-Balad",
      es: "Sura Al-Balad",
      tr: "Sure Al-Beled",
      it: "Sura Al-Balad",
      nl: "Soera Al-Balad",
      ru: "Сура Аль-Балад",
      tl: "Surah Al-Balad",
      th: "ซูเราะห์ อัล-บะลาด",
      id: "Surah Al-Balad",
      ja: "スーラ アル-バラド",
      ko: "수라 알-발라드",
      pl: "Surah Al-Balad",
      vi: "Surah Al-Balad",
      ta: "சூரா அல-பலத்",
      ur: "سورۃ البلد",
      zh: "苏拉·阿尔-巴拉德",
    },
    surahNumber: 90,
    juzNumber: [30],
    totalAyah: 20,
  },
  {
    surahName: {
      ar: "سورة الشمس",
      bn: "সুরা আশ-শামস",
      en: "Surah Ash-Shams",
      hi: "सूरा अश-शम्स",
      pt: "Surah Ash-Shams",
      de: "Surah Ash-Shams",
      fr: "Sourate Ash-Shams",
      es: "Sura Ash-Shams",
      tr: "Sure Şems",
      it: "Sura Ash-Shams",
      nl: "Soera Ash-Shams",
      ru: "Сура Аш-Шамс",
      tl: "Surah Ash-Shams",
      th: "ซูรอาห์ อัชชัมส์",
      id: "Surah Ash-Shams",
      ja: "スーラ アッシュシャムス",
      ko: "수라 아쉬-샴스",
      pl: "Surah Ash-Shams",
      vi: "Surah Ash-Shams",
      ta: "சூரா அஷ்ஷம்ஸ்",
      ur: "سورۃ الشمس",
      zh: "苏拉·太阳",
    },
    surahNumber: 91,
    juzNumber: [30],
    totalAyah: 15,
  },
  {
    surahName: {
      ar: "سورة الليل",
      bn: "সুরা আল-লাইল",
      en: "Surah Al-Layl",
      hi: "सूरा अल-लैल",
      pt: "Surah Al-Layl",
      de: "Surah Al-Layl",
      fr: "Sourate Al-Layl",
      es: "Sura Al-Layl",
      tr: "Sure Leyl",
      it: "Sura Al-Layl",
      nl: "Soera Al-Layl",
      ru: "Сура Аль-Лайл",
      tl: "Surah Al-Layl",
      th: "ซูรอาห์ อัลลัยล์",
      id: "Surah Al-Layl",
      ja: "スーラ アル・レイル",
      ko: "수라 알-라일",
      pl: "Surah Al-Layl",
      vi: "Surah Al-Layl",
      ta: "சூரா அல்-லைல்",
      ur: "سورۃ اللیل",
      zh: "苏拉·夜晚",
    },
    surahNumber: 92,
    juzNumber: [30],
    totalAyah: 21,
  },
  {
    surahName: {
      ar: "سورة الضحى",
      bn: "সুরা আদ-দুহা",
      en: "Surah Ad-Duhaa",
      hi: "सूरा अद-दुहा",
      pt: "Surah Ad-Duhaa",
      de: "Surah Ad-Duhaa",
      fr: "Sourate Ad-Duhaa",
      es: "Sura Ad-Duhaa",
      tr: "Sure Duha",
      it: "Sura Ad-Duhaa",
      nl: "Soera Ad-Duhaa",
      ru: "Сура Ад-Духа",
      tl: "Surah Ad-Duhaa",
      th: "ซูรอาห์ อัด-ฎุฮา",
      id: "Surah Ad-Duhaa",
      ja: "スーラ アッド・ドゥハー",
      ko: "수라 아드-두하",
      pl: "Surah Ad-Duhaa",
      vi: "Surah Ad-Duhaa",
      ta: "சூரா அத்-துஹா",
      ur: "سورۃ الضحیٰ",
      zh: "苏拉·早晨",
    },
    surahNumber: 93,
    juzNumber: [30],
    totalAyah: 11,
  },
  {
    surahName: {
      ar: "سورة الإنشراح",
      bn: "সুরা আল-ইনশিরাহ",
      en: "Surah Al-Inshirah",
      hi: "सूरा अल-इंशिराह",
      pt: "Surah Al-Inshirah",
      de: "Surah Al-Inshirah",
      fr: "Sourate Al-Inshirah",
      es: "Sura Al-Inshirah",
      tr: "Sure İnşirah",
      it: "Sura Al-Inshirah",
      nl: "Soera Al-Inshirah",
      ru: "Сура Аль-Инширах",
      tl: "Surah Al-Inshirah",
      th: "ซูเราะห์ อัล-อินชีเราะห์",
      id: "Surah Al-Inshirah",
      ja: "スーラ アル・インシラー",
      ko: "수라 알-인쉬라흐",
      pl: "Surah Al-Inshirah",
      vi: "Surah Al-Inshirah",
      ta: "சூரா அல்-இன்ஷிராஹ்",
      ur: "سورۃ الإنشراح",
      zh: "苏拉·宽慰",
    },
    surahNumber: 94,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: {
      ar: "سورة التين",
      bn: "সুরা আত-তিন",
      en: "Surah At-Tin",
      hi: "सूरा अत-तीन",
      pt: "Surah At-Tin",
      de: "Surah At-Tin",
      fr: "Sourate At-Tin",
      es: "Sura At-Tin",
      tr: "Sure Tin",
      it: "Sura At-Tin",
      nl: "Soera At-Tin",
      ru: "Сура Ат-Тин",
      tl: "Surah At-Tin",
      th: "ซูรอาห์ อัตตีน",
      id: "Surah At-Tin",
      ja: "スーラ アット・ティン",
      ko: "수라 앗-틴",
      pl: "Surah At-Tin",
      vi: "Surah At-Tin",
      ta: "சூரா அத்-தீன்",
      ur: "سورۃ التین",
      zh: "苏拉·无花果",
    },
    surahNumber: 95,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: {
      ar: "سورة العلق",
      bn: "সুরা আল-আলাক",
      en: "Surah Al-'Alaq",
      hi: "सूरा अल-अलक़",
      pt: "Surah Al-'Alaq",
      de: "Surah Al-'Alaq",
      fr: "Sourate Al-'Alaq",
      es: "Sura Al-'Alaq",
      tr: "Sure Al-Alak",
      it: "Sura Al-'Alaq",
      nl: "Soera Al-'Alaq",
      ru: "Сура Аль-Алак",
      tl: "Surah Al-'Alaq",
      th: "ซูเราะห์อัลอะลัก",
      id: "Surah Al-'Alaq",
      ja: "スーラ アル-アラク",
      ko: "수라 알-알라크",
      pl: "Surah Al-'Alaq",
      vi: "Surah Al-'Alaq",
      ta: "சூரா அல்அலக்",
      ur: "سورۃ العلق",
      zh: "苏拉·阿尔-阿拉克",
    },
    surahNumber: 96,
    juzNumber: [30],
    totalAyah: 19,
  },
  {
    surahName: {
      ar: "سورة القدر",
      bn: "সুরা আল-কদর",
      en: "Surah Al-Qadr",
      hi: "सूरा अल-क़द्र",
      pt: "Surah Al-Qadr",
      de: "Surah Al-Qadr",
      fr: "Sourate Al-Qadr",
      es: "Sura Al-Qadr",
      tr: "Sure Al-Kadr",
      it: "Sura Al-Qadr",
      nl: "Soera Al-Qadr",
      ru: "Сура Аль-Кадр",
      tl: "Surah Al-Qadr",
      th: "ซูเราะห์อัลก็อดร์",
      id: "Surah Al-Qadr",
      ja: "スーラ アル-カドル",
      ko: "수라 알-카드르",
      pl: "Surah Al-Qadr",
      vi: "Surah Al-Qadr",
      ta: "சூரா அல்கத்ர்",
      ur: "سورۃ القدر",
      zh: "苏拉·阿尔-卡德尔",
    },
    surahNumber: 97,
    juzNumber: [30],
    totalAyah: 5,
  },
  {
    surahName: {
      ar: "سورة البينة",
      bn: "সুরা আল-বাইয়্যিনাহ",
      en: "Surah Al-Bayyinah",
      hi: "सूरा अल-बय्यिनाह",
      pt: "Surah Al-Bayyinah",
      de: "Surah Al-Bayyinah",
      fr: "Sourate Al-Bayyinah",
      es: "Sura Al-Bayyinah",
      tr: "Sure Al-Beyyine",
      it: "Sura Al-Bayyinah",
      nl: "Soera Al-Bayyinah",
      ru: "Сура Аль-Баййина",
      tl: "Surah Al-Bayyinah",
      th: "ซูเราะห์อัลบัยยินาห์",
      id: "Surah Al-Bayyinah",
      ja: "スーラ アル-バイイナ",
      ko: "수라 알-바이야나",
      pl: "Surah Al-Bayyinah",
      vi: "Surah Al-Bayyinah",
      ta: "சூரா அல்பய்யினா",
      ur: "سورۃ البينة",
      zh: "苏拉·阿尔-拜因纳",
    },
    surahNumber: 98,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: {
      ar: "سورة الزلزلة",
      bn: "সুরা আজ-যালযালাহ",
      en: "Surah Az-Zalzalah",
      hi: "सूरा अज़-ज़लज़लाह",
      pt: "Surah Az-Zalzalah",
      de: "Surah Az-Zalzalah",
      fr: "Sourate Az-Zalzalah",
      es: "Sura Az-Zalzalah",
      tr: "Sure Az-Zilzal",
      it: "Sura Az-Zalzalah",
      nl: "Soera Az-Zalzalah",
      ru: "Сура Аз-Залзала",
      tl: "Surah Az-Zalzalah",
      th: "ซูเราะห์ อัซ-ญาลาละห์",
      id: "Surah Az-Zalzalah",
      ja: "スーラ アズ-ザルザラ",
      ko: "수라 앗-잘잘라",
      pl: "Surah Az-Zalzalah",
      vi: "Surah Az-Zalzalah",
      ta: "சூரா அஸ்-சல்சலா",
      ur: "سورۃ الزلزلة",
      zh: "苏拉·阿兹-扎尔扎拉",
    },
    surahNumber: 99,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: {
      ar: "سورة العاديات",
      bn: "সুরা আল-আদিয়াত",
      en: "Surah Al-'Adiyat",
      hi: "सूरा अल-आदियात",
      pt: "Surah Al-'Adiyat",
      de: "Surah Al-'Adiyat",
      fr: "Sourate Al-'Adiyat",
      es: "Sura Al-'Adiyat",
      tr: "Sure Al-Adiyat",
      it: "Sura Al-'Adiyat",
      nl: "Soera Al-'Adiyat",
      ru: "Сура Аль-Адийат",
      tl: "Surah Al-'Adiyat",
      th: "ซูเราะห์อัลอาดิยัต",
      id: "Surah Al-'Adiyat",
      ja: "スーラ アル-アーディヤート",
      ko: "수라 알-아디야트",
      pl: "Surah Al-'Adiyat",
      vi: "Surah Al-'Adiyat",
      ta: "சூரா அல்அதியாத்",
      ur: "سورۃ العاديات",
      zh: "苏拉·阿尔-阿迪亚特",
    },
    surahNumber: 100,
    juzNumber: [30],
    totalAyah: 11,
  },
  {
    surahName: {
      ar: "سورة القارعة",
      bn: "সুরা আল-কারিয়া",
      en: "Surah Al-Qari'ah",
      hi: "सूरा अल-कारिआ",
      pt: "Surah Al-Qari'ah",
      de: "Surah Al-Qari'ah",
      fr: "Sourate Al-Qari'ah",
      es: "Sura Al-Qari'ah",
      tr: "Sure Karia",
      it: "Sura Al-Qari'ah",
      nl: "Soera Al-Qari'ah",
      ru: "Сура Аль-Кариа",
      tl: "Surah Al-Qari'ah",
      th: "ซูรอาห์ อัลกอรียะห์",
      id: "Surah Al-Qari'ah",
      ja: "スーラ アル・カリア",
      ko: "수라 알-까리아",
      pl: "Surah Al-Qari'ah",
      vi: "Surah Al-Qari'ah",
      ta: "சூரா அல்காரிஅ",
      ur: "سورۃ القارعة",
      zh: "苏拉·大灾难",
    },
    surahNumber: 101,
    juzNumber: [30],
    totalAyah: 11,
  },
  {
    surahName: {
      ar: "سورة التكاثر",
      bn: "সুরা আত-তাকাসুর",
      en: "Surah At-Takathur",
      hi: "सूरा अत-तकासुर",
      pt: "Surah At-Takathur",
      de: "Surah At-Takathur",
      fr: "Sourate At-Takathur",
      es: "Sura At-Takathur",
      tr: "Sure Tekasür",
      it: "Sura At-Takathur",
      nl: "Soera At-Takathur",
      ru: "Сура Ат-Такатхур",
      tl: "Surah At-Takathur",
      th: "ซูรอาห์ อัตตะกาษูร",
      id: "Surah At-Takathur",
      ja: "スーラ アット・タカスル",
      ko: "수라 앗-타카투르",
      pl: "Surah At-Takathur",
      vi: "Surah At-Takathur",
      ta: "சூரா அத்-தகாஸுர்",
      ur: "سورۃ التكاثر",
      zh: "苏拉·竞赛",
    },
    surahNumber: 102,
    juzNumber: [30],
    totalAyah: 8,
  },
  {
    surahName: {
      ar: "سورة العصر",
      bn: "সুরা আল-আসর",
      en: "Surah Al-'Asr",
      hi: "सूरा अल-असर",
      pt: "Surah Al-'Asr",
      de: "Surah Al-'Asr",
      fr: "Sourate Al-'Asr",
      es: "Sura Al-'Asr",
      tr: "Sure Asr",
      it: "Sura Al-'Asr",
      nl: "Soera Al-'Asr",
      ru: "Сура Аль-Аср",
      tl: "Surah Al-'Asr",
      th: "ซูเราะห์อัลอัศร",
      id: "Surah Al-'Asr",
      ja: "スーラ アル・アスル",
      ko: "수라 알-아스르",
      pl: "Surah Al-'Asr",
      vi: "Surah Al-'Asr",
      ta: "சூரா அல்-அஸ்ர்",
      ur: "سورۃ العصر",
      zh: "苏拉·时间",
    },
    surahNumber: 103,
    juzNumber: [30],
    totalAyah: 3,
  },
  {
    surahName: {
      ar: "سورة الهمزة",
      bn: "সুরা আল-হুমাজাহ",
      en: "Surah Al-Humazah",
      hi: "सूरा अल-हुमज़ा",
      pt: "Surah Al-Humazah",
      de: "Surah Al-Humazah",
      fr: "Sourate Al-Humazah",
      es: "Sura Al-Humazah",
      tr: "Sure Hümeze",
      it: "Sura Al-Humazah",
      nl: "Soera Al-Humazah",
      ru: "Сура Аль-Хумаза",
      tl: "Surah Al-Humazah",
      th: "ซูเราะห์อัลฮุมาซะห์",
      id: "Surah Al-Humazah",
      ja: "スーラ アル・フマザ",
      ko: "수라 알-후마자",
      pl: "Surah Al-Humazah",
      vi: "Surah Al-Humazah",
      ta: "சூரா அல்-ஹுமஸா",
      ur: "سورۃ الهمزة",
      zh: "苏拉·诽谤者",
    },
    surahNumber: 104,
    juzNumber: [30],
    totalAyah: 9,
  },
  {
    surahName: {
      ar: "سورة الفيل",
      bn: "সুরা আল-ফীল",
      en: "Surah Al-Fil",
      hi: "सूरा अल-फील",
      pt: "Surah Al-Fil",
      de: "Surah Al-Fil",
      fr: "Sourate Al-Fil",
      es: "Sura Al-Fil",
      tr: "Sure Fil",
      it: "Sura Al-Fil",
      nl: "Soera Al-Fil",
      ru: "Сура Аль-Филь",
      tl: "Surah Al-Fil",
      th: "ซูเราะห์ อัลฟีล",
      id: "Surah Al-Fil",
      ja: "スーラ アル・フィール",
      ko: "수라 알-필",
      pl: "Surah Al-Fil",
      vi: "Surah Al-Fil",
      ta: "சூரா அல்-பீல்",
      ur: "سورۃ الفيل",
      zh: "苏拉·象",
    },
    surahNumber: 105,
    juzNumber: [30],
    totalAyah: 5,
  },
  {
    surahName: {
      ar: "سورة قريش",
      bn: "সুরা কুরাইশ",
      en: "Surah Quraish",
      hi: "सूरा कुरैश",
      pt: "Surah Quraish",
      de: "Surah Quraish",
      fr: "Sourate Quraish",
      es: "Sura Quraish",
      tr: "Sure Kureyş",
      it: "Sura Quraish",
      nl: "Soera Quraish",
      ru: "Сура Курайш",
      tl: "Surah Quraish",
      th: "ซูรอาห์ กุเรช",
      id: "Surah Quraish",
      ja: "スーラ クライシュ",
      ko: "수라 쿠라이쉬",
      pl: "Surah Quraish",
      vi: "Surah Quraish",
      ta: "சூரா குரைஷ்",
      ur: "سورۃ قریش",
      zh: "苏拉·古莱什",
    },
    surahNumber: 106,
    juzNumber: [30],
    totalAyah: 4,
  },
  {
    surahName: {
      ar: "سورة الماعون",
      bn: "সুরা আল-মাউন",
      en: "Surah Al-Ma'un",
      hi: "सूरा अल-माऊन",
      pt: "Surah Al-Ma'un",
      de: "Surah Al-Ma'un",
      fr: "Sourate Al-Ma'un",
      es: "Sura Al-Ma'un",
      tr: "Sure Al-Maun",
      it: "Sura Al-Ma'un",
      nl: "Soera Al-Ma'un",
      ru: "Сура Аль-Маун",
      tl: "Surah Al-Ma'un",
      th: "ซูเราะห์ อัล-มุน",
      id: "Surah Al-Ma'un",
      ja: "スーラ アル-マウン",
      ko: "수라 알-마운",
      pl: "Surah Al-Ma'un",
      vi: "Surah Al-Ma'un",
      ta: "சூரா அல்மாஊன்",
      ur: "سورۃ الماعون",
      zh: "苏拉·阿尔-马翁",
    },
    surahNumber: 107,
    juzNumber: [30],
    totalAyah: 7,
  },
  {
    surahName: {
      ar: "سورة الكوثر",
      bn: "সুরা আল-কাউসার",
      en: "Surah Al-Kauthar",
      hi: "सूरा अल-कौसर",
      pt: "Surah Al-Kauthar",
      de: "Surah Al-Kauthar",
      fr: "Sourate Al-Kawthar",
      es: "Sura Al-Kauthar",
      tr: "Sure Kevser",
      it: "Sura Al-Kauthar",
      nl: "Soera Al-Kauthar",
      ru: "Сура Аль-Каусар",
      tl: "Surah Al-Kauthar",
      th: "ซูเราะห์อัลเกาศร",
      id: "Surah Al-Kauthar",
      ja: "スーラ アル-カウサル",
      ko: "수라 알-카우사르",
      pl: "Surah Al-Kauthar",
      vi: "Surah Al-Kauthar",
      ta: "சூரா அல்கௌசர்",
      ur: "سورۃ الکوثر",
      zh: "苏拉·阿尔-考萨尔",
    },
    surahNumber: 108,
    juzNumber: [30],
    totalAyah: 3,
  },
  {
    surahName: {
      ar: "سورة الكافرون",
      bn: "সুরা আল-কাফিরুন",
      en: "Surah Al-Kafirun",
      hi: "सूरा अल-काफिरून",
      pt: "Surah Al-Kafirun",
      de: "Surah Al-Kafirun",
      fr: "Sourate Al-Kafirun",
      es: "Sura Al-Kafirun",
      tr: "Sure Kafirun",
      it: "Sura Al-Kafirun",
      nl: "Soera Al-Kafirun",
      ru: "Сура Аль-Кафирун",
      tl: "Surah Al-Kafirun",
      th: "ซูเราะห์อัลกะฟิรุน",
      id: "Surah Al-Kafirun",
      ja: "スーラ アル-カーフィルーン",
      ko: "수라 알-카피룬",
      pl: "Surah Al-Kafirun",
      vi: "Surah Al-Kafirun",
      ta: "சூரா அல்காபிரூன்",
      ur: "سورۃ الكافرون",
      zh: "苏拉·阿尔-卡菲伦",
    },
    surahNumber: 109,
    juzNumber: [30],
    totalAyah: 6,
  },
  {
    surahName: {
      ar: "سورة النصر",
      bn: "সুরা আন-নাসর",
      en: "Surah An-Nasr",
      hi: "सूरा अन-नस्र",
      pt: "Surah An-Nasr",
      de: "Surah An-Nasr",
      fr: "Sourate An-Nasr",
      es: "Sura An-Nasr",
      tr: "Sure Nasr",
      it: "Sura An-Nasr",
      nl: "Soera An-Nasr",
      ru: "Сура Ан-Наср",
      tl: "Surah An-Nasr",
      th: "ซูเราะห์อัน-นัสร์",
      id: "Surah An-Nasr",
      ja: "スーラ アン-ナスル",
      ko: "수라 안-나스르",
      pl: "Surah An-Nasr",
      vi: "Surah An-Nasr",
      ta: "சூரா அந்நஸ்ர்",
      ur: "سورۃ النصر",
      zh: "苏拉·安-奈斯尔",
    },
    surahNumber: 110,
    juzNumber: [30],
    totalAyah: 3,
  },
  {
    surahName: {
      ar: "سورة المسد",
      bn: "সুরা আল-মাসাদ",
      en: "Surah Al-Masad",
      hi: "सूरा अल-मसद",
      pt: "Surah Al-Masad",
      de: "Surah Al-Masad",
      fr: "Sourate Al-Masad",
      es: "Sura Al-Masad",
      tr: "Sure Mesed",
      it: "Sura Al-Masad",
      nl: "Soera Al-Masad",
      ru: "Сура Аль-Масад",
      tl: "Surah Al-Masad",
      th: "ซูรอาห์ อัลมะซัด",
      id: "Surah Al-Masad",
      ja: "スーラ アル・マサド",
      ko: "수라 알-마사드",
      pl: "Surah Al-Masad",
      vi: "Surah Al-Masad",
      ta: "சூரா அல்மசத்",
      ur: "سورۃ المسد",
      zh: "苏拉·棕榈",
    },
    surahNumber: 111,
    juzNumber: [30],
    totalAyah: 5,
  },
  {
    surahName: {
      ar: "سورة الإخلاص",
      bn: "সুরা আল-ইখলাস",
      en: "Surah Al-Ikhlas",
      hi: "सूरा अल-इखलास",
      pt: "Surah Al-Ikhlas",
      de: "Surah Al-Ikhlas",
      fr: "Sourate Al-Ikhlas",
      es: "Sura Al-Ikhlas",
      tr: "Sure İhlas",
      it: "Sura Al-Ikhlas",
      nl: "Soera Al-Ikhlas",
      ru: "Сура Аль-Ихлас",
      tl: "Surah Al-Ikhlas",
      th: "ซูรอาห์ อัลอิคลาส",
      id: "Surah Al-Ikhlas",
      ja: "スーラ アル・イクラス",
      ko: "수라 알-이클라스",
      pl: "Surah Al-Ikhlas",
      vi: "Surah Al-Ikhlas",
      ta: "சூரா அல்-இக்லாஸ்",
      ur: "سورۃ الإخلاص",
      zh: "苏拉·纯洁",
    },
    surahNumber: 112,
    juzNumber: [30],
    totalAyah: 4,
  },
  {
    surahName: {
      ar: "سورة الفلق",
      bn: "সুরা আল-ফালাক",
      en: "Surah Al-Falaq",
      hi: "सूरा अल-फलक",
      pt: "Surah Al-Falaq",
      de: "Surah Al-Falaq",
      fr: "Sourate Al-Falaq",
      es: "Sura Al-Falaq",
      tr: "Sure Felak",
      it: "Sura Al-Falaq",
      nl: "Soera Al-Falaq",
      ru: "Сура Аль-Фаляк",
      tl: "Surah Al-Falaq",
      th: "ซูเราะห์ อัล-ฟาลัค",
      id: "Surah Al-Falaq",
      ja: "スーラ アル・ファラク",
      ko: "수라 알-팔락",
      pl: "Surah Al-Falaq",
      vi: "Surah Al-Falaq",
      ta: "சூரா அல்ஃபலக்",
      ur: "سورۃ الفلق",
      zh: "苏拉·破晓",
    },
    surahNumber: 113,
    juzNumber: [30],
    totalAyah: 5,
  },
  {
    surahName: {
      ar: "سورة الناس",
      bn: "সুরা আন-নাস",
      en: "Surah An-Nas",
      hi: "सूरा अन-नास",
      pt: "Surah An-Nas",
      de: "Surah An-Nas",
      fr: "Sourate An-Nas",
      es: "Sura An-Nas",
      tr: "Sure Nas",
      it: "Sura An-Nas",
      nl: "Soera An-Nas",
      ru: "Сура Ан-Нас",
      tl: "Surah An-Nas",
      th: "ซูรอาห์ อันนาส",
      id: "Surah An-Nas",
      ja: "スーラ アン・ナス",
      ko: "수라 안-나스",
      pl: "Surah An-Nas",
      vi: "Surah An-Nas",
      ta: "சூரா அன்னாஸ்",
      ur: "سورۃ الناس",
      zh: "苏拉·众人",
    },
    surahNumber: 114,
    juzNumber: [30],
    totalAyah: 6,
  },
];

export const tafsirBooksList = [
  {
    nameEn: "Tafseer al Kabir",
    nameBn: "তাফসির আল কাবির",
  },
  {
    nameEn: "Tafsir Ibn 'Abbas",
    nameBn: "তাফসির ইবনে আব্বাস",
  },
  {
    nameEn: "Tafsir Al-Qurtubi",
    nameBn: "তাফসির আল-কুরতুবি",
  },
  {
    nameEn: "Tafsir Ibn Kathir",
    nameBn: "তাফসির ইবনে কাসীর",
  },
  {
    nameEn: "Tafsir Al-Jalalayn",
    nameBn: "তাফসির আল-জালালাইন",
  },
  {
    nameEn: "Tafseer ul Baizawi",
    nameBn: "তাফসির আল-বায়জাভি",
  },
  {
    nameEn: "Tafsir Al-Tabari",
    nameBn: "তাফসির আল-তাবারী",
  },
  {
    nameEn: "Tafseer al-Mazhari",
    nameBn: "তাফসির আল-মাজহারি",
  },
  {
    nameEn: "Tafseer As-Sa'di",
    nameBn: "তাফসির আস-সা’দী",
  },
  {
    nameEn: "Ma'ariful Qur'an",
    nameBn: "মা'আরিফুল কুরআন",
  },
  {
    nameEn: "Tafseer-e-Usmani",
    nameBn: "তাফসির-এ-উসমানী",
  },
  {
    nameEn: "Tafseer al-Madani",
    nameBn: "তাফসির আল-মাদানী",
  },
  {
    nameEn: "Tauzeeh Al-Qur'an",
    nameBn: "তাওজীহুল কুরআন",
  },
  {
    nameEn: "Tafseer Fi Zilalil Quran",
    nameBn: "তাফসির ফি জিলালিল কুরআন",
  },
  {
    nameEn: "Tafhimul Quran",
    nameBn: "তাফহীমুল কুরআন",
  },
  {
    nameEn: "Taiseer ul Quran",
    nameBn: "তাইসীরুল কুরআন",
  },
  {
    nameEn: "Tafsir Fathul Majid",
    nameBn: "তাফসির ফাতহুল মাজীদ",
  },
  {
    nameEn: "Tafseer Ahsan-ul-Bayan",
    nameBn: "তাফসির আহসানুল বায়ান",
  },
];

